### ISSUE TITLE
是否可以在不绑定ck的情况下，直接通过api传来的数据获取装备信息

### ISSUE THREAD

**Issue by davidelectricfree** [yoimiya-kokomi/miao-plugin#10]
请问是否可以在不绑定ck的情况下，直接通过api传来的数据获取装备信息。

现在似乎不绑定ck，就没办法使用那个通过api查询到的装备属性详情，请问有办法不绑定ck，直接通过api那边穿过路的数据，生成那种装备属性图吗？

主要是我那个机器人不想开cookie功能，怕群里面有人因为自己的原因账号出问题找机器人的麻烦

十分感谢。

**Comment by yoimiya-kokomi** [comment]
这个暂时不支持，因为api的数据不完整
为了降低服务器压力，能通过ck查到的数据都没在api内采集，例如圣遗物套装、天赋命座等。
所以需要两边的数据合并起来才是完整面板数据
