### ISSUE TITLE
获取原图指令无效

### ISSUE THREAD

**Issue by StarerDust** [yoimiya-kokomi/miao-plugin#100]
操作正确，发送获取原图指令无效，日志里没有反馈

**Comment by StarerDust** [comment]
[YzBot][17:34:33.528][INFO] recv from: [Private: 24770867(friend)] 胡桃
[YzBot][17:34:33.610][MARK] [米游社查询][uid：159099737][使用已绑定ck：260443018]
[YzBot][17:34:33.952][MARK] [图片生成][miao-plugin/character/card][3次] 239.54kb 333ms
[YzBot][17:34:34.360][INFO] succeed to send: [Private(24770867)] [图片]
[YzBot][17:34:34.362][MARK] [miao-plugin][dispatch] 胡桃 处理完成 753ms
[YzBot][17:34:38.776][INFO] recv from: [Private: 24770867(friend)] 原图

**Comment by xiaomingwa** [comment]
一样一样，希望能快捷获取原图，有些图片挺好的

**Comment by yoimiya-kokomi** [comment]
V3 yunzai适配问题，已经在新版本中fix
