### ISSUE TITLE
执行面板查询相关指令不回复

### ISSUE THREAD

**Issue by QingMuCat** [yoimiya-kokomi/miao-plugin#102]
YunzaiV3.0，喵喵插件1.9.4
报错日志如下：
![-554243cc33d2519](https://user-images.githubusercontent.com/88731921/182670972-eb1f26f9-6e25-4ba6-bff3-aa3df4723614.jpg)

**Comment by yoimiya-kokomi** [comment]
看起来是v3 yunzai的一些异常处理问题

可以尝试在yunzai中设置系统cookie （plugins/genshin/config/mys.pubCk.yaml）
同时对当前用户绑定uid或者ck

**Comment by QingMuCat** [comment]
@yoimiya-kokomi 噢噢，是这样的，我已经绑定过公共CK了，当前用户也绑定了CK的

**Comment by QingMuCat** [comment]
通过重装解决了这个问题 @yoimiya-kokomi
