### ISSUE TITLE
加载出错

### ISSUE THREAD

**Issue by RightTriangle** [yoimiya-kokomi/miao-plugin#103]
8月4日上午9点更新后加载插件出错![image](https://user-images.githubusercontent.com/47479859/182745276-9a132ed9-9f5b-432e-a535-50d5b475e68f.png)

**Comment by liuly0322** [comment]
#104 

```bash
pnpm add https-proxy-agent -w
```

建议顺便尝试更新 Yunzai 版本

**Comment by yoimiya-kokomi** [comment]
安装依赖即可
