### ISSUE TITLE
今天早上更新喵喵插件后提示要安装依赖但无法安装

### ISSUE THREAD

**Issue by StarerDust** [yoimiya-kokomi/miao-plugin#104]
![Screenshot_2022_0804_093557](https://user-images.githubusercontent.com/110532121/182745515-9641125f-a7bf-4928-af66-083201a269b6.png)
![Screenshot_2022_0804_094553](https://user-images.githubusercontent.com/110532121/182745530-4353eb72-2c8f-40f2-ac80-8de42a3f81ef.png)
在根目录powershell输入所需指令后报错

**Comment by liuly0322** [comment]
```bash
pnpm add https-proxy-agent -w
```

这应该是 Yunzai 的提示有点问题

**Comment by yoimiya-kokomi** [comment]
已经规避此问题，安装对应依赖，或者升级miao-plugin即可
