### ISSUE TITLE
关于现有算分算法科学性的一些研究和易行修改建议

### ISSUE THREAD

**Issue by Yuugure-Yuu** [yoimiya-kokomi/miao-plugin#105]
对算分算法做了一些研究。

1. 最优主词缀比例的惩罚似乎不够合理。
根据描述，“最优主词缀比例：对主词条词缀非最优的圣遗物进行评分惩罚。若装备的圣遗物主词条不是当前位置的最高权重主词条，则依据权重差值比例进行分数扣减，最多扣减50%。”
可是比例惩罚会导致圣遗物选择不合理，总词条数更多的套装可能因为词条所在位置不同而分数更低，同词条不平等，这与“圣遗物评分更高的圣遗物更可能适配角色”的目的不符。对圣遗物评比来说，如果总词条数*权重越多的圣遗物越好的话，跟据权重差值比例进行分数扣减在数学上也不合理。

有一个更好的方案是使用绝对分数惩罚。目前主词条以四分之一的比例参与评分，主词条不合理在分数上有所需四分之一的惩罚，可以再减去四分之三的与最优主词缀差值，这样使得评分严格与总词条数*权重成线性关系，圣遗物评分更高的圣遗物更可能适配角色。还有一个方案是主词条直接不计分，减去100%与最优主词缀差值。

2. 总分对齐似乎也不够合理。
根据描述，“总分对齐比例：根据角色不同圣遗物位置可选词条及评分，计算理论最高原始词条总分。为使不同角色不同位置最终总分对齐，规定圣遗物满分为66分。理论总分对齐比例=66/理论最高原始分*100%。”
首先我不理解这个理论总分对齐比例公式和实际总分对齐比例的关系，比如下图中冰伤杯的总分对齐比例是84.6%，暴伤头是93.9%，这是怎么计算出来的呢，即使考虑不同角色因素也让我暂时摸不着头脑。比较不同角色，似乎杯子的总分对齐比例总是低一些。
![D)H_GDD(L@)9~4(%)4U74$M](https://user-images.githubusercontent.com/57028785/182794808-52789518-94b0-4b0c-9507-8725e087f437.gif)
就“比较圣遗物选择”的目的来说，总分对齐会导致圣遗物选择不合理，总词条数更多的套装可能因为词条所在位置不同而分数更低，同词条不平等，这与“圣遗物评分更高的圣遗物更可能适配角色”的目的不符。
总分对齐的初衷可能是排除了主词条分数不同带来的偏差，让不同位置圣遗物可以同等评比，但即使总分对齐了，圣遗物的实际获取难度也没有对齐，因为总分对齐只是最高分对齐，但由于主词缀概率不同，不同位置圣遗物达到相同分数的难度依然不同，也没有考虑套装适配性的分数（散件、2件套和4件套圣遗物的获取难度不同）；以实际的例子来说就是，如果没有总分对齐，评比时比较不同位置圣遗物时要额外考虑位置和套装因素而不仅看分数，如果有的话，还是要额外考虑位置和套装因素而不仅看分数。

有一个能满足总分对齐的所有好处，同时又使得评分严格与总词条数*权重成线性关系的方案，即主词条最优时不参与评分计算，不是最优时计算最优主词缀的惩罚。只是这样搞的话会带来总分降低不好看的问题，那可以全体圣遗物分数乘以一个大于一的权重以和现有总分平衡，可能更好的方案是增加一个“圣遗物等级赋分”，其实就是圣遗物分数统统加一个绝对分数值来使得总分与现在持平，好处是这样一来算分更清晰好算了，多1暴击就是圣遗物多2分，多1爆伤就是圣遗物多1分，没有额外乘区了，易于理解和调整圣遗物争取高分。

3. 最后一个疑问是充能算分，通常来说充能是某一配队下要达到所需分数，然后越高越好但显著边际递减，和其他词条优劣比较不是一个逻辑，因此要搞出合理的评分算法确实比较困难。但无论如何，给严格需要充能的角色的充能词条赋一个远低于1的分都很离谱（比如0.55，神里甚至0.3），有误导性，也让充能越高角色面板越难看，本来充能已经极度受鄙视了。
我个人认为需要充能的角色（几乎全部？）词条权重应该都是1，并给出角色参考合理充能范围。这样将达到圣遗物评分严格与总词条数*权重成线性关系的目的，而且由于pvp中充能受鄙夷的特殊性，几乎没有人会用高充能来pvp，如果给出角色参考合理充能范围的话既帮助了调整配装又进一步杜绝了用高充能pvp。即使由于工作量和配队复杂性暂时不给出角色参考合理充能范围，也最好需要充能的角色分数权重应该都是1，再至少不应该不平等或太低。
最好应该能给不在合理充能范围的配装给出仅与充能挂钩的惩罚分数，这个大概会增加工作量。

所以总结来说就是：
取消最优主词缀比例和总分对齐比例，主词条不计分，对非最优主词缀圣遗物减去100%与最优主词缀差值；增加一个“圣遗物等级赋分”，即圣遗物分数统统加一个绝对分数值来使得总分与现在持平；需要充能的角色（几乎全部？）词条权重都是1，给出角色参考合理充能范围，最好应该能给不在合理充能范围的配装给出仅与充能挂钩的惩罚分数。这样调整的好处是在不同位置圣遗物总分相同的情况下使得评分严格与总所需词条数*权重成线性关系，圣遗物评分更高的圣遗物更可能适配角色，需要越多充能词条的角色评分上不会更低，引导合理充能配装。
以上是我理想中的最优方案，对于其他一些可能的方案上文也进行了相关讨论，以供参考。

**Comment by yoimiya-kokomi** [comment]
哇，写了好多！感谢反馈

感觉对评分很有想法，其实其中的一些思路在当初设计评分逻辑时也想到了，不过在权衡之后选取了现有方案
评分确实是个比较难以足够公允，也包含很多主观判定在里面

关于你的一些建议也说一下我的想法，当然有的也许不一定足够充分
因为本身也没有最适合的方案，无非是在几个都不完美的方案选取了其中一个而已

---

主词条的扣减是个好建议，不过直接扣减主词条分在副词条得分不高的情况下有可能扣成0甚至扣成负分
所以现在选用的方案是参考当前得分，进行按比例扣减，虽然不线性，但符合趋势

---

对齐总分的目的确实是为了圣遗物之间可快速横向比较，防止一些有效词缀比较多的角色圣遗物得分普遍高于其他角色，一般来说辅助角色会吃亏一些
给的建议方案是乘以一个大于1的权重，其实和当前方案是一致的，只是目标总分不一样而已。比如如果目标总分设定为100分那对齐比例其实就都大于1了

而另一个方案统一累加一个值来对齐总分当时确实也有考虑，不过考虑到这种跳跃性比较大最后还是选取了比例方案
例如都同样都是只有一个有效词条的圣遗物，有的角色因为基础累加分高就能拿到比较高的分，有的角色分就比较低

---

至于对齐的比例计算逻辑我以为我写清楚了来着 T.T 
也再说明一下，计算当前角色当前位置的圣遗物的理论最高分：
以副词条分为例：副词条最高分= 6个最高权重最高档强化得分（权重最高的词条最高档强化命中1+5次） + 依次三个次优副词条最高档强化得分
对齐比例 = 目标66分 / 算出的理论最高总分 的比例

---

关于充能的权重
当前版本评分的核心是权重值，所谓权重值是在多个词缀之间比较的时候，正常情况下 高权重的词条会比低权重词条更有价值，所以得分更高
还是以绫华为例：
大部分场景下绫华都是应该选取攻击沙，而不是充能沙，所以攻击的权重比充能高
而头的位置会优先选取双爆头而不是攻击头，所以双爆的权重比攻击高
至于有了这个顺序之后，攻击的权重应该是55还是70，或者充能的权重应该是30还是40，这个确实存在一定主观因素在里面

---

而根据角色再定合理属性范围，再根据属性范围确定词缀分数的方案可能确实更合理，但稍微难以实操
因为其实不止充能，大公鸡、暴击、爆伤、精通等都会存在最优的区间，甚至还存在溢出情况，也没道理专门为充能设定独立规则
但是如此都评分会让整体体系变得更加复杂。。 而且。。 因为最优区间其实还是人拍出来的，还是无法规避主观的经验值
同时，如果要这么精细，其实角色面板提供了另外一个能精细评估角色属性的功能 --- 伤害计算 
但这个看的比较细，所以评分还是用于快速评估来使用了

---

评分的设计是为了能够快速评估圣遗物，但不承担精细比较的职能
例如一个260分的圣遗物大概率比200分的圣遗物要适合，但260分和255分那个更好用就无法用分值来评估了
这里即使分值是线性变化的也没法比较，因为涉及到词条间的平衡，无法单纯用分值来评估

所以最终维持词条分值的线性变化确实也不在第一目标里，最终选取了以比例为主的评分体系
方案确实可能难以足够合理，不过也是当前状态下的一个选择
有需要也可以加下qq592981798继续聊聊，多谢~
