### ISSUE TITLE
#喵喵深渊

### ISSUE THREAD

**Issue by RockRadix** [yoimiya-kokomi/miao-plugin#106]
能否在设置了喵喵深渊替换云崽深渊后，进行判定用户是否绑定Cookie。
如未绑定米游社Cookie，则跳转执行使用uid查询深渊。如绑定了cookie，则执行#喵喵深渊。
一些没有绑定Cookie，在执行#喵喵设置深渊开启，后执行#深渊，会提示未绑定cookie。

**Comment by yoimiya-kokomi** [comment]
更新下最新版，理论上现在应该就是这个逻辑
如果有不符合期望的也可以反馈下

**Comment by RockRadix** [comment]
还是不行。没有绑定cookie，还是会触发未绑定Cookie。
但绑定了Cookie，可以使用（任何字）#深渊，触发旧版深渊。

**Comment by yoimiya-kokomi** [comment]
更新至最新版miao-plugin
