### ISSUE TITLE
怎么让机器人发送se文件夹里的照片

### ISSUE THREAD

**Issue by takichisato** [yoimiya-kokomi/miao-plugin#107]

**Comment by takichisato** [comment]
这是路径
Yunzai-Bot\plugins\miao-plugin\resources\miao-res-plus\character-img

**Comment by yoimiya-kokomi** [comment]
`#喵喵设置`里开启小清新，se目录下的图像会与常规图像一同随机发送
如果指的是只发送se目录图像的话。。。 目前还不支持，勇士
