### ISSUE TITLE
米游社签到报错

### ISSUE THREAD

**Issue by Shvamp** [yoimiya-kokomi/miao-plugin#108]
米游社签到：invalid request

**Comment by YunJin77** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/342

应该是 Yunzai 采用的米游社 api 的问题（米游社今天更新了签到 api，建议等待 Yunzai 更新

**Comment by yoimiya-kokomi** [comment]
等待更新签名算法

**Comment by 1871910889** [comment]
我这里也不能用了

**Comment by Womsxd** [comment]
> 等待更新签名算法

https://github.com/Womsxd/AutoMihoyoBBS/blob/master/setting.py#L2-L6

Salt = "dWCcD2FsOUXEstC5f9xubswZxEeoBOTc"
version="2.28.1"

**Comment by YunJin77** [comment]
fixed

https://github.com/Le-niao/Yunzai-Bot/commit/492c53847b23b93815664426200bca62e2cc8148

**Comment by Shvamp** [comment]
> fixed
> 
> [Le-niao/Yunzai-Bot@492c538](https://github.com/Le-niao/Yunzai-Bot/commit/492c53847b23b93815664426200bca62e2cc8148)

2.2.1的修复了吗？我还没装V3

**Comment by songchenfei** [comment]
> > 等待更新签名算法
> 
> https://github.com/Womsxd/AutoMihoyoBBS/blob/master/setting.py#L2-L6
> 
> Salt = "dWCcD2FsOUXEstC5f9xubswZxEeoBOTc" version="2.28.1"

非常感谢  全局搜索

> > fixed
> > [Le-niao/Yunzai-Bot@492c538](https://github.com/Le-niao/Yunzai-Bot/commit/492c53847b23b93815664426200bca62e2cc8148)
> 
> 2.2.1的修复了吗？我还没装V3

找到这个文件 替换掉签名和版本就好了

**Comment by Shvamp** [comment]
签到好像又失灵了

**Comment by Shvamp** [comment]
好像是自动签到有问题，手动#签到可以签上

**Comment by yoimiya-kokomi** [comment]
更新至 2.2.1的最新版，已解决
