### ISSUE TITLE
问一下大佬，怎么更改#更新面板的默认刷新时间啊

### ISSUE THREAD

**Issue by myz-lgj** [yoimiya-kokomi/miao-plugin#109]

**Comment by YunJin77** [comment]
复制该文件到上一级更改即可

https://github.com/yoimiya-kokomi/miao-plugin/blob/1c744f8234f833610cbc4e6202feda21c6303150/config/system/profile.js#L1-L4

https://github.com/yoimiya-kokomi/miao-plugin/blob/1c744f8234f833610cbc4e6202feda21c6303150/config/system/profile.js#L34

**Comment by YunJin77** [comment]
不过游戏内信息的更新本身就有延迟，其实一般不需要改短

**Comment by yoimiya-kokomi** [comment]
复制 miao-plugin/config/profile_default.js 为 miao-plugin/config/profile.js
不要复制 miao-plugin/config/system/profile.js这个文件，防止影响后续的一些更新

export const requestInterval = 5  
如Yunjin77所说，服务侧及游戏侧都有更新时间，调整更短除了刷屏实际意义不大
