### ISSUE TITLE
今天更新后伤害面板查询报错，之前查过的还能查

### ISSUE THREAD

**Issue by muguodiao** [yoimiya-kokomi/miao-plugin#110]
![image](https://user-images.githubusercontent.com/105115300/182977702-5d0cb358-2aa3-41aa-9a3c-d5c6c68fd38d.png)

**Comment by muguodiao** [comment]
![image](https://user-images.githubusercontent.com/105115300/183226868-622bf602-2fe3-43e7-8213-a12ca286f356.png)

**Comment by yoimiya-kokomi** [comment]
更新至最新版喵喵，重启，看问题是否存在
如果有问题的话提供下uid
