### ISSUE TITLE
#更新面板

### ISSUE THREAD

**Issue by RockRadix** [yoimiya-kokomi/miao-plugin#112]
使用2个以上的机器人请求同一个uid会导致，一个请求中，一个直接进入cd。
![-3704497eac988f76](https://user-images.githubusercontent.com/99504275/183224991-f05830a9-2ba9-4827-8b3d-afa22906d42f.png)
——1.9.5版本

**Comment by RockRadix** [comment]
貌似在1.9.4版本好像就有了。

**Comment by yoimiya-kokomi** [comment]
两个机器人应该使用了同一个redis，不可避免的问题
如果要互不干扰可以使用两个不同的redis db

**Comment by RockRadix** [comment]
但我不是使用同一个redis db。
