### ISSUE TITLE
好像没办法查询武器了

### ISSUE THREAD

**Issue by xiaomingwa** [yoimiya-kokomi/miao-plugin#113]
![image](https://user-images.githubusercontent.com/74846916/183228635-13028640-830e-4cb8-bde7-27d38a08c57e.png)
其他指令都有效就打#雾切#妖刀啥的都不出图片之前还能能查的

**Comment by wangxiaohit** [comment]
3.0版本，#角色图鉴也看不到了

**Comment by yoimiya-kokomi** [comment]
这个不是miao-plugin的功能
如果要查看武器图鉴推荐安装图鉴插件
https://gitee.com/Ctrlcvs/xiaoyao-cvs-plugin

**Comment by xiaomingwa** [comment]
> 这个不是miao-plugin的功能 如果要查看武器图鉴推荐安装图鉴插件 https://gitee.com/Ctrlcvs/xiaoyao-cvs-plugin

谢谢
Thanks♪(･ω･)ﾉ（づ￣3￣）づ╭❤～
