### ISSUE TITLE
“照片”功能无法通过云仔“自定义别名”设置的别名查询

### ISSUE THREAD

**Issue by YunLuoyuu** [yoimiya-kokomi/miao-plugin#114]
“照片”功能无法通过云仔“自定义别名”设置的别名查询

**Comment by yoimiya-kokomi** [comment]
为了同时兼容v2与v3yunzai，miao-plugin目前尽量少的依赖yunzai本身的数据，防止版本差异
如需自定义角色，可在miao-plugin/config/character.js中定义
