### ISSUE TITLE
深渊配队推荐合理性

### ISSUE THREAD

**Issue by xcpxr** [yoimiya-kokomi/miao-plugin#116]
深渊配队，主c都没有的阵容给推荐，让我很难顶啊。

上半房间的阵容和下半房间的阵容能不能分开推荐，只要角色不冲突就好。

比如A上，A下，B上，B下都是过了的，那么A上+B下理论上也能过，只要A上和B下的角色没有冲突，能正常配队就行

**Comment by xcpxr** [comment]
角色比较少，只能替补，但是有些推荐的队伍角色核心c都没有。一队可以找替补，但是二队明显c是神里，没法替补
![%QDX XPP`H9NN8 9@ 6XLU](https://user-images.githubusercontent.com/34615161/183243765-09ede2e2-0697-4c5f-b286-e2175d1d9766.jpg)

**Comment by yoimiya-kokomi** [comment]
目前使用的api服务侧返回的组队列表比较有限，所以可能与当前阵容的适配性可能不高

后面会用更专门的组队api进行匹配，应该效果会更好一些

**Comment by xcpxr** [comment]
你好！我已收到你的邮件，会尽快回复的哈~祝天天开心^^

**Comment by xcpxr** [comment]
多谢大佬
