### ISSUE TITLE
安装插件后，查询角色卡片等不需要私人ck的功能，提示错误

### ISSUE THREAD

**Issue by davidelectricfree** [yoimiya-kokomi/miao-plugin#12]
安装插件后，查询角色卡片等不需要私人ck的功能，提示暂未配置公共查询，但是在yunzai config文件里面已经配置了ck，这个插件如果不配置私人ck，就没有办法使用吗？
备注：
1.确定yunzai config文件有效，因为在装这个插件之前，一直是用那个ck查询的。
2.还有一个很奇怪的现象，可能有助于排查问题，我装完插件后，使用机器人管理员的账号查询#老婆指令，发现它提示“暂未配置公共查询”，于是我使用用户统计功能，发现图片提示ck失效，在我确认其他机器人均可以使用这个ck（即不是ck问题）的情况下，我使用重置用户统计，原来失效的ck变得有效，但是机器人管理员进行查询时，机器人会返回两个信息，一个是米游社接口错误，另一个就是返回过来正确的角色图片。但是其他群成员查询同样会显示暂未配置公共查询。

**Comment by Luomeng0104** [comment]
插件安装后 所有命令都用不了了

**Comment by yoimiya-kokomi** [comment]
应该还是Cookie本身有问题，在查询天赋的时候错误了，Cookie可能是BotCookie或者当前用户绑定的Cookie，可以看下具体Cookie-UID信息

接下来会重新梳理下MysApi的查询逻辑，完善下前置检测及失效的log，定位下问题
issue保留，持续关注

**Comment by davidelectricfree** [comment]
> 应该还是Cookie本身有问题，在查询天赋的时候错误了，Cookie可能是BotCookie或者当前用户绑定的Cookie，可以看下具体Cookie-UID信息
> 
> 接下来会重新梳理下MysApi的查询逻辑，完善下前置检测及失效的log，定位下问题 issue保留，持续关注

emmmmmmm，cookie如果只需要ituid和itoken这两个值，我很确认我填写的是正确的，我的验证方法是，我把完整的ck放到adachi机器人或者hoshino那边，那边的原神插件都是可以识别并且查询信息的，而yunzai这边不管我是单独取出ituid itoken还是把完整的ck加上去，都会报上面的错误。

**Comment by davidelectricfree** [comment]
> 应该还是Cookie本身有问题，在查询天赋的时候错误了，Cookie可能是BotCookie或者当前用户绑定的Cookie，可以看下具体Cookie-UID信息
> 
> 接下来会重新梳理下MysApi的查询逻辑，完善下前置检测及失效的log，定位下问题 issue保留，持续关注

而且现在又出了新的问题，我在不使用你的插件的情况下，单独用yunzai的，使用#角色卡片 这种走公共ck的功能，群里面极个别人能正常使用功能，但是绝大部分人，包括我，触发命令后，终端报

`TypeError: cookieUser.getCookie is not a function
    at Object.Msg.getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/components/Msg.js:170:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GroupMessage.e.getMysApi (file:///C:/GenshinBot/Yunzai-Bot/lib/dealMsg.js:144:12)
    at async Module.wife (file:///C:/GenshinBot/Yunzai-Bot/plugins/miao-plugin/apps/character.js:143:16)
    at async Object.dealMsg (file:///C:/GenshinBot/Yunzai-Bot/lib/dealMsg.js:191:19)`

会报这种错误，但是adachi那边又是好的。

而且最奇怪的是，我删除了data中所有的文件，包括对redis进行卸载，对dump.db数据库文件进行删除，重装redis，使用cnpm unistall 对所有依赖重新卸载安装后，都无法解除报错，就好像计算机里面除了data和dump.db两个进行存储yunzai数据之外，还有其他地方存储了yunzai数据，那个地方的数据损坏了导致即使重装依赖，重装redis数据库，删除data里面所有文件，依然无法解决问题。我现在目前能想到的只有云服务器重装系统了。

我猜测可能是yunzai那边的bug，可能并不是你这边插件的。

**Comment by davidelectricfree** [comment]
> 应该还是Cookie本身有问题，在查询天赋的时候错误了，Cookie可能是BotCookie或者当前用户绑定的Cookie，可以看下具体Cookie-UID信息
> 
> 接下来会重新梳理下MysApi的查询逻辑，完善下前置检测及失效的log，定位下问题 issue保留，持续关注

我昨天把node.js更新到最新的16了，报错是否和我使用了最新版本的node有关啊？
