### ISSUE TITLE
[my-plan] 请问有考虑过/正在做 队伍(逐帧)伤害计算的功能吗

### ISSUE THREAD

**Issue by lumie-fx** [yoimiya-kokomi/miao-plugin#120]
类似某公众号提供的那种。
目前我这边有在写这样的功能，也是基于enka的数据，自己提供模板计算，不过要是你们有考虑/正在做，我就打算先废弃了（开发周期过长）。

![translate](https://user-images.githubusercontent.com/106158693/183281751-744b395c-3adf-4e65-93a5-189d4f8c1734.png)

**Comment by wangxiaohit** [comment]
这个看起来挺不错诶

**Comment by yoimiya-kokomi** [comment]
哇好漂亮~
组队伤害确实是个比较复杂的事情，目前没有在做而且也不在近期的规划内
哈哈，加油~
