### ISSUE TITLE
签到一直提示失败

### ISSUE THREAD

**Issue by blueflywen** [yoimiya-kokomi/miao-plugin#122]
invalid request

**Comment by yoimiya-kokomi** [comment]
`git remote set-url origin https://gitee.com/yoimiya-kokomi/Yunzai-Bot`
切源然后更新

**Comment by blueflywen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
