### ISSUE TITLE
更新面板会提示请先配置公共查询ck，然后再发面板截图

### ISSUE THREAD

**Issue by Wxrmr** [yoimiya-kokomi/miao-plugin#124]
![7F56E3840220A8BA44D275EA719D26E1](https://user-images.githubusercontent.com/106142304/184067833-dc18672a-e5ba-45e1-8cb5-31951e0a0465.jpg)

**Comment by CHxCOOH** [comment]
嗯…虽然知道这是个bug，但是配置完公告ck就行了233

**Comment by yoimiya-kokomi** [comment]
查询命令初始化uid时会检查公共ck情况，目前的bot处理逻辑如此，配置一个就可以
不过面板本身不依赖ck查询

**Comment by yoimiya-kokomi** [comment]
升级最新版yunzai
