### ISSUE TITLE
机器人每日自动签到并且发送了签到成功，但是实际米游社上的签到并没有签上怎么办

### ISSUE THREAD

**Issue by JSKJUN** [yoimiya-kokomi/miao-plugin#125]

**Comment by Lo1iame** [comment]
同样的问题，绑定了200多个ck，收到好多群友反馈显示签到成功，实际米游社里没有签到，手动发签到命令也提示成功，甚至提示已经自动签到过了，实际上依然没签到。

**Comment by ChthollyWn** [comment]
米游社最近新添加了人机验证，没办法

**Comment by mchenryXD** [comment]
> 米游社最近新添加了人机验证，没办法

现在有解决办法吗QAQ

**Comment by kikasyou** [comment]
老米加验证了，这不是机器人的锅

**Comment by yoimiya-kokomi** [comment]
米游社上了验证码
后续yunzai会增加轮签逻辑，但也只能尽可能缓解问题
