### ISSUE TITLE
绫人四命计算技能错误(QE混了)

### ISSUE THREAD

**Issue by hillyson** [yoimiya-kokomi/miao-plugin#130]
绫人4命是E+3级,练度面板统计计算把Q+3了

**Comment by hillyson** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/7822493/184575136-baee7776-4092-4f8b-8ce2-8386966bf182.png">

**Comment by yoimiya-kokomi** [comment]
更新至最新版试下
以及天赋有缓存，如果2小时内查看过对应uid的话，更新后2小时后再看
