### ISSUE TITLE
“#更新面板”提示no-avatar

### ISSUE THREAD

**Issue by sahajata** [yoimiya-kokomi/miao-plugin#136]
部分账号更新面板时提示no-avatar请问有可能是什么原因呢？角色展柜和详情都已经打开了

**Comment by yoimiya-kokomi** [comment]
no-avatar是一个文案遗漏，更新至最新版会提示正确的文案。
不过本身确实还是没有获取到角色数据，确认绑定的uid正确，以及确实在游戏内放置了角色并等待5分钟再获取
