### ISSUE TITLE
面板角色皮肤

### ISSUE THREAD

**Issue by bietiaop** [yoimiya-kokomi/miao-plugin#137]
面板的角色没有皮肤。
enka的接口中也会提供皮肤
![Z 6)O$92}{Q2_G 1RH7_0 N](https://user-images.githubusercontent.com/43831609/185545534-e420e701-62e1-4f1f-ba50-ba2e0750c5f0.png)
我之前想做一个enka的网站供国内使用，因为当时enka在国内加载速度很慢，达到了50s才能加载完图片，我仅仅实现了一些基本功能，之后就没有再继续写了，而且enka的网站速度有明显的提升，我也不维护我之前写的了，在我的网站中判断的该显示哪个角色图片的时候是这样的：
> 接口的一位作者Algoinde提供了一个`characters.json`文件，我把它储存在`charaters`中。
> Algoinde提供的图片文件我放在`./img/ui/`文件夹中。
```javascript
//下面代码中data就是获取到的数据.

/*
* Algoinde说并没有文件能够让角色图片文件跟获取到的数据对应，需要经过特殊处理，这个就不用放出来了，只要解决皮肤问题就可以了
* 下面两行代码可以忽略，if-else中else里面的代码也可以忽略，就是一般情况下角色图片的路径。
*/
let sideImgName = characterInfo["SideIconName"].split('_');
sideImgName = sideImgName[sideImgName.length - 1];

let sideImgFile = new Image();
let showAvatarInfoList = data.playerInfo.showAvatarInfoList;
if (data.avatarInfoList[index]["costumeId"]) { //其中index是角色的索引，判断有无皮肤
    //如果有皮肤
    sideImgFile.src = "./img/ui/" + characters[showAvatarInfoList[index].avatarId.toString()].Costumes[showAvatarInfoList[index].costumeId.toString()].art + ".png";
} else {
    //如果没皮肤
    sideImgFile.src = "./img/ui/UI_Gacha_AvatarImg_" + sideImgName + ".png";
}
```
思路是这样的：
数据中`playerInfo.showAvatarInfoList`里面有一个`avatarId`可以获取角色在`characters.json`对应的数据，`characters.json`里面有`Costume`，里面是皮肤相关图片对应的文件名，如图：
![D_%G54@YUR)0)WAP@Y8~SKS](https://user-images.githubusercontent.com/43831609/185547736-85518444-6bb3-49c8-ad27-18c385a5f5de.png)
*（琴有两个皮肤懂得都懂）*
 
 
上图`Costumes`中，"200301"字段就是皮肤代号，就是第一张图里的`costumeId`。
有一个`art`数据就是对应的皮肤文件名（作者提供的原文件），只需要加上.png就可以对应相应的图片文件。

有皮肤和无皮肤还是有差距的（拿我朋友的UID）
![image](https://user-images.githubusercontent.com/43831609/185550168-11574f7e-bcae-4daf-ba2b-2bae89f575f9.png)

![image](https://user-images.githubusercontent.com/43831609/185550133-4d9e6e07-a786-4975-9301-43c02ef2281e.png)

**Comment by yoimiya-kokomi** [comment]
计划中的功能，其实时装图像文件都准备好了，就在resources/meta/character/对应角色目录下

近期在做底层逻辑重构，等差不多完成后会加时装展示

**Comment by bietiaop** [comment]
> 计划中的功能，其实时装图像文件都准备好了，就在resources/meta/character/对应角色目录下
> 
> 近期在做底层逻辑重构，等差不多完成后会加时装展示

好的
