### ISSUE TITLE
今天重启喵喵后显示QQ版本过低

### ISSUE THREAD

**Issue by 2497162852** [yoimiya-kokomi/miao-plugin#139]
云崽v2.2.1，喵喵v1.9.9
![image](https://user-images.githubusercontent.com/33111780/185676100-a7322b52-2832-49d0-80f5-3ac78694c19f.png)

**Comment by 2497162852** [comment]
![1$}I$5RV(JC@R~LMULJDGFU](https://user-images.githubusercontent.com/33111780/185670262-cc2bc034-1fcb-4819-84f5-b9516791961e.png)
换安卓后..

**Comment by 2497162852** [comment]
两个号都能登没被封

**Comment by 2497162852** [comment]
![image](https://user-images.githubusercontent.com/33111780/185675765-f43ba885-feb6-4cfa-a046-60cf86981bef.png)

**Comment by 2497162852** [comment]
![image](https://user-images.githubusercontent.com/33111780/185676186-bbe17c7b-25f7-4a8a-8aa4-f0bc2ab3ff91.png)

**Comment by yoimiya-kokomi** [comment]
npm update oicq试下

**Comment by 2497162852** [comment]
> npm update oicq试下

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: agent-base@6.0.2
npm WARN Found: peer eslint-plugin-jsx-a11y@"^6.1.1" from eslint-config-airbnb@17.1.0
npm WARN node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"17.1.0" from agent-base@6.0.2
npm WARN   node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-jsx-a11y@"^6.1.1" from eslint-config-airbnb@17.1.0
npm WARN node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"17.1.0" from agent-base@6.0.2
npm WARN   node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: agent-base@6.0.2
npm WARN Found: peer eslint-plugin-react@"^7.11.0" from eslint-config-airbnb@17.1.0
npm WARN node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"17.1.0" from agent-base@6.0.2
npm WARN   node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-react@"^7.11.0" from eslint-config-airbnb@17.1.0
npm WARN node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"17.1.0" from agent-base@6.0.2
npm WARN   node_modules/.pnpm/agent-base@6.0.2/node_modules/agent-base
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rollup-plugin-babel@4.4.0
npm WARN Found: rollup@0.57.1
npm WARN node_modules/.pnpm/dayjs@1.8.36/node_modules/dayjs/node_modules/rollup
npm WARN   dev rollup@"^0.57.1" from dayjs@1.8.36
npm WARN   node_modules/.pnpm/dayjs@1.8.36/node_modules/dayjs
npm WARN     dayjs@1.8.36
npm WARN     node_modules/.pnpm/pm2@5.2.0/node_modules/dayjs
npm WARN     dayjs@1.8.36
npm WARN     node_modules/.pnpm/@pm2+agent@2.0.1/node_modules/dayjs
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer rollup@">=0.60.0 <3" from rollup-plugin-babel@4.4.0
npm WARN node_modules/.pnpm/dayjs@1.8.36/node_modules/dayjs/node_modules/rollup-plugin-babel
npm WARN   dev rollup-plugin-babel@"^4.0.0-beta.4" from dayjs@1.8.36
npm WARN   node_modules/.pnpm/dayjs@1.8.36/node_modules/dayjs
npm WARN
npm WARN Conflicting peer dependency: rollup@2.78.1
npm WARN node_modules/rollup
npm WARN   peer rollup@">=0.60.0 <3" from rollup-plugin-babel@4.4.0
npm WARN   node_modules/.pnpm/dayjs@1.8.36/node_modules/dayjs/node_modules/rollup-plugin-babel
npm WARN     dev rollup-plugin-babel@"^4.0.0-beta.4" from dayjs@1.8.36
npm WARN     node_modules/.pnpm/dayjs@1.8.36/node_modules/dayjs
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: debug@2.6.9
npm ERR! Found: dev karma-chai@"^0.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev karma-chai@"^0.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2022-08-21T13_36_23_085Z-debug-0.log

**Comment by 2497162852** [comment]
> npm update oicq试下

报错了，我先百度下看看

**Comment by 2497162852** [comment]
> npm update oicq

![image](https://user-images.githubusercontent.com/33111780/185997169-bccd2a67-308c-440d-b42a-0c03d5a5ee5a.png)
喵佬！

**Comment by 2497162852** [comment]
> npm update oicq试下

![image](https://user-images.githubusercontent.com/33111780/186001518-cd868ad0-161a-47b0-a9fb-13f8d538be89.png)
喵佬！

**Comment by dxylive** [comment]
有解决方案了么 大佬

**Comment by 2497162852** [comment]
> 我今天更新后也出现这个问题，后来将登录设备配置从Mac改为其他设备类型就可以正常登陆了

换完后每天都至少被冻一次，第二个号之前没被冻过
