### ISSUE TITLE
关于token不发放

### ISSUE THREAD

**Issue by 1055169799** [yoimiya-kokomi/miao-plugin#14]
这边了解到查询面板的token不发放的原因是服务器压力问题，那请问可否发布这个查询面板的方法，大家自己看看能否有条件部署使用。

**Comment by ttimochan** [comment]
emmm，确实，给一个部署方法也行，也能减轻作者服务器压力

**Comment by yoimiya-kokomi** [comment]
面板查询能力是另一位匿名大佬提供的，逻辑不对外
以及面板查询对与服务器（需要GPU）及环境部署与运维上都有不小要求
所以目前来看应该不会公开部署能力

**Comment by 1055169799** [comment]
> 面板查询能力是另一位匿名大佬提供的，逻辑不对外
> 以及面板查询对与服务器（需要GPU）及环境部署与运维上都有不小要求
> 所以目前来看应该不会公开部署能力

那这不是很尴尬，token发不出来，部署方法也没有…

**Comment by zizxzy** [comment]
同意
