### ISSUE TITLE
查他人功能无法关闭

### ISSUE THREAD

**Issue by weilai5201314** [yoimiya-kokomi/miao-plugin#140]
![1](https://user-images.githubusercontent.com/99032101/185739886-0ef5bb01-292b-4c42-9fd9-9b79e0eb1822.png)
![3](https://user-images.githubusercontent.com/99032101/185739894-284a7548-d9fb-4c6d-9ff1-1c8299ea56fa.jpg)
如图，不管是开启还是关闭，都可以查他人资料，包括帮助对方更新面板，查看面板。

**Comment by weilai5201314** [comment]
而抽卡记录，不管是开启还是关闭都无法帮他人查询。

**Comment by yoimiya-kokomi** [comment]
目前yunzai底层逻辑里暂不支持单独屏蔽此功能，暂时隐藏此配置了
