### ISSUE TITLE
装了yunzai-v3，发现深渊面板用不了，然后根据code页面的提示更换远程仓库地址后Git pull失败

### ISSUE THREAD

**Issue by fsqhn** [yoimiya-kokomi/miao-plugin#141]
如题，在yunzai根目录运行 “git remote set-url origin https://github.com/yoimiya-kokomi/Yunzai-Bot”，然后git pull后系统提示

remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 15 (delta 12), reused 11 (delta 8), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/yoimiya-kokomi/Yunzai-Bot
   b4744bd..f0546db  master     -> origin/master
Your configuration specifies to merge with the ref 'main'
from the remote, but no such ref was fetched.

然后启动yunzai-bot 还是显示版本号v3.0.0。
linux环境，阿里云上搞的

**Comment by citydirector** [comment]
直接删除文件夹重新拉取，不能这样换的；
另外，这条更改远程仓库地址的命令是给之前用旧版v2的用户看的，不是给v3的用户看的（v3的readme在下面）

**Comment by yoimiya-kokomi** [comment]
嗯，无法从V3直接换源降级到V2
以及目前V3基本稳定，后面喵喵也会切换到V3为基线的版本
