### ISSUE TITLE
请问面板服务又是显示：请求失败:undefined该如何解决，已经用了中转

### ISSUE THREAD

**Issue by woshidxx** [yoimiya-kokomi/miao-plugin#145]

**Comment by 2497162852** [comment]
两个节点都用了？

**Comment by yoimiya-kokomi** [comment]
undefined是个文案错误，更新至最新版会提示对应错误文案
不过更新失败本身是服务问题，可能是enka服务访问不稳定或服务问题

**Comment by yoimiya-kokomi** [comment]
undefined是个文案错误，更新至最新版会提示对应错误文案
不过更新失败本身是服务问题，可能是enka服务访问不稳定或服务问题
