### ISSUE TITLE
云崽显示QQ版本过低，但另一个号没事

### ISSUE THREAD

**Issue by 2497162852** [yoimiya-kokomi/miao-plugin#146]
云崽v2.2.2，喵喵v1.9.10
![image](https://user-images.githubusercontent.com/33111780/186312892-559a9518-c503-4731-a1ba-8df682dea69f.png)

**Comment by 2497162852** [comment]
另一个号刚才重启完也寄了

**Comment by yoimiya-kokomi** [comment]
yunzai的conifg中更换一下登录设备试下

**Comment by 2497162852** [comment]
> yunzai的conifg中更换一下登录设备试下

改了之后每天被冻一两次，我把签到关了后就没被冻过

**Comment by yoimiya-kokomi** [comment]
签到不影响qq冻结，把签到结果的推送关了
