### ISSUE TITLE
深渊十二层出场率图片异常

### ISSUE THREAD

**Issue by SleepyAsh0191** [yoimiya-kokomi/miao-plugin#149]
![image](https://user-images.githubusercontent.com/64446140/187017472-620656a7-e5f6-434f-ac10-ab0a6858a16f.jpeg)
如图所示，其他层数是正常的。

**Comment by yoimiya-kokomi** [comment]
估计请求失败并缓存了错误的数据，一般缓存为10分钟
目前再查看应该就恢复正常了
