### ISSUE TITLE
最新喵喵，使用的Enka国内的API，但#更新面板，经常服务器过载

### ISSUE THREAD

**Issue by mogudunji** [yoimiya-kokomi/miao-plugin#152]
最新喵喵，使用的Enka国内的API，但#更新面板，经常服务器过载
![Snipaste_2022-08-29_19-12-46](https://user-images.githubusercontent.com/48897686/187188956-527b13dd-c2a3-4671-850b-d358e41fe0dd.png)
![Snipaste_2022-08-29_19-12-26](https://user-images.githubusercontent.com/48897686/187188974-3b33a935-fb5a-49dc-8301-ede48bcafd82.png)

**Comment by mogudunji** [comment]
![Snipaste_2022-08-29_19-12-46](https://user-images.githubusercontent.com/48897686/187189061-4939bad8-6769-4a92-8885-d7c5d5ceaa1f.png)

**Comment by swh20021102** [comment]
我测试了一下，国内的那两个节点都提示这个，反倒是默认的节点可以正常更新面板

**Comment by yoimiya-kokomi** [comment]
最近Enka服务对国内uid的稳定性确实不高，enka官方也在解决

具体请求地址可根据具体访问情况进行选择
