### ISSUE TITLE
重启失败

### ISSUE THREAD

**Issue by wooodswu** [yoimiya-kokomi/miao-plugin#157]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/87766834/187902794-5c6205b5-ee94-4dd7-9cf1-10726c70e281.png">
重启能用了：redis-cli
config set stop-writes-on-bgsave-error no

但是，签到失败：验证码失效
<img width="567" alt="image" src="https://user-images.githubusercontent.com/87766834/187906292-92004c5b-d5e6-4818-8383-fab13d56dfc0.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/87766834/187908352-c4276460-9040-4aab-9539-79f7d51772ee.png">

**Comment by yoimiya-kokomi** [comment]
签到失败是因为MHY加了验证码的安全校验，短期内无解
