### ISSUE TITLE
[须弥角色]角色图片显示裂开

### ISSUE THREAD

**Issue by ayakasuki** [yoimiya-kokomi/miao-plugin#159]
![image](https://user-images.githubusercontent.com/20859971/188261784-6589f1b6-6805-4cdb-9ae0-6c358df63f17.png)
如图，并且没有草神瞳和须弥探索进度—— 不晓得是喵喵插件还是云zai2.18的问题

**Comment by yoimiya-kokomi** [comment]
2.1.8版本过老
换喵喵版本YunzaiV2或者换官方V3版本
详见README
