### ISSUE TITLE
绫人伤害计算错误

### ISSUE THREAD

**Issue by hsx-123** [yoimiya-kokomi/miao-plugin#161]
闪浪伤害没计算上，显示为nan
![-7049ff3e0a2b47b4](https://user-images.githubusercontent.com/54926560/188652262-98e0a46f-429f-495b-b7ee-e198929443cb.jpg)

**Comment by yoimiya-kokomi** [comment]
新角色天赋数据格式变化导致获取失败，已经在最新版本fix
