### ISSUE TITLE
V3版本character_default.js问题

### ISSUE THREAD

**Issue by e4ya** [yoimiya-kokomi/miao-plugin#166]
更改character_default.js文件角色关系重启后未生效
但直接更改character.js文件重启后生效
怀疑character_default.js并未与character.js合并
谢谢大佬~
![image](https://user-images.githubusercontent.com/87714554/189053479-a30ec723-d730-4383-96ca-60e6dab3b747.png)

**Comment by yoimiya-kokomi** [comment]
修改方式仔细看下character_default.js上方的描述

以及不要修改system下的配置文件，可能会导致与后续更新冲突

**Comment by e4ya** [comment]
谢谢大佬
