### ISSUE TITLE
角色面板更新后无法获取到圣遗物

### ISSUE THREAD

**Issue by VeritasAlex** [yoimiya-kokomi/miao-plugin#167]
![QQ图片20220909093340](https://user-images.githubusercontent.com/57402050/189253836-37d7b42b-5035-4743-b515-a379969e8e0c.jpg)

**Comment by Ponysesame** [comment]
![dcb72f5dc2ca064f92654e145209dfb1](https://user-images.githubusercontent.com/110590237/189257514-dcd9a280-92f7-40bd-906b-43f1872560d7.jpg)
一样的问题，是胡桃api出问题了吗？

**Comment by GoverSky** [comment]
同样的问题，我暂时给回滚了

**Comment by yoimiya-kokomi** [comment]
emm，确认。。
更新至最新版本，已修正
