### ISSUE TITLE
#上传深渊和#喵喵深渊显示上传失败

### ISSUE THREAD

**Issue by eiheixwy** [yoimiya-kokomi/miao-plugin#169]
![Screenshot_20220909_141137](https://user-images.githubusercontent.com/106575654/189284543-0fcf9a03-b4a6-4b01-ad55-993e0273d669.jpg)
![Screenshot_20220909_141337](https://user-images.githubusercontent.com/106575654/189284559-bad17694-0125-4ef3-88be-aabdbab29073.jpg)

**Comment by canyi2** [comment]
![image](https://user-images.githubusercontent.com/95406510/190665323-e627b999-ce82-49ef-ae7d-6d3f278b0c6b.png)
我也是欸

**Comment by canyi2** [comment]
对了，已解决，我是直接翻到那个html文件，直接改的原代码，反正现在能用了（
