### ISSUE TITLE
未能获得圣遗物详情

### ISSUE THREAD

**Issue by Fachep** [yoimiya-kokomi/miao-plugin#172]
更新[c9fe04](https://github.com/yoimiya-kokomi/miao-plugin/commit/c9fe04952ebfbc6f9b786f2ec06ca937f55eec45)后
`#[角色]圣遗物`指令返回`未能获得圣遗物详情，请重新获取面板信息后查看`
俩bot测试同样结果
![BJ7QI 4VXX~L Q%`(QGCS~O](https://user-images.githubusercontent.com/31302548/189505512-2d80d539-911e-433e-9289-ace761221da3.png)
![}G}Z }6(LKMX5G6LQ0$X(JG](https://user-images.githubusercontent.com/31302548/189505514-0dfe0db9-4ec1-4004-a77c-f46065717e47.png)

**Comment by yoimiya-kokomi** [comment]
确实有个属性标记错误，更新至最新版试一下
