### ISSUE TITLE
角色攻略查询不能用

### ISSUE THREAD

**Issue by akmioto** [yoimiya-kokomi/miao-plugin#18]
查询#xx攻略 bot回复暂无xx攻略
![QQ截图20220519101220](https://user-images.githubusercontent.com/105832022/169189037-f5795e84-c976-452e-a550-f987992ed311.png)

**Comment by yoimiya-kokomi** [comment]
角色攻略是Yunzai的功能，不是喵喵的
可以尝试将app/strategy_xf.js fetch(url, { method: "get" }); 中请求的url改为url_1试下
