### ISSUE TITLE
报错:SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by guobaisanxiu** [yoimiya-kokomi/miao-plugin#181]
![IMG_20220914_002306](https://user-images.githubusercontent.com/66705405/189955327-db38ab82-41e8-48b5-9c98-be8c41e71084.jpg)
报错如图，将插件重载依然报错，浏览器能够正常访问https://enka.network/

**Comment by guobaisanxiu** [comment]
是不是json格式错了(●—●)

**Comment by SleepyAsh0191** [comment]
修改`profile.js`将面板服务切换为国内节点。
（实际上是傻X Cloudflare的鬼）

**Comment by yoimiya-kokomi** [comment]
更新到miao-plugin最新版本

**Comment by guobaisanxiu** [comment]
>
