### ISSUE TITLE
胡桃q融化伤害计算错误

### ISSUE THREAD

**Issue by 6DDUU6** [yoimiya-kokomi/miao-plugin#184]
自己修改了下resources/meta/character/胡桃/calc.js文件，加了一个蒸发和融化：
![image](https://user-images.githubusercontent.com/51308585/190128318-c871bcd6-6e0e-41d0-b797-38dc769e67ae.png)
结果出来的融化比蒸发伤害还低
![image](https://user-images.githubusercontent.com/51308585/190128995-f7ace87d-c0be-4d10-94e4-6d5b7c5c5ed2.png)

**Comment by yoimiya-kokomi** [comment]
自己加的融化吗？
胡桃buffs里面需要增加rh，以计算精通对融化的加成buff
