### ISSUE TITLE
夜兰q伤害计算错误

### ISSUE THREAD

**Issue by PrussianBlueCN** [yoimiya-kokomi/miao-plugin#185]
面板计算值暴击6700:![E6450D1F-EB0A-485E-AF54-DDC0BFE6A99B](https://user-images.githubusercontent.com/110645427/190220055-3f24e1f0-1243-4851-8d04-ae554114f596.jpeg)
实测即使是单人队伍伤害也是在9000-10000级的
![Uploading E2A39F40-5635-4790-BACA-62F9EA4BBC86.png…]()

**Comment by PrussianBlueCN** [comment]
uid 231814528

**Comment by PrussianBlueCN** [comment]
第二张图好像丢了，重新发一下
![Uploading BB5C15CD-5D01-446D-AC0C-CF0B2E397700.png…]()

**Comment by yoimiya-kokomi** [comment]
缺失的伤害来自q启动后的伤害加成buff
现已按照最大buff层数计算q伤害
