### ISSUE TITLE
#面板练度统计 的天赋不显示

### ISSUE THREAD

**Issue by CUZNIL** [yoimiya-kokomi/miao-plugin#186]
大概是昨天开始频繁出现的，新绑定的用户使用该指令会出现天赋不显示的情况
具体如图，可以看到下图中有且仅有胡桃开始的8个角色无法显示天赋数据
![N83L`M8IDZUO$BT{@F8TE8V](https://user-images.githubusercontent.com/76582404/190334026-c288e9b9-3273-4649-9913-b906eba1097e.gif)
版本是最新版本miao和yunzai
![4E%EUSIFNYBWQY4JI6)_CG](https://user-images.githubusercontent.com/76582404/190334461-f6e4a261-9920-4464-8e8b-8c2e814ceafc.png)
![S75S6MBV@BX488H_I0WKYAB](https://user-images.githubusercontent.com/76582404/190334517-50dc0963-effb-4b38-af1b-92bb5e5181c2.png)
然后以下是完整的运行日志[TRACE]：
1/2:
![image](https://user-images.githubusercontent.com/76582404/190335847-8384d581-506a-4309-a715-5e9bec00f154.png)
2/2:
![image](https://user-images.githubusercontent.com/76582404/190335881-8af6f8be-c6bd-4046-84e4-137f5e4ab6b3.png)

**Comment by yoimiya-kokomi** [comment]
更新至最新版yunzai
不过近期mys升级了ck逻辑，确实可能会有比较多失效的情况
