### ISSUE TITLE
关于菜单功能问题

### ISSUE THREAD

**Issue by 1485470102** [yoimiya-kokomi/miao-plugin#187]
能不能添加一个菜单添加功能
有时候yunzai会更新新功能 但是菜单里面没有

**Comment by fsqhn** [comment]
装个锅巴插件，能够改猫猫插件的帮助图…… 我是直接把装的其他插件的帮助命令全写猫猫帮助里了。

**Comment by yoimiya-kokomi** [comment]
嗯，建议锅巴插件，很好用～
