### ISSUE TITLE
老婆和角色查询出错了，请问怎么解决

### ISSUE THREAD

**Issue by Sakurai233** [yoimiya-kokomi/miao-plugin#19]

**Comment by Sakurai233** [comment]
![QQ截图20220520190316](https://user-images.githubusercontent.com/102948139/169515004-70ee933f-8f16-4dca-b398-ba0b46a676ee.png)

**Comment by NomadThanatos** [comment]
Duplicate as https://github.com/Le-niao/Yunzai-Bot/issues/148

**Comment by yoimiya-kokomi** [comment]
此问题已在Yunzai 2.1.9 修复
可尝试切换到此分支进行更新 https://github.com/yoimiya-kokomi/Yunzai-Bot
