### ISSUE TITLE
树莓派chromium自定义路径启动不了，还是会启动yunzai路径里的默认chromium

### ISSUE THREAD

**Issue by RightTriangle** [yoimiya-kokomi/miao-plugin#190]
之前是没问题的，更新后就不行了，一直自定义不了路径
![image](https://user-images.githubusercontent.com/47479859/190650446-d32b2a53-6b01-4d43-8cf5-758a3e0bb8dc.png)
![image](https://user-images.githubusercontent.com/47479859/190650850-abb0e371-04f8-41c0-b26f-6b09c7b2f833.png)

**Comment by hyw498169842** [comment]
遇到了同样的问题，可以在adapter/lib/puppeteer.js中手动指定路径解决

**Comment by boli-zhazi** [comment]
请问具体在puppeteer.ha 哪里指定路径？

**Comment by RightTriangle** [comment]
问题已经解决，用了miao插件的话需要把两个puppeteer.js都改了，一个是插件的adapter/lib/puppeteer.js，还有一个也是lib文件夹里

**Comment by boli-zhazi** [comment]
> 问题已经解决，用了miao插件的话需要把两个puppeteer.js都改了，一个是插件的adapter/lib/puppeteer.js，还有一个也是lib文件夹里

具体是改哪行

**Comment by yoimiya-kokomi** [comment]
目前puppeteer.js已经统一使用yunzai的了，修改yunzai的即可
