### ISSUE TITLE
关于激化

### ISSUE THREAD

**Issue by NRZ091** [yoimiya-kokomi/miao-plugin#195]
在未来有没有可能会添加激化条件下阿晴，小艾咪等角色的激化加伤显示⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by yoimiya-kokomi** [comment]
会，不过最近在做底层重构，重构完成后会增加新的伤害计算

**Comment by 793967240** [comment]
关于激化伤害近期有排期添加了吗

**Comment by Aniverse** [comment]
斗胆催更一下小艾咪（皇女菲谢尔）的激化伤害计算
