### ISSUE TITLE
载入插件错误，enka

### ISSUE THREAD

**Issue by 1120647385** [yoimiya-kokomi/miao-plugin#197]
![QQ截图20220923143654](https://user-images.githubusercontent.com/67355533/191904493-ccad72e0-d207-40bd-8ec2-fd575627a609.png)

**Comment by yoimiya-kokomi** [comment]
这个非miao-plugin的功能，是yunzai V3自带的

**Comment by liuly0322** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/639
