### ISSUE TITLE
圣遗物两件套效果无法触发

### ISSUE THREAD

**Issue by 1-4134-5386-4941** [yoimiya-kokomi/miao-plugin#198]
当装备有赌徒、宗室、武人的四件套时，对应两件套效果无法在伤害计算中正确触发。
位置：`resources\meta\reliquaries\calc.js`：
```js
武人2: {
    title: '武人2: 普攻与重击造成的伤害提高15%',
    data: {
      aDmg: 15,
      a2Dmg: 15
    }
  },
  武人4: {
    title: '武人4：施放元素战技后的8秒内，普攻和重击伤害提升25%',
    data: {
      aDmg: 25,
      a2Dmg: 25
    }
  },
...
赌徒2: {
    title: '赌徒2：元素战技造成的伤害提升20%',
    data: {
      eDmg: 20
    }
  },
...
昔日宗室之仪2: {
    title: '宗室2：元素爆发造成的伤害提升20%',
    data: {
      qDmg: 20
    }
  },
昔日宗室之仪4: {
    title: '宗室4：施放元素爆发后，攻击力提升20%',
    check: ({ currentTalent }) => !currentTalent || currentTalent === 'q',
    data: {
      atkPct: 20
    }
  }
```
下图为装备了赌徒4的辛焱，计算e伤害时无两件套buff：
![image](https://user-images.githubusercontent.com/57062259/192083550-58451fca-c303-4a95-bdf5-25944d07ec10.png)
但只装备两件套时却可以正确计算：
![image](https://user-images.githubusercontent.com/57062259/192083963-f69aa864-2a2f-42f1-a1de-9f08fa0013a7.png)

**Comment by 1-4134-5386-4941** [comment]
另外，武人2的圣遗物描述使用了英文冒号，导致buff列表中显示效果异常：
![image](https://user-images.githubusercontent.com/57062259/192084088-2a7d555a-1ca6-4be8-ba8f-6167e6159d0b.png)

**Comment by yoimiya-kokomi** [comment]
确认，会在稍晚的2.0版本中修复
