### ISSUE TITLE
尚未配置更新Api，无法更新数据~

### ISSUE THREAD

**Issue by YanQian01** [yoimiya-kokomi/miao-plugin#2]
发送：#雷神详情
答：尚无雷电将军的面板详情。请在将角色展示在【游戏内】的“角色展柜”中，并打开“显示角色详情”。设置完成5分钟后使用 #获取游戏角色详情 命令进行数据获取。
发送#获取游戏角色详情
答：尚未配置更新Api，无法更新数据~
![image](https://user-images.githubusercontent.com/99258837/163818856-3f044953-5a76-44e1-b039-71c1804a6fb8.png)
文件复制到位，为何还是无法使用#角色面板

**Comment by yoimiya-kokomi** [comment]
API非公开，请到YunzaiBot群找喵喵或九章私聊申请
