### ISSUE TITLE
新绑定ck的无法使用#上传深渊

### ISSUE THREAD

**Issue by Flyky** [yoimiya-kokomi/miao-plugin#201]
更新插件后，以前绑定过ck的可以正常使用#上传深渊
新绑定ck的群员使用#上传深渊一直回复【请绑定ck后再使用#上传深渊】

**Comment by Flyky** [comment]
#体力 可以正常使用， #练度统计可以正常查到所有角色和技能等，应该只有上传深渊不行

**Comment by CKing1228** [comment]
我这也是，主人的ck可以使用喵喵深渊，群友绑定的ck只能使用体力，不能使用喵喵深渊

**Comment by yoimiya-kokomi** [comment]
更新至最新版看是否还有问题，如果有问题提供下yunzai的版本

**Comment by Flyky** [comment]
> 更新至最新版看是否还有问题，如果有问题提供下yunzai的版本

没问题了。我close了~

**Comment by yoimiya-kokomi** [comment]
更新至Yunzai最新版
