### ISSUE TITLE
#面板练度统计 的天赋获取异常

### ISSUE THREAD

**Issue by CUZNIL** [yoimiya-kokomi/miao-plugin#206]
如图，`#练度统计`可以正常获取天赋，`#面板练度统计`却不行。

![) UD6%`%{~EAZ46IOKEY7VC](https://user-images.githubusercontent.com/76582404/194204750-7b370ee5-8741-47f1-8c32-0f295a4e1765.png)

上图是与bot的聊天记录，下图是bot返回的`#面板练度统计`的大图
![@{~KA01T~9876K7}{H4XQSJ](https://user-images.githubusercontent.com/76582404/194203845-e7f12463-d2ed-4c37-83e8-1da3a9b6f87e.gif)
如下图所示，yunzai和miao都是最新版本。
![@CH%0YG)LA1F71AOHVYEWUM](https://user-images.githubusercontent.com/76582404/194204287-c9bdf401-3335-4ca6-ad35-6b9161aad544.png)
最后是四张bot终端的运行截图，如果加载较慢可以移步[b站动态](https://t.bilibili.com/713762052248698919)
![image](https://user-images.githubusercontent.com/76582404/194204542-f38794f9-0a7e-44cf-9c17-b4835a4ed8a1.png)
![image](https://user-images.githubusercontent.com/76582404/194204550-55faa5cf-c628-40db-9f3f-07b23815963f.png)
![image](https://user-images.githubusercontent.com/76582404/194204554-96c7f7cd-9bd2-45a8-86ee-295bcff088e8.png)
![image](https://user-images.githubusercontent.com/76582404/194204563-72bfe816-7e1b-4fc1-a337-4a8847f9544f.png)

**Comment by CUZNIL** [comment]
有没有大佬救一救orz

**Comment by yoimiya-kokomi** [comment]
更新至最新版yunzai以及miao-plugin试试
目前针对ck的分配应该做了优化
