### ISSUE TITLE
面板查询，方案变化导致评分混乱

### ISSUE THREAD

**Issue by duur** [yoimiya-kokomi/miao-plugin#207]
![Screenshot_20221006_125020_com tencent mobileqq](https://user-images.githubusercontent.com/10671566/194217178-557f141b-6f4b-4d76-9df0-ad2d711b9c63.jpg)
雾切3次查询，面板不变都是44/248。
中间穿插2次绿剑查询（凯亚-绿剑绝缘4、凯亚-绿剑）。
导致同一面板（凯亚-通用）评分异常变化（242.5-233.7-233）。
经检查发现查完绿剑之后，带雾切的生命词条也标亮了。怀疑是切换方案，有效词条没刷新。
只发现凯亚有。其他角色/武器不太清楚

**Comment by duur** [comment]
是2.0alpha8分支- -手滑了见谅

**Comment by duur** [comment]
是2.0分支- -手滑了见谅

**Comment by duur** [comment]
2.0alpha8- -

**Comment by yoimiya-kokomi** [comment]
收～ 后面排查下

**Comment by duur** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by duur** [comment]
更新到2.0.3，解决了（
