### ISSUE TITLE
关于一个ck下多账号，查询深渊配队的情况

### ISSUE THREAD

**Issue by MuXia-0326** [yoimiya-kokomi/miao-plugin#209]
切换uid后获取深渊配队情况，就会检测不到角色，我觉得是一个bug，希望能解决一下
![help_img](https://user-images.githubusercontent.com/63834850/194736238-9e5dc011-6d2f-435f-aca6-7fd9e6f99247.png)

**Comment by yoimiya-kokomi** [comment]
V3Yunzai的话更新至最新版本后再试一下

**Comment by MuXia-0326** [comment]
> V3Yunzai的话更新至最新版本后再试一下

新版本切换之后就这样了

![image](https://user-images.githubusercontent.com/63834850/197716504-a9be5ae7-db1a-488e-b2dd-58109b404f86.png)

**Comment by MuXia-0326** [comment]
我两个uid绑在一个米友社账号上，所以ck肯定是绑定了的，并且没过期

**Comment by yoimiya-kokomi** [comment]
ok，这种情况稍晚确认下

**Comment by MuXia-0326** [comment]
好的，辛苦了
