### ISSUE TITLE
戳一戳无反应

### ISSUE THREAD

**Issue by CuteLittleSky** [yoimiya-kokomi/miao-plugin#210]
![Screenshot_2022-10-13-08-50-19-57_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/62592731/195473959-0a9354a8-1072-491b-9d04-fd94afa581bc.jpg)
![Screenshot_2022-10-13-08-50-00-88_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/62592731/195473976-78c99262-c038-452b-929a-756b0586dcf5.jpg)
如图,日志无响应
云崽版本:3.0.0 10/13更新
喵喵版本:2.0.3 10/13更新

**Comment by DDGG123** [comment]
可能和你选择的QQ端口有关，有些端口比如手表和Mac好像不支持戳一戳
