### ISSUE TITLE
深渊配队查看失败

### ISSUE THREAD

**Issue by hchen1134** [yoimiya-kokomi/miao-plugin#217]
提示“请绑定CK以使用此功能...”，其余需要绑ck的功能可以正常使用

**Comment by Capybara-sea** [comment]
同，绑定cookie后 无法查询查询深渊数据， 需要重启后才能查询，cookie本身是没问题的，可以签到

![image](https://user-images.githubusercontent.com/67335679/196494600-138af149-e5b4-4aa5-930a-0a917087408b.png)

**Comment by yoimiya-kokomi** [comment]
更新Yunzai至最新版本
