### ISSUE TITLE
字体与原来不同

### ISSUE THREAD

**Issue by sakuramob** [yoimiya-kokomi/miao-plugin#221]
![7ecd470aa566fd1a](https://user-images.githubusercontent.com/111983340/196699141-0a6982dd-6e61-435c-a17e-436a0e9182f8.jpg)
不知道为什么重启了一次字体就变成这样了，有没有大佬指出问题在哪

**Comment by yoimiya-kokomi** [comment]
看下系统字体渲染的设置
比如windows的话就是控制面板里找一下clearType，设置开启并调整对应参数
