### ISSUE TITLE
绑定uid指令yunzai接收到了对应消息，但插件未响应

### ISSUE THREAD

**Issue by AlwaysGuu** [yoimiya-kokomi/miao-plugin#222]
<img width="568" alt="Screenshot 2022-10-20 at 12 04 01" src="https://user-images.githubusercontent.com/47023706/196853741-581117b6-3c0f-45fa-abd6-a62e1e851bbb.png">

**Comment by yoimiya-kokomi** [comment]
绑定uid的命令是 #绑定123456789
以及绑定uid是yunzai本体的功能不是miao-plugin插件的
