### ISSUE TITLE
面板列表样式异常

### ISSUE THREAD

**Issue by Capybara-sea** [yoimiya-kokomi/miao-plugin#224]
![image](https://user-images.githubusercontent.com/67335679/196924610-009c2ba2-399c-45a5-83a8-92b47f9e25cb.png)

部分武器没有及时跟进简称，文本超长导致换行，建议增加`white-space: nowrap; overflow: hidden;`。
并且武器图标没有垂直居中，图标顶头了。

**Comment by yoimiya-kokomi** [comment]
理论上是已经加的别名，估计你不是最新版，更新下试试？

**Comment by Capybara-sea** [comment]
更新了，好了。可以加一下防止未及时更新时的排版问题。
