### ISSUE TITLE
图片加载不出来

### ISSUE THREAD

**Issue by Shuangze687101** [yoimiya-kokomi/miao-plugin#225]
![图片](https://user-images.githubusercontent.com/115065376/197176252-159fef6d-cce6-40d9-af4b-61499fa7a2e5.png)

**Comment by Shuangze687101** [comment]
![图片](https://user-images.githubusercontent.com/115065376/197178325-804b979b-bd5f-405b-b802-e4f96071ea07.png)

**Comment by yoimiya-kokomi** [comment]
升级下puppeteer及浏览器内核试试

**Comment by Shuangze687101** [comment]
我这边用的是centos7，安装的chromium浏览器，之前因为插件有中文路径问题改了plugin/example里的三个js文件的文件名
![图片](https://user-images.githubusercontent.com/115065376/197309614-10ce316a-5ef8-4cc3-b825-d3354edfc9a2.png)
运行云崽，插件都可以加载出来，

**Comment by Shuangze687101** [comment]
![图片](https://user-images.githubusercontent.com/115065376/197313536-4ca12425-b6b9-43e1-a426-5720622a04ac.png)
![图片](https://user-images.githubusercontent.com/115065376/197313656-081c508d-193d-4661-a593-9e3874aeb3ac.png)

**Comment by yoimiya-kokomi** [comment]
如果是因为中文路径的话短期内解决不了，这个改动面影响比较大，建议从部署环境侧解决
