### ISSUE TITLE
这个神奇的群友总是草神图鉴报错

### ISSUE THREAD

**Issue by NepPure** [yoimiya-kokomi/miao-plugin#232]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/12379907/199443739-eeb657b7-c324-45d5-9996-2e3288220f45.png">

其他人没问题，这个天选群友有什么特别的吗

**Comment by yoimiya-kokomi** [comment]
看起来是没获取到武器数据
更新喵喵到最新版，如果问题依旧问一下那位群友草神带的是哪个武器，我检查下

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/199481617-6131194e-9852-4de7-b6ac-458876cdf20d.png)

应该是面板抓到了错误 数据 更新下面板就好了
