### ISSUE TITLE
更新面板增加提示

### ISSUE THREAD

**Issue by GOOD-AN** [yoimiya-kokomi/miao-plugin#233]
在更新面板时，返回 开始获取数据，可能会需要一定时间~ 后，没有任何反应，也没有报错，不知道发生了什么，希望可以对这样的现象增加一定的反馈。

**Comment by yoimiya-kokomi** [comment]
mark下，后面添加

**Comment by GOOD-AN** [comment]
十分抱歉，对js这一块不是很熟悉，目前看下来，我想可以在`apps/character/ProfileCommon.js L185`或者`components/Profile.js L24`下添加`e.reply`，但是mark没看明白，还望大佬详说。

**Comment by GOOD-AN** [comment]
嗯。。。大概按自己想法写了一点输出，后面看看具体是哪里的问题。
