### ISSUE TITLE
部分武器图标加载异常

### ISSUE THREAD

**Issue by Inky-Moon** [yoimiya-kokomi/miao-plugin#234]
求助，我的一个群员查询纳西妲面板的时候发现武器的图标和文字显示不正常（这里纳西妲装备的是专武），但是用 #武器 指令查询的时候却能够正常显示。起初我以为是我的插件没更新，就手动用git pull命令更新到2.0.6，但是更新完了以后问题依旧，问题出在哪里，怎么解决？
![QQ截图20221104201226](https://user-images.githubusercontent.com/84265441/199970313-6c829ecb-97c8-46e8-b3f5-eeafced0e8f1.png)

**Comment by yoimiya-kokomi** [comment]
确认是最新版，然后重新获取面板

**Comment by q838090386** [comment]
> 

我的也这样 刚更新完 包括喵喵更新图像 都是最新的了  但是纳西妲的专武就是不显示

**Comment by yoimiya-kokomi** [comment]
重新#更新面板 后也不可以？

**Comment by q838090386** [comment]
> 重新#更新面板 后也不可以？

可以了 打扰了emm
