### ISSUE TITLE
莫娜普攻等级识别错误

### ISSUE THREAD

**Issue by 1055169799** [yoimiya-kokomi/miao-plugin#240]
技能等级是7-7-7，识别成1-7-7，大概是把多的那个被动技能给错误算进去了

![IMG_20221106_095312.png](https://user-images.githubusercontent.com/41286675/200150423-ee61b16a-6633-4d0d-8477-46fac75f5c2b.png)
![59f57d8ae6345738.jpg](https://user-images.githubusercontent.com/41286675/200150369-e736464f-7514-4e95-b1f1-3e826e78412c.jpg)![-64694780eb4b5d17.jpg](https://user-images.githubusercontent.com/41286675/200150373-12c52156-ba94-418d-82e4-52ace55dac39.jpg)

**Comment by yoimiya-kokomi** [comment]
嗯，莫娜神里两个需要有特殊处理(,,•́.•̀,,)
下个版本fix

**Comment by yoimiya-kokomi** [comment]
已fix，更新至最新版后，重新获取面板信息即可
