### ISSUE TITLE
喵喵设置查他人选项消失

### ISSUE THREAD

**Issue by earthjasonlin** [yoimiya-kokomi/miao-plugin#242]
![e6ed613455eaab5eba8547ab99a2e041](https://user-images.githubusercontent.com/83632110/200150878-43c13f9a-e090-4f18-8e9a-aac4fc1f88f7.jpg)
![3a8eaa72d4ee91a4b5dcb57a3b7337bf](https://user-images.githubusercontent.com/83632110/200150889-68ab08f0-2068-4e36-a670-c9c94b08add3.jpg)
图一为现在的，图二危以前的

**Comment by yoimiya-kokomi** [comment]
临时关闭这个设置了，目前的逻辑里面无法做到完全隔离
