### ISSUE TITLE
尝试多个服务器

### ISSUE THREAD

**Issue by GOOD-AN** [yoimiya-kokomi/miao-plugin#249]
打扰了，现在看到查询服务器配置内只能设置单个服务器，可不可以设置多个服务器，然后在请求失败时，按设置顺序依次请求下面的服务器，直到成功或者全部请求失败。

**Comment by Lactococcuslactis** [comment]
因为就一个服务器啊，其他的只是做的代理，归根到底还是看enka

**Comment by GOOD-AN** [comment]
这个想法的初衷是如果有其他自建或者他人提供的服务也可以加入到里面，增加这个功能的稳定性。

**Comment by yoimiya-kokomi** [comment]
目前能够提供对接的服务只有两个（enka的多个url为代理）
对于enka如果之前能访问的服务如果失败大概率是服务本身的问题，即使通过其他代理url访问也会失败。
轮训请求必要性不高，暂不会增加

不过后续确实会上线手工切换服务的配置的命令，便于不改文件切换enka服务地址

**Comment by GOOD-AN** [comment]
好的
