### ISSUE TITLE
bot突然掉登录 然后重新登时提示qq版本过低

### ISSUE THREAD

**Issue by AshJordanZhao** [yoimiya-kokomi/miao-plugin#254]
请问如何升级qq版本？
![E14}_@BZA {V V}LVS5YDN1](https://user-images.githubusercontent.com/67005331/200983268-e5bf0cfb-bf1c-4924-81c2-04ca7a7e17e3.png)

**Comment by czh249899518** [comment]
在yunzai-bot有解决方案，最好的办法扫码登陆

**Comment by AshJordanZhao** [comment]
> 在yunzai-bot有解决方案，最好的办法扫码登陆

找着了 感谢回答
