### ISSUE TITLE
上传角色图像权限获取不到

### ISSUE THREAD

**Issue by 1294266616** [yoimiya-kokomi/miao-plugin#255]
我管理员上传不了图像
![image](https://user-images.githubusercontent.com/52421598/201010922-7216bc4c-4ef6-43f4-8a19-27975dd51993.png)
之后我修改了下代码
![image](https://user-images.githubusercontent.com/52421598/201010983-f7d36c7b-157f-42c8-8b03-52bf9c1433e7.png)
就可以了应该是没获取到配置
![image](https://user-images.githubusercontent.com/52421598/201011074-be7dfed0-1dd5-489c-9f40-afc0057ecb9e.png)

**Comment by yoimiya-kokomi** [comment]
遗留的v2 v3兼容问题没适配，后面fix一下

**Comment by 1294266616** [comment]
> 遗留的v2 v3兼容问题没适配，后面fix一下

好的

**Comment by ziyuCat** [comment]
@1294266616   大佬，这个怎么没获取到配置
