### ISSUE TITLE
是否有办法一键更新全部面板？

### ISSUE THREAD

**Issue by unknown10777** [yoimiya-kokomi/miao-plugin#256]

**Comment by likodesu** [comment]
你意思是一个号的所有角色？？那个你得叫米哈游把8个格子上限改到54

**Comment by yoimiya-kokomi** [comment]
哈哈，楼上说的正确
更新面板的原理就是读好友窗口数据，目前mhy只允许摆8个，所以也只能更新8个的数据

**Comment by unknown10777** [comment]
> 你意思是一个号的所有角色？？那个你得叫米哈游把8个格子上限改到54

抱歉，我指的是所有本地uid，并非单个uid所有角色

**Comment by SmallK111407** [comment]
你这样请求量会很大，服务器承担不住

**Comment by yoimiya-kokomi** [comment]
嗯，原则上面板需要手工摆出来需要更新的角色，然后主动触发更新。全部更新的话大部分都是无意义的更新，造成不必要的服务压力

**Comment by Alex6357** [comment]
原神似乎支持更新有token的uid下的全部角色？星铁不支持？
