### ISSUE TITLE
请问安装完以后报错是怎么回事

### ISSUE THREAD

**Issue by minihua** [yoimiya-kokomi/miao-plugin#26]
![QQ截图20220606205518](https://user-images.githubusercontent.com/57204430/172164727-3545c43a-082e-49a0-a256-6d77279b5ff1.png)

**Comment by minihua** [comment]
已经解决了

**Comment by Peagger** [comment]
这是来自QQ邮箱的假期自动回复邮件。

**Comment by L-yt** [comment]
> 已经解决了

怎么解决的老哥
