### ISSUE TITLE
建议：希望群排名功能可以分开按群单独设置

### ISSUE THREAD

**Issue by Muamu925** [yoimiya-kokomi/miao-plugin#261]
#建议：
##希望群排名功能可以分开按群单独设置，每个群群友对pvp看法不同，不能因一个群而全部关闭群排名功能<pr>或者将群排名列为喵喵单独分区，通过单独群配置进行禁用

**Comment by yoimiya-kokomi** [comment]
嗯，后面会加分群的独立开关

**Comment by lxs880628** [comment]
群面板排名功能已禁用...
——这个功能怎么打开哇，没查到命令

**Comment by Peagger** [comment]
> 群面板排名功能已禁用... ——这个功能怎么打开哇，没查到命令

#喵喵设置里面

**Comment by wudifeixue** [comment]
喵喵设置这个pvp榜貌似默认只允许主人设置。。没办法管理员来管理自己的群么🤔
Bot提供人并不在群里，希望可以群管理管理自己的群，谢谢

**Comment by Muamu925** [comment]
> 嗯，后面会加分群的独立开关

请问koukoumi大大功能实现了吗

**Comment by yoimiya-kokomi** [comment]
此功能已经支持
可在对应群内执行 `#禁用排名` 或 `#启用排名` 来单独关闭或打开排名功能
群管理员暂不支持设置，后续版本会增加支持
