### ISSUE TITLE
关于甘雨面板的伤害计算

### ISSUE THREAD

**Issue by lin-junliang** [yoimiya-kokomi/miao-plugin#264]
冰套甘雨打融化会触发冰套增加的20%暴击率，实际怪物头上是火属性，无法触发冰套的任何加成

**Comment by yoimiya-kokomi** [comment]
确实，不过短期内好像调整不了
在当前的伤害计算逻辑里，冰套的加成早于融化的伤害计算，目前好像排除不了 0.0
