### ISSUE TITLE
排行榜作弊与圣遗物列表

### ISSUE THREAD

**Issue by crecheng** [yoimiya-kokomi/miao-plugin#265]
通过一套圣遗物多人重复穿戴来刷新面板，达到多个角色使用同一套圣遗物来霸占排行榜，同时导致圣遗物列表重复显示同一个圣遗物

**Comment by yoimiya-kokomi** [comment]
因为一次最多获取8个角色数据，从原理上无法规避卡bug刷榜
可以通过一定的数据分析做一定的检测或去重，不过分析量不小，担心影响性能。
因为都是群内排名，遇到这种问题目前最简单的方式是群内谴责
₍˄·͈༝·͈˄*₎◞ ̑̑
