### ISSUE TITLE
妮露的面板是否应该计算丰穰之核伤害

### ISSUE THREAD

**Issue by Brillight** [yoimiya-kokomi/miao-plugin#266]
除非是高命妮露或者娱乐玩法可以选择打蒸发，否则妮露正常配队都是打妮绽放吧，在队伍中妮露主要的伤害贡献来自于其对丰穰之核的伤害加成，所以妮露的面板伤害计算是否应该计算其触发的丰穰之核伤害。

**Comment by yoimiya-kokomi** [comment]
是，妮露的伤害计算及圣遗物评分规则会在后面进行更新
