### ISSUE TITLE
刻晴词条评分相关

### ISSUE THREAD

**Issue by NRZ091** [yoimiya-kokomi/miao-plugin#268]
现在激化体系精通是不是也应该算阿晴的有效词条●▽●

**Comment by Putarku** [comment]
我也这么觉得，权重可以给到60-70的样子

**Comment by yoimiya-kokomi** [comment]
精通大于80的刻晴会走精通流判定

**Comment by NRZ091** [comment]
了解了





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月27日(周日) 上午6:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoimiya-kokomi/miao-plugin] 刻晴词条评分相关 (Issue #268)




 
精通大于80的刻晴会走精通流判定

**Comment by NichtsHsu** [comment]
研究了半天，才发现原来是我79精通刻晴所以不算数。。。要是能手动切就好了。

**Comment by TZ0918** [comment]
我尝试把精通》=80切换精通规则，改成了》=0，让精通直接成为有效词条，但是其他所有评分都下降了，是什么原理？总分对齐的缘故么？

**Comment by NRZ091** [comment]
> 我尝试把精通》=80切换精通规则，改成了》=0，让精通直接成为有效词条，但是其他所有评分都下降了，是什么原理？总分对齐的缘故么？

是因为对齐，总分是不变的，多了精通作为有效其他的原本词条分就会低一点了
