### ISSUE TITLE
请问喵喵插件可以放在安卓端上面吗？

### ISSUE THREAD

**Issue by ConghaiLY** [yoimiya-kokomi/miao-plugin#27]
我根据教程在安卓上的Termux部署了yunzai的bot，我想把喵喵插件也放进去，可以把插件解压之后放进安卓插件文件夹里吗？感谢！

**Comment by yoimiya-kokomi** [comment]
可以，放到plugins目录后重启yunzai即可。如遇moment报错就安装一下moment
不过建议git安装以便于后续升级。
