### ISSUE TITLE
关于查询别人面板的一些问题

### ISSUE THREAD

**Issue by xiaoACE6716** [yoimiya-kokomi/miao-plugin#271]
在之前没更新的时候，可以通过#绑定123456789的命令去切换绑定的uid，然后去查询别人的面板。
但是更新后，使用#绑定123456789的命令，机器人会回复绑定成功123456789，但是更新面板的时候，查询的还是我自己的号。
我绑定的ck是我自己号的。我每次更新机器人的时候会把机器人及插件都进行一次更新，所以我自己无法确定是机器人问题还是插件问题。
我希望有人可以帮我解决这个问题或是告诉我为什么更新后就无法查别人的面板了
/Le-niao/Yunzai-Bot#884

**Comment by xiaoACE6716** [comment]
![如图](https://user-images.githubusercontent.com/94223505/202323576-a0046bcd-1507-48a4-86f1-5b8fe94ef3cd.png)
情况如图所示

**Comment by yoimiya-kokomi** [comment]
有ck时优先用ck的uid，这是yunzai的底层逻辑
如需查看别人面板直接 #面板123456789 即可

**Comment by xiaoACE6716** [comment]
> 有ck时优先用ck的uid，这是yunzai的底层逻辑 如需查看别人面板直接 #面板123456789 即可

原来如此，我知道了，谢谢你

**Comment by Lzx935740** [comment]
那如果还要查看别人面板的某个角色详情呢

**Comment by Lzx935740** [comment]
> 

试出来了#角色面板uid
