### ISSUE TITLE
排行榜头像显示错误

### ISSUE THREAD

**Issue by WuSheng125** [yoimiya-kokomi/miao-plugin#274]
插件由旧版本更新之后，a使用“#面板@b”指令后排行榜显示对应角色头像为发送该条指令的a的头像，而非正确的b的头像，会导致排行榜有两个相同的a的头像（a之前也使用了“#更新面板”指令）

**Comment by yoimiya-kokomi** [comment]
对at的记录进行了调整，已有数据的可以#刷新排名 整体更新下数据
不过对于未绑定ck的用户会记录最后一个查询的qq，可能不足够稳定
