### ISSUE TITLE
好像喵喵插件不会艾特人了

### ISSUE THREAD

**Issue by Fury94-Echo** [yoimiya-kokomi/miao-plugin#275]
![1](https://user-images.githubusercontent.com/8230419/202552388-ee9a2c5a-27fc-41c9-a9cc-e81efeadc26e.png)
![2](https://user-images.githubusercontent.com/8230419/202552849-47cd916b-4f99-4e75-8ac2-0c1effa33dc7.png)

搜下issue好像只有我有这个问题(

**Comment by yoimiya-kokomi** [comment]
这几个命令都不是miao-plugin的命令
不过miao-plugin的命令回复确实大部分都没有增加at人的选项

**Comment by Fury94-Echo** [comment]
> 这几个命令都不是miao-plugin的命令 不过miao-plugin的命令回复确实大部分都没有增加at人的选项

欸..我还以为统计的功能是喵的(
了解了！
