### ISSUE TITLE
请问Token什么时候可以开放申请

### ISSUE THREAD

**Issue by BeHappy-NoTZG** [yoimiya-kokomi/miao-plugin#28]
有偿的也行啊

**Comment by Fengjio** [comment]
同求token，愿有偿，赞美之心
q1401116280，两个群号都搜索不到了

**Comment by A7424** [comment]
> 同求token，愿有偿，赞美之心 q1401116280，两个群号都搜索不到了

现在不需要token，别被骗了

**Comment by yoimiya-kokomi** [comment]
最新版喵喵不需要token了，更新最新版即可
