### ISSUE TITLE
执行#更新面板 时，CD时间异常（请求过快，请4293669739秒后重试..）

### ISSUE THREAD

**Issue by AkiraShe** [yoimiya-kokomi/miao-plugin#281]
yunzai-bot 3.0.0 Miao-Plugin 2.0.10

目前只有一个群友遇到，#更新面板时，提示的CD为异常的4293669739秒。请问要如何修复此用户数据？谢谢。

log:
[YzBot][23:18:40.734][MARK] [喵喵:角色面板][profileDetail][123(Akira)] #更新面板            
[YzBot][23:18:40.737][MARK] [喵喵:角色面板][profileRefresh][123(Akira)] #更新面板           
[YzBot][23:18:40.761][MARK] [喵喵:角色面板][profileRefresh] #更新面板 处理完成 23ms                 
[YzBot][23:18:41.135][INFO] succeed to send: [Group(123)] 请求过快，请4293669739秒后重试..

**Comment by AkiraShe** [comment]
删掉.rdb里的异常CD后解决了。但这个bug是怎么引起的呢...

**Comment by yoimiya-kokomi** [comment]
mark下，查询后修复或适配

**Comment by yoimiya-kokomi** [comment]
此问题已经解决，更新至最新版可规避此问题
