### ISSUE TITLE
关于群排名模块，显示错误

### ISSUE THREAD

**Issue by DeSireFire** [yoimiya-kokomi/miao-plugin#282]
![MDDLZDB)6YP7EV{Z8UNX2S](https://user-images.githubusercontent.com/18726905/202752656-d586b0e0-2ca0-474d-b76e-a01c4ec13337.gif)
![BNVB$ 5$F_AQFSEJX7)NNMU](https://user-images.githubusercontent.com/18726905/202752690-53f399dc-d45e-469d-8361-e738197a303e.gif)

为啥第一个排名的甘雨圣遗物没有分数呢..
如何fix

**Comment by yoimiya-kokomi** [comment]
因为设置了排名参与条件（限制CK），该用户无法再参与排行
请使用`#重置排行`命令重置已有排行数据
重置后也可使用`#刷新排行`刷入能够参与排行的用户数据
