### ISSUE TITLE
删除uid后排行榜里存在一个幽灵

### ISSUE THREAD

**Issue by ABT98421** [yoimiya-kokomi/miao-plugin#284]
群友绑了一个他人的uid霸榜，在data/userdata里删除掉该uid之后，使用#雷神排行该uid确实消失了；使用#最强排行，雷神等原来霸榜的角色消失了；使用#最强雷神会提示“请确认雷电将军已展示在【游戏内】的角色展柜中......”；#面板里所有人的雷神排行会下降一位

**Comment by ru8lq0005** [comment]
我也遇到了类似的情况 不过我是删除了redis的uid绑定 然后重置了排行

**Comment by yoimiya-kokomi** [comment]
如果手动删除过uid数据，请使用`#重置排行`命令重置排行榜，并使用`#刷新排行`重新载入本群数据
后续会增加删除面板的命令，会在命令内部清除排行信息
