### ISSUE TITLE
角色面板自定义立绘的开启条件是什么？有没有办法手动开启？

### ISSUE THREAD

**Issue by MSSX-Ifvo** [yoimiya-kokomi/miao-plugin#289]
有时候面板的立绘会变成其他画师的图片，而非官方立绘
![image](https://user-images.githubusercontent.com/83542073/202898048-6e8250e0-d078-4e85-b11c-53f7f61b2b5c.png)

**Comment by Algar233** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/commit/6720eba0ba95693cb4bfb416c62997b984a0807c

**Comment by MSSX-Ifvo** [comment]
ok，了解了
