### ISSUE TITLE
新角色莱依拉侧面头像未正确加载

### ISSUE THREAD

**Issue by CUZNIL** [yoimiya-kokomi/miao-plugin#290]
`#练度统计`使用到的侧面头像裂开了
![image](https://user-images.githubusercontent.com/76582404/202898625-e72808c0-fdcb-4aa8-a8eb-534a5e751ed0.png)
如图，未正常显示
已经是最新版本
![image](https://user-images.githubusercontent.com/76582404/202898585-c33387e5-e593-4fb7-b4f2-56ec8125a617.png)
下图来自[enka.network](https://enka.network/ui/UI_AvatarIcon_Side_Layla.png)
![image](https://enka.network/ui/UI_AvatarIcon_Side_Layla.png
)

**Comment by yoimiya-kokomi** [comment]
这里不是miao-plugin的功能，是更早期合并到Yunzai主体的功能
更新下yunzai
