### ISSUE TITLE
喵佬喵佬，群友自己上传了面板排名的头像，把最强万叶排名里面挤进了一个向日葵

### ISSUE THREAD

**Issue by MSSX-Ifvo** [yoimiya-kokomi/miao-plugin#294]
如题，我翻了一遍目录，可是没找到相关配置文件啊
![image](https://user-images.githubusercontent.com/83542073/202952285-32f02c2d-4ae6-4461-b313-16e8915612d1.png)

有没有修改的方法，或者禁用也可以

**Comment by yoimiya-kokomi** [comment]
这个是qq头像，默认以qq头像展示
如其他qq头像未正常展示可通过 `#刷新面板` 刷新数据

后续会增加展示配置选项，是展示角色头像还是qq头像

**Comment by MSSX-Ifvo** [comment]
okok
