### ISSUE TITLE
新增的排名功能如何单独对一个群关闭

### ISSUE THREAD

**Issue by Kuriyama-Natsuki** [yoimiya-kokomi/miao-plugin#295]
最近更新的排名功能有些群要用有些群不想要，但是我并没有找到单独开关的方法，求大佬们告知，如果不能单独开关的话希望以后能更新

**Comment by Muamu925** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/261#issuecomment-1317939667

**Comment by yoimiya-kokomi** [comment]
已经支持，通过在群内发送 #禁用排名 可关闭特定群排名功能
