### ISSUE TITLE
这个喵喵面板的彩蛋在哪里，流程是怎样的？

### ISSUE THREAD

**Issue by sgqy** [yoimiya-kokomi/miao-plugin#298]
全文搜索整部 Yunzai 包括 node_modules 都没有找到。其文字为：
```
※Yunzai-Bot免费开源项目：gitee.com/Le-niao/Yunzai-Bot
```
信息截图为：
![img](https://user-images.githubusercontent.com/4893302/203340463-15a3c05c-987a-4a78-be39-0a5dbb36336a.png)

**Comment by Lactococcuslactis** [comment]
去掉然后方面倒卖？

**Comment by sgqy** [comment]
@Lactococcuslactis 

计划用 geoip 给插件加点功能，突然看到了这彩蛋，就想顺便也给它**添加**一点花活而已。

> 去掉然后方面倒卖？

不过为了配上您这顶帽子，我得先做实一下。

![image](https://user-images.githubusercontent.com/4893302/203669425-9a961ceb-1f00-441b-bdad-bcc9141febca.png)

**Comment by sgqy** [comment]
@Lactococcuslactis 

计划用 geoip 给插件加点功能，突然看到了这彩蛋，就想顺便也给它**添加**一点花活而已。

> 去掉然后方面倒卖？

您这顶帽子太大，我不配。所以我急了，叠个甲先。

![image](https://user-images.githubusercontent.com/4893302/203669425-9a961ceb-1f00-441b-bdad-bcc9141febca.png)

幸亏爱发电支持 paypal ，坐实得比较顺利，不然国际汇款还要等三天🐶。

但还是要感谢您提醒如此恶劣的环境，不如找机会私聊作者，先溜为敬🐶。

**Comment by sgqy** [comment]
@Lactococcuslactis 

计划用 geoip 给插件加点功能，突然看到了这彩蛋，就想顺便也给它**添加**一点花活而已。

> 去掉然后方面倒卖？

您这顶帽子太大，我不配。所以我急了，叠个甲先。

![image](https://user-images.githubusercontent.com/4893302/203669425-9a961ceb-1f00-441b-bdad-bcc9141febca.png)

幸亏爱发电支持 paypal ，叠得比较顺利，不然国际汇款还要等三天🐶。

但还是要感谢您提醒我环境如是恶劣。我不如找机会私聊作者，先溜为敬🐶。

**Comment by Lactococcuslactis** [comment]
环境确实挺恶劣的，闲鱼倒卖一大堆，你问这个我当然要怀疑一下你的动机，要是错怪你了我向你道歉，这个彩蛋具体在哪估计只有作者知道吧，不过你要加可以去(https://github.com/Le-niao/Yunzai-Bot/blob/8421c581fc995f95e861298e850943a7760ada30/lib/plugins/loader.js#L451) 改这个函数，据我所知，大部分插件的回复都是走的这个函数，喵喵插件也是一样的

**Comment by sgqy** [comment]
@Lactococcuslactis 


彩蛋属于 unexpected behaviour 着实吓到我了，经过简单调查也没能发现其原理，故而比较焦躁，以至于很多事情考虑欠妥。
~~虽然你所指出的地方我也没能找到线索。~~

我为之前的粗陋向你表示歉意🍎。

**Comment by Lactococcuslactis** [comment]
没事，这个彩蛋就是为了防止倒卖的，要是这么容易被找出来，那还防个啥，~~虽然骗子根本不在意~~

**Comment by yoimiya-kokomi** [comment]
喵喵的面板彩蛋指的不是这个，是面板查询四神（满命/ACE/三皇冠）会触发另外的立绘。
截图所示的是yunzai的底层增加的逻辑，所有由bot发出的图像有概率（好像是0.01？）附带链接
