### ISSUE TITLE
请问这些报错有解决方法吗

### ISSUE THREAD

**Issue by yescaptain666** [yoimiya-kokomi/miao-plugin#30]
![1N1AL~N01H 0SCV4UB{$(S9](https://user-images.githubusercontent.com/57821724/173176059-cc9792a6-4e7d-43be-bf6d-3149130424de.png)
![2M@M S@ %G~{H{XEZ1{@CS](https://user-images.githubusercontent.com/57821724/173176060-c70d924c-50f7-417c-8f42-39a2e72382f3.png)

**Comment by NomadThanatos** [comment]
Duplicate as https://github.com/Le-niao/Yunzai-Bot/issues/148

**Comment by yoimiya-kokomi** [comment]
由于Yunzai暂时无法合入代码，可尝试切到这里更新下试试
https://github.com/yoimiya-kokomi/Yunzai-Bot

若Yunzai恢复，变更会合入Yunzai
