### ISSUE TITLE
伤害显示希望换成四位一逗号

### ISSUE THREAD

**Issue by Lactococcuslactis** [yoimiya-kokomi/miao-plugin#300]
中文语境下我们习惯说2万伤害，而不是20千，逗号断数字的方式是本意是方便阅读数字，国外三位一断是因为正好可以与thousand，million对应，中文语境下如果要起到方便阅读的效果最好是四个一断

**Comment by sgqy** [comment]
现已合并了对应功能，即 `#喵喵设置逗号 4`，更新即可。

**Comment by yoimiya-kokomi** [comment]
多谢~
