### ISSUE TITLE
赛诺天赋5计算错误

### ISSUE THREAD

**Issue by neko-fu** [yoimiya-kokomi/miao-plugin#301]
感谢大佬修复更新了赛诺的伤害计算，但是天赋5有一些计算错误：

面板：精通353 _（如下图红线）_
天赋5计算应该是：
普通攻击伤害值提高（353+饰金150+赛诺开大100）×150%=904.5【机器人算的是679.1】
渡荒之雷伤害值提高（353+饰金150+赛诺开大100）×250%=1507.5【机器人算的是181.1】 _（如下图红线）_
还有一些建议：
（1）因为如雷套也可以押上一些qte，所以个人感觉“q状态e伤害” _（下图伤害计算2）_ 和“q+末途真眼e伤害” _（下图伤害计算3）_ 取其后者计算就好。
（2）因为每次q后e即使计算如雷都是2-3s一次的释放，激化率最低50%，所以“q+末途真眼伤害”_（下图伤害计算3）_ 和“q后强化e.超激化” _（下图伤害计算4）_ 取后者即可。
（3）能否把元素爆发后的“q后强化e.超激化”具体计算为：“一次强化e的激化伤害+渡荒之雷的激化伤害+渡荒之雷伤害+渡荒之雷伤害”的伤害期望。
**综上，建议伤害计算板块改为：1计算q后第一段普攻伤害，2计算q后第一段普攻激化，3计算qte超激化即可。这样四个板块的计算可以压到3个而且更有用直观**
<img width="839" alt="屏幕截图 2022-11-24 155910" src="https://user-images.githubusercontent.com/118741239/203726330-897d4b11-e59d-4527-ae6d-602037a29588.png">
大佬辛苦了，非常感谢！！！
![QQ图片20221124150800](https://user-images.githubusercontent.com/118741239/203716927-f728724b-e278-40b3-8a26-f384a9de69f8.jpg)
![QQ图片20221124150804](https://user-images.githubusercontent.com/118741239/203716956-831fe7a8-706c-4304-b724-2d855162f1c5.jpg)

**Comment by yoimiya-kokomi** [comment]
现在的激化伤害计算的不够准确，这块等底层调整完结束之后统一进行处理
赛诺会增加 Q一轮输出的激化 总伤害

**Comment by neko-fu** [comment]
> 现在的激化伤害计算的不够准确，这块等底层调整完结束之后统一进行处理 赛诺会增加 Q一轮输出的激化 总伤害

了解了！谢谢大佬。

**Comment by neko-fu** [comment]
> 现在的激化伤害计算的不够准确，这块等底层调整完结束之后统一进行处理 赛诺会增加 Q一轮输出的激化 总伤害

大佬，我回去又验算了一下，发现它伤害计算的3和4偏低了；实际上是天赋4没有参与计算。

验算过程：
精通叠满应该是：353+150+100=603
赤沙提升的转化没有问题了，算出来是：603×（52%+28%×3）=314+506=820
总攻击力就是：1332+313.4+506.3=2153
激化的基础伤害提升也没有问题了，是：1447×1.15×[1+5×603/1200+603]=4446
（1）普攻如果按机器人算的错误天赋5算，（2153×倍率1.55+错误天赋5679.1）×爆伤区间3.2×（1+雷伤46.6%+二命50%）×0.5×0.9=11370**（所以普攻计算没有问题）**
（2）强化e伤害应该是：（2153×倍率2.82）×3.2×（1+46.6%+50%+35%)×0.5×0.9=20248（如果去掉天赋4的35%，就是17188和机器人算的差不多了）
（3）强化e激化伤害应该是：（2153×倍率2.82+4446）×3.2×（1+46.6%+50%+35%)×0.5×0.9=35076（如果去掉天赋4的35%，就是29775和机器人算的差不多了）

现在的问题就是：
①天赋4未参与计算
②天赋5计算错误

我算的应该是没有问题，大佬不是有个qq群吗？可以验算一下，我怕我有失误；我也不太了解程序什么的，只能检查一下计算方面哪里错了。再次感谢大佬们的机器人hhh。
