### ISSUE TITLE
查询他人面板无响应

### ISSUE THREAD

**Issue by Ruby280255768** [yoimiya-kokomi/miao-plugin#304]
使用#角色面板可以正常查询自己角色面板，使用#角色面板+uid无法查询其他人角色面板，但是使用#面板+uid可以查看别人角色面板列表
![image](https://user-images.githubusercontent.com/18400004/203886040-6c7a2606-5d2b-4d7f-8cfc-95ef6117139b.png)

![image](https://user-images.githubusercontent.com/18400004/203885992-11c7a14b-f279-4939-8986-740c8413e321.png)

**Comment by yoimiya-kokomi** [comment]
先把中间的空格去了查询
我后面加一下兼容

**Comment by yoimiya-kokomi** [comment]
最新版已经适配
