### ISSUE TITLE
更新到最新版本后出现bug

### ISSUE THREAD

**Issue by AshJordanZhao** [yoimiya-kokomi/miao-plugin#305]
刚刚顺手#喵喵更新 之后 面板查询就出现问题了
查体力啥的都还正常
![Screenshot_2022-11-25-17-33-09-152-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/203947675-65970668-5c94-4f87-8abf-ea3af75067e7.jpg)

**Comment by AshJordanZhao** [comment]
附一张更新时的返回
![Screenshot_2022-11-25-17-34-21-021-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/203947962-2d18ea45-d3d4-425c-a438-fafbcf2ae3a3.jpg)

**Comment by likodesu** [comment]
这次喵喵版本更新内容，估计你需要更新yunzai版本了

**Comment by AshJordanZhao** [comment]
![image](https://user-images.githubusercontent.com/67005331/204014187-74325ace-08a0-400c-8a75-75ab6d952411.png)
查看后台是这个提示 请问下怎么解决
git pull会提示已经更新到最新

**Comment by FenDC** [comment]
你需要更新Yunzai版本了，最新的喵喵需要e.runtime支持，你可以试试“#更新”命令来更新Yunzai

**Comment by AshJordanZhao** [comment]
> 你需要更新Yunzai版本了，最新的喵喵需要e.runtime支持，你可以试试“#更新”命令来更新Yunzai

更新过了 还是一样的

**Comment by Lactococcuslactis** [comment]
你看看#喵喵版本，需要2.23

**Comment by AshJordanZhao** [comment]
> 你看看#喵喵版本，需要2.23

#喵喵版本 返回的是2.23的更新内容
然后使用#喵喵更新 bot就会毫无反应

**Comment by zzgwd** [comment]
一样的问题 ,都更新到了最新，所有指令都报错这个错误
![QQ截图20221127011337](https://user-images.githubusercontent.com/12791750/204100873-8337dc05-2a9a-4d92-9396-0bcbdcc724c1.png)
![QQ截图20221127011357](https://user-images.githubusercontent.com/12791750/204100874-5a30d992-f248-42ac-b2d2-3f29b16b3b18.png)

**Comment by yoimiya-kokomi** [comment]
应该已经fix了，更新V2-Yunzai及miao-plugin均至最新版，重启

**Comment by zzgwd** [comment]
拉取插件后重启正常

**Comment by AshJordanZhao** [comment]
> 应该已经fix了，更新V2-Yunzai及miao-plugin均至最新版，重启

更新后问题解决 感谢

**Comment by AshJordanZhao** [comment]
> 应该已经fix了，更新V2-Yunzai及miao-plugin均至最新版，重启

似乎绑定了ck的人可以正常查询 但是直接查还是会有这个问题![Screenshot_2022-11-27-23-54-01-732-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/204144564-f2534e5d-aae0-41ef-860c-8181dfbf7bc5.jpg)

**Comment by AshJordanZhao** [comment]
> > 应该已经fix了，更新V2-Yunzai及miao-plugin均至最新版，重启
> 
> 似乎绑定了ck的人可以正常查询 但是直接查还是会有这个问题![Screenshot_2022-11-27-23-54-01-732-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/204144564-f2534e5d-aae0-41ef-860c-8181dfbf7bc5.jpg)

补充，后台bot是完全没有任何报错提醒
bot也显示已经绑定uid
使用#更新面板 能正常更新绑定的uid面板，但是查具体面板会显示未绑定uid
![Screenshot_2022-11-28-10-25-01-455-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/204178286-f2a26bd3-195a-49af-bb0f-2e42eef9b808.jpg)
