### ISSUE TITLE
关于面板更换功能的小建议

### ISSUE THREAD

**Issue by xh2002** [yoimiya-kokomi/miao-plugin#309]
读取武器精炼那个部分，对于五星武器如果读不到精几默认精1应该比较合理
ProfileChange.js L82那段
（看着我摆烂圣遗物却能一戳7w的胡桃吓了一跳，直到我看到精5护摩（））
以及，希望下次更新，武器名称可以用简称啦~

作者加油！已经star啦

**Comment by yoimiya-kokomi** [comment]
嗯，精炼与用的是当前精炼等级，后面改成升星默认精一

武器别名已经支持了

**Comment by xh2002** [comment]
诶嘿 谢谢啦

**Comment by yoimiya-kokomi** [comment]
升星默认精一的逻辑已经补充
