### ISSUE TITLE
关于角色详情里面的满命纳西妲

### ISSUE THREAD

**Issue by K0t0dama** [yoimiya-kokomi/miao-plugin#311]
能否更换一张图片或者能够自定义显示默认图片呢？现在的这张不仅画工不是很好，还完全和剧情不符合...，跟别人的默认图片比起来像个🤡...

**Comment by yoimiya-kokomi** [comment]
能自定义，见 #喵喵帮助
我也觉得不够理想，目前没找到比较合适的替换图，蹲立绘中
