### ISSUE TITLE
node app启动的Yunzai-Bot执行喵喵更新后无法自动重启

### ISSUE THREAD

**Issue by SirlyDreamer** [yoimiya-kokomi/miao-plugin#32]
![问题描述](https://s2.loli.net/2022/06/12/hBl17RwHvzs3ZgW.jpg)

**Comment by Fujimiya-Asuka** [comment]
要用npm start命令启动

**Comment by yoimiya-kokomi** [comment]
先用npm run start启动即可。后面会适配下node app的启动模式
