### ISSUE TITLE
替换命令计算与显示异常

### ISSUE THREAD

**Issue by GOOD-AN** [yoimiya-kokomi/miao-plugin#321]
在同一UID下，未进行`#更新面板`指令，但替换为`若水`与`2命`时生命值显示错误。
![image](https://user-images.githubusercontent.com/53306377/204251999-ef2f5837-21b4-4c7d-9d4f-59321ccd410d.png)
*先查询的换若水，然后查询的正常面板，最后查询的换2命

**Comment by yoimiya-kokomi** [comment]
可能是原本面板数据中的生命值错误，获取面板时夜兰出场了，附带有双水buff或被动生命加成

以及换二命+若水的命令需要是换若水换2命，武器区和角色区的数据不能加号相连，否则可能无法识别

**Comment by GOOD-AN** [comment]
明白了，谢谢大佬
