### ISSUE TITLE
关于面板替换命令的四个小问题

### ISSUE THREAD

**Issue by Blaze-RI** [yoimiya-kokomi/miao-plugin#325]
# 目前发现了四个问题
---
## ①切换1星、2星武器可能出现等级超过实际上限的问题
![猎弓](https://user-images.githubusercontent.com/68352682/204304491-61e5f48e-514b-47e3-8a3d-abd412d4033b.jpg)
![历练的猎弓](https://user-images.githubusercontent.com/68352682/204304973-82e1802a-8b25-4f58-872e-9d67fcaf1981.jpg)
---
## ②切换部分无法精炼武器可能出现精炼超过上限的问题
![笼钓瓶一心](https://user-images.githubusercontent.com/68352682/204305488-be7f01a7-774f-49f2-85d2-1e80a1bcba71.jpg)
![降临之剑](https://user-images.githubusercontent.com/68352682/204305773-48b38644-de5a-44f8-afb5-f94bb79691b1.jpg)
![掠食者](https://user-images.githubusercontent.com/68352682/204305884-a635df31-eb05-4e12-a8ec-c2a2524b49d0.jpg)
---
## ③埃洛伊可切换命座
![@}A2Y6LBSU`@0LRD1 Q1JT3](https://user-images.githubusercontent.com/68352682/204306184-f506dc7b-cb62-4712-8b8b-22117338acdb.gif)
---
## ④等级限制后没有调整技能等级
![1级安柏](https://user-images.githubusercontent.com/68352682/204306470-57590780-54c5-4745-b45c-3f4479613826.jpg)

**Comment by yoimiya-kokomi** [comment]
武器相关问题已进行适配，角色天赋类的暂时没有调整
