### ISSUE TITLE
更新面板提示：请求失败:请求错误，请稍后重试

### ISSUE THREAD

**Issue by chen8665272** [yoimiya-kokomi/miao-plugin#33]
![QQ图片20220614114504](https://user-images.githubusercontent.com/60909156/173489357-22af75a1-cdb7-4f0c-aa99-4e093373e6bf.png)
![QQ图片20220614114535](https://user-images.githubusercontent.com/60909156/173489380-ee8a5936-029a-4491-a985-e06b5af1f70b.png)
这是怎么回事？请大大看一下，谢谢了

**Comment by Darkatse** [comment]
同样的情况

**Comment by 486494914** [comment]
不清楚，我服务器上配置没问题昨天是好的今天
也是这样，用别人的也是这样

**Comment by yoimiya-kokomi** [comment]
依赖的enka服务跪了，国服uid查询会失败，等服务解决

**Comment by 486494914** [comment]
好的，我估计也是

**Comment by MiniStar826** [comment]
等待解决

**Comment by chen8665272** [comment]
已经恢复了
