### ISSUE TITLE
绑定uid后查面板仍提示未绑定

### ISSUE THREAD

**Issue by AshJordanZhao** [yoimiya-kokomi/miao-plugin#330]
![Screenshot_2022-11-27-23-54-01-732-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/204588766-dae8b115-4873-40ac-a8e6-6cd0d2fe9c60.jpg)
![Screenshot_2022-11-30-00-40-52-484-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/67005331/204589373-90e89006-6789-4444-8037-66703be94829.jpg)
如图 yunzai与miao plugin均已是最新版
使用#更新面板 正常
但是查看面板会提示未绑定uid

似乎绑定ck能正常查询

**Comment by AshJordanZhao** [comment]
补充：yunzai版本2.2.3 喵喵版本2.1.3

**Comment by Peagger** [comment]
#340

**Comment by AshJordanZhao** [comment]
> #340 没有绑定CK的玩家无法查看面板

嗯 我也在等作者解决 目前暂时去用3.0版本yunzai了

**Comment by yoimiya-kokomi** [comment]
更新至miao-plugin最新版以及yunzai最新版，看是否还有问题
