### ISSUE TITLE
查看面板不识别武器

### ISSUE THREAD

**Issue by Auturns** [yoimiya-kokomi/miao-plugin#333]
0|Yunzai-Bot  | [YzBot][09:04:55.850][ERRO] TypeError: Cannot read properties of undefined (reading '护摩之杖')
0|Yunzai-Bot  |     at Function.Weapon.get (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Weapon.js:43:11)
0|Yunzai-Bot  |     at Proxy.get weapon (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Avatar.js:110:25)
0|Yunzai-Bot  |     at Reflect.get (<anonymous>)
0|Yunzai-Bot  |     at Object.get (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Base.js:21:26)
0|Yunzai-Bot  |     at baseGet (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:3077:24)
0|Yunzai-Bot  |     at Function.get (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:13195:49)
0|Yunzai-Bot  |     at Object.getVal (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/components/Data.js:156:19)
0|Yunzai-Bot  |     at file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/components/Data.js:150:26
0|Yunzai-Bot  |     at arrayEach (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:530:11)
0|Yunzai-Bot  |     at Function.forEach (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)

0|Yunzai-Bot  | [YzBot][09:02:30.448][ERRO] [喵喵:角色面板][profileDetail]
0|Yunzai-Bot  | [YzBot][09:02:30.450][ERRO] TypeError: Cannot read properties of undefined (reading '「渔获」')
0|Yunzai-Bot  |     at Function.Weapon.get (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Weapon.js:43:11)
0|Yunzai-Bot  |     at Proxy.get weapon (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Avatar.js:110:25)
0|Yunzai-Bot  |     at Reflect.get (<anonymous>)
0|Yunzai-Bot  |     at Object.get (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Base.js:21:26)
0|Yunzai-Bot  |     at baseGet (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:3077:24)
0|Yunzai-Bot  |     at Function.get (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:13195:49)
0|Yunzai-Bot  |     at Object.getVal (file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/components/Data.js:156:19)
0|Yunzai-Bot  |     at file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/components/Data.js:150:26
0|Yunzai-Bot  |     at arrayEach (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:530:11)
0|Yunzai-Bot  |     at Function.forEach (/NextCloud/Yunzai-Bot/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js:9410:14)

删除插件，并重新下载，上周才出现问题，并没有手动修改代码。

**Comment by yoimiya-kokomi** [comment]
咋感觉你的路径上错了，miao-plugin多了一个点
file:///NextCloud/Yunzai-Bot/plugins/.miao-plugin/models/Avatar.js
把这个目录的点删掉试试
