### ISSUE TITLE
能否放出自定义角色图的一些推荐参数

### ISSUE THREAD

**Issue by MSSX-Ifvo** [yoimiya-kokomi/miao-plugin#335]
如题，手里有很多各种比例的图片，但是始终都没能裁剪成想要的效果，能不能给出插件渲染时的一些具体参数，比如图像位置，缩放大小，以便自行调整？

**Comment by sec-8** [comment]
我自己用ps做了一个透明模板的psd。参数是 面板是1080*607,贴图放上去之后的展示区域是从383px（像素）开始，0px-383px（左右）展示不出来，383-1080为展示区域，可以铺满无缝隙。如下图。如果只想铺一半，可以扣个透明背景，尺寸为150px*238px这个参数。
![FQR~WS28W_NFVTO6HXNPYEJ](https://user-images.githubusercontent.com/27398776/205848741-080e2de1-2931-4f63-a04a-4604efaed571.png)

**Comment by sec-8** [comment]
我自己用ps做了一个透明模板的psd。参数是 面板是1080*607,贴图放上去之后的展示区域是从383px（像素）开始，0px-383px（左右）展示不出来，383-1080为展示区域，可以铺满无缝隙。如下图。如果只想铺一半，可以扣个透明背景，尺寸为150px*238px这个参数。
![FQR~WS28W_NFVTO6HXNPYEJ](https://user-images.githubusercontent.com/27398776/205848741-080e2de1-2931-4f63-a04a-4604efaed571.png)

**Comment by yoimiya-kokomi** [comment]
面板图本身是立绘，所以尽量是透明背景，人物保持在最中间即可

当然如果是纯色背景想铺满的话维持人物在最中间，够宽就可以

**Comment by Tsuk1ko** [comment]
可以按这个计算

https://github.com/yoimiya-kokomi/miao-plugin/blob/8881f5a8817843e8f30f4c472e31d65fbb68a444/resources/character/profile-detail.less#L3-L5

https://github.com/yoimiya-kokomi/miao-plugin/blob/8881f5a8817843e8f30f4c472e31d65fbb68a444/resources/character/profile-detail.less#L33-L42
