### ISSUE TITLE
关于用户的隐私数据删除困难

### ISSUE THREAD

**Issue by z3052624057** [yoimiya-kokomi/miao-plugin#337]
对于用户个人而言，用户的隐私数据才是他们最重视的；
而在云仔bot中，一旦用户绑定了自己的UID并且使用#更新面板 命令后，他们的原神角色部分相关数据会被存储到 .\data\UserData 中，而当他们想删除的时候，却无法使用#删除面板 等命令来删除他们的角色数据。
本人UID186167950，曾经多次因为角色面板展示而被拉去PVP。目前本人已经将游戏中的角色下架，并且将米游社数据全部隐藏，但是残留的部分面板信息仍然有时会被群友调出来PVP。对此我已经向多个bot的主人申请删除本人的json文件了，但是很多都以”过于麻烦“等理由拒绝删除。本人在想：既然Cookie命令可以通过指令删除，那么同样是为了隐私保护，面板的json文件（比如.\data\UserData\186167950.json）是否也可以通过指令删除呢？（本人只会Python，所以就先不提交Pr了，望开发者早日上线这个功能，谢谢）

**Comment by Peagger** [comment]
直接删除文件可能会有权限的问题，可以做一下覆盖

**Comment by z3052624057** [comment]
> 直接删除文件可能会有权限的问题，可以做一下覆盖。 建议看看更新面板是怎么更新json文件的，然后照着写一个把数据覆盖掉的指令。 ![图片](https://user-images.githubusercontent.com/103034147/205433810-a3c5dcf4-1857-4681-a572-607a874c91f1.png)

OK Thanks
