### ISSUE TITLE
b服面板查询的时候会不计算杯子部件的元素增伤

### ISSUE THREAD

**Issue by ZHN2002** [yoimiya-kokomi/miao-plugin#34]
![289ec214d51fc392](https://user-images.githubusercontent.com/106851241/173718125-999c1dda-7063-452f-95f4-55c2fce5a35d.jpg)
如图，杯子部件的元素伤害没有被计算到面板里

**Comment by yoimiya-kokomi** [comment]
下个版本fix

**Comment by yoimiya-kokomi** [comment]
已经fix
