### ISSUE TITLE
Error: read ETIMEDOUT 报错出现部分裂图和消息延迟

### ISSUE THREAD

**Issue by chen8665272** [yoimiya-kokomi/miao-plugin#35]
![173856845-5cf3503e-dddd-470a-a434-63a838c96a15](https://user-images.githubusercontent.com/60909156/173985989-fbae6f6b-6d87-4314-8c39-a2ebaf834c6b.png)

这张图发送命令十几分钟后收到的，但部分裂图。我查了一下百度是node.js相关，请问各位大神如何解决？
node.js版本是v16.14的

**Comment by yoimiya-kokomi** [comment]
正常来说就是网络问题，看是否稳定复现
或者可以更换到云服务器试试
