### ISSUE TITLE
使用#刷新面板指令报错

### ISSUE THREAD

**Issue by VeritasAlex** [yoimiya-kokomi/miao-plugin#357]
0|Yunzai-Bot  | [YzBot][10:23:16.990][ERRO] [喵喵:角色面板][refreshRank]
0|Yunzai-Bot  | [YzBot][10:23:16.991][ERRO] SyntaxError: Unexpected token '{'
0|Yunzai-Bot  |     at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
0|Yunzai-Bot  |     at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
0|Yunzai-Bot  |     at async link (node:internal/modules/esm/module_job:67:21)

**Comment by VeritasAlex** [comment]
写错了，是#刷新排行。

**Comment by yoimiya-kokomi** [comment]
更新最新版试下

**Comment by VeritasAlex** [comment]
> 更新最新版试下
已解决
