### ISSUE TITLE
关于角色面板的”换“功能在自己没有抽到角色的时候武器无法利用”换”命令正常更换的问题

### ISSUE THREAD

**Issue by OIGrass** [yoimiya-kokomi/miao-plugin#358]
我一直没有抽到七七，但是圣遗物和武器都刷好了，于是想试试假装有七七，就是那个角色面板的“换”功能，结果发现，无论什么角色，只要没有抽到，那么换默认带西风武器，及时添加了如”换精五祭礼“这样的在其他角色身上都能生效的语句也没用，圣遗物能照常换，天赋也正常，只有武器不行，目前试了长枪、弓、单手剑，其他的估计也一样。

**Comment by yoimiya-kokomi** [comment]
我这没能复现，本地没有七七数据的情况下 `#七七面板换精五祭礼` 或 `#刻晴面板换七七` 均能正常使用
