### ISSUE TITLE
请求过快，请18498秒后重试..

### ISSUE THREAD

**Issue by motian16** [yoimiya-kokomi/miao-plugin#359]
今天两个人突然就出现这种情况了，看了日志也没报错，是bug吗
![Screenshot_2022-12-11-12-21-37-55_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/89713447/206886871-6b951bf9-ea7c-403e-af6f-eac6fe5a21fa.jpg)
#

**Comment by Dr-WeiAL** [comment]
我这边有个更离谱的
![image](https://user-images.githubusercontent.com/47446553/206898200-c9f8f420-9b93-446c-bfc8-4d94ed751048.png)

**Comment by yoimiya-kokomi** [comment]
更新至最新版，应该对这种情况做了处理
