### ISSUE TITLE
`#上传深渊`无法获取b服天赋数据

### ISSUE THREAD

**Issue by Fachep** [yoimiya-kokomi/miao-plugin#369]
复现：同cookie绑定官服和b服uid，`#上传深渊`
图1为b服结果，图2为官服结果，此cookie下uid1为官服 uid2为b服
![B服](https://user-images.githubusercontent.com/31302548/208042229-04957cbd-18e9-4b9a-b59a-026b85b85a2d.gif)
![官服](https://user-images.githubusercontent.com/31302548/208042484-c554a4ad-4ba9-4304-8d35-3d44b0ced710.gif)

**Comment by yoimiya-kokomi** [comment]
没太看懂，是说上一个没有天赋数据吗？这里应该是ck的问题，新获取ck绑定后试试

**Comment by Fachep** [comment]
已解决，谢谢
