### ISSUE TITLE
#上传深渊等功能无反应

### ISSUE THREAD

**Issue by zankyo4575** [yoimiya-kokomi/miao-plugin#370]
#深渊 可以使用，
#上传深渊 无反应（不知道是miao-plugin还是api接口的问题），
#深渊十二层 等指令只会返回一个没有角色配队，只有深渊层数（是标题）的图片
yunzai和miao-plugin也都已经是最新了
喵佬看见的话救救我，有其他知道的佬也救救我，万分感激

**Comment by zankyo4575** [comment]
![Screenshot_2022-12-16-15-19-57-941_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/105942791/208045698-b44d05d8-bc1a-43d9-b99e-a6f50c1c66df.jpg)

**Comment by joexu01** [comment]
你自己也得绑定ck才行，绑定过ck才能查详情

**Comment by zankyo4575** [comment]
> 你自己也得绑定ck才行，绑定过ck才能查详情

先谢谢大佬，绑了ck的确实没问题，但之前好像没绑ck的也能上传深渊数据，#深渊十二层
等也能查看具体情况(˃ ⌑ ˂ഃ )

**Comment by yoimiya-kokomi** [comment]
深渊必须有有效ck才能查到详情，上传深渊需要这个
