### ISSUE TITLE
夜兰神奇的伤害计算替换bug血量问题

### ISSUE THREAD

**Issue by wudifeixue** [yoimiya-kokomi/miao-plugin#372]
![8`LDQ%4NN4 Z067MR{ 8XJ](https://user-images.githubusercontent.com/7316929/208292454-21f6fe81-5072-43b5-b3ce-7fc16fa077de.png)

如图所示，2命和专武都莫名的把血量给改了，变成了负提升，很奇怪

**Comment by wudifeixue** [comment]
其他人生命值测试偶尔也会有一点问题，但是略微的偏差不至于像夜兰这么大
![image](https://user-images.githubusercontent.com/7316929/208292606-c5979401-099e-4f1d-9505-adb7479f1ecc.png)
![T9H(%L0I9`XX9B ( 4OF~HT](https://user-images.githubusercontent.com/7316929/208292510-d168b44d-79e7-4016-9e21-34cb873f2556.png)

**Comment by likodesu** [comment]
因为啊，你夜兰那个你是放队伍吃了双水buff的。替换面板那个直接计算圣遗物词条你双水buff直接给剔了呢

**Comment by yoimiya-kokomi** [comment]
原本的夜兰面板数据有问题，应该是获取夜兰面板时出场了，所以获取的数据包含了夜兰被动或双水buff，导致生命值虚高

**Comment by wudifeixue** [comment]
好的谢谢解答
