### ISSUE TITLE
关于千岩长枪被动的问题

### ISSUE THREAD

**Issue by 824972158** [yoimiya-kokomi/miao-plugin#376]
![QQ图片20221227142408](https://user-images.githubusercontent.com/121478240/209621325-96d20260-0ea7-4f50-b691-1d2e04f18477.jpg)
写着四璃月4个人，但是却只加了1个人的层数，最后的计算结果也是1个人的

**Comment by yoimiya-kokomi** [comment]
收到，下个版本fix
