### ISSUE TITLE
心海排名计算不太合理

### ISSUE THREAD

**Issue by wudifeixue** [yoimiya-kokomi/miao-plugin#380]
首先有观察到最近伤害排行榜变了，但是发现心海还是老样子。

关于这个，目前可以查看到回血量，3段Q伤害，目前只计算回血量导致1命的意义完全没有了，而心海也经常作为主c输出，所以觉得用3段Q输出，如果能计算海染套的效果，会更全面的展示角色。

**Comment by yoimiya-kokomi** [comment]
心海更通用的还是奶，比输出的话一些词缀和圣遗物选择会改变，感觉不太合适

不过后续会支持排行榜排行属性的自定义功能，可允许设置排行的依据字段
