### ISSUE TITLE
有些角色的词条伤害计算一栏没有精通项目

### ISSUE THREAD

**Issue by ABT98421** [yoimiya-kokomi/miao-plugin#384]
比如#刻晴伤害4【Q总伤害·超激化】和#夜兰伤害5【Q协同单段蒸发】都是受精通影响的，词条伤害计算里没有，目前只发现了这两个
![image](https://user-images.githubusercontent.com/78371203/210072192-a3cd9881-8ae3-4c21-ae9a-1cea23023393.png)

**Comment by yoimiya-kokomi** [comment]
嗯，多谢，已经更新~
