### ISSUE TITLE
为什么自己在更新面板获取面板后，还是没能出现在群排名功能上面

### ISSUE THREAD

**Issue by Crypton-miku** [yoimiya-kokomi/miao-plugin#387]
自己已经开启了无限制，且也重置过，只是群里有自己大小两个QQ号都用着一个uid，但却看不到自己uid的排名

**Comment by Bubulujian** [comment]
前15名上榜

**Comment by Crypton-miku** [comment]
> 前15名上榜

可是，绝对是够了的，但是还是没有上

**Comment by yoimiya-kokomi** [comment]
发送 #面板 看具体展示或说明
以及如果同一个uid被多个qq号绑定，排名列表里只会展示其中一个qq号与头像，看下是不是这个原因
