### ISSUE TITLE
计算阵容伤害时，可能未考虑元素共鸣。（以甘鹤万班蓄力融化为例）

### ISSUE THREAD

**Issue by WeidongWan** [yoimiya-kokomi/miao-plugin#392]
![甘雨1精若水伤害(甘鹤万班词条伤害有问题)](https://user-images.githubusercontent.com/108603786/210470778-0811597f-d560-40cc-91f5-489cffed09a2.jpg)

我带这套圣遗物，暴率已经到78%了。甘雨天赋再加20%，就是98%。

在甘鹤万班队伍里，双冰共鸣加15%暴率，这时候暴率为113%，已经溢出了。

也就是说，此时，暴击词条减少1条，增加任意1条其它有效词条，期望伤害都应该是上升的。但词条变换表格里显示的不对。

我估计是没有考虑双冰共鸣，不知道具体是啥原因，反馈一下。

**Comment by CHxCOOH** [comment]
注意双冰共鸣buff条件，必须敌人有冰附着才能+15%暴击，在融化甘雨配队里面是不可能吃到的。不过具体数值我也没算，请先考虑这点之后再讨论伤害词条问题吧。

**Comment by panganqi** [comment]
融甘打融化是吃不到双冰共鸣的。所以buff里就没加这个。
