### ISSUE TITLE
群友怎么删除uid缓存数据

### ISSUE THREAD

**Issue by morii-water** [yoimiya-kokomi/miao-plugin#394]
怎么删除uid缓存数据

**Comment by Bubulujian** [comment]
目录：Yunzai-Bot\data\UserData   选择你要删除uid直接删掉就醒了

**Comment by Bubulujian** [comment]
主人到：Yunzai-Bot\data\UserData    选择你要删除的uid

**Comment by yoimiya-kokomi** [comment]
2.3.0版本已添加`#删除面板`功能

**Comment by morii-water** [comment]
> 2.3.0版本已添加`#删除面板`功能

似乎发送“#删除面板”无法删除
