### ISSUE TITLE
能否使用stoken进行自动祈愿刷新

### ISSUE THREAD

**Issue by thz-hub** [yoimiya-kokomi/miao-plugin#395]
到部分工具，已经可以stoken进行自动祈愿刷新，不用手动导入了，能否集成入喵喵插件？

**Comment by Algar233** [comment]
图鉴插件有

**Comment by thz-hub** [comment]
> 

请问是指[https://github.com/ctrlcvs/xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)插件吗？
需要特殊设置吗？我在图鉴设置帮助里没有看到相关设置

**Comment by thz-hub** [comment]
> 图鉴插件有

请问是指[https://github.com/ctrlcvs/xiaoyao-cvs-plugin](https://github.com/ctrlcvs/xiaoyao-cvs-plugin)插件吗？
需要特殊设置吗？我在图鉴设置帮助里未看到相关设置

**Comment by thz-hub** [comment]
> > 图鉴插件有
> 
> 请问是指https://github.com/ctrlcvs/xiaoyao-cvs-plugin插件吗？ 需要特殊设置吗？我在图鉴设置帮助里未看到相关设置

我找到了谢谢

**Comment by slideslide** [comment]
你找到在哪方便说一下吗？

**Comment by yoimiya-kokomi** [comment]
嗯，图鉴插件的功能，miao-plugin不重复搞了
