### ISSUE TITLE
Userdata转移数据不会被读取

### ISSUE THREAD

**Issue by Lycofuture** [yoimiya-kokomi/miao-plugin#411]
我将data转移到别的部署好云崽和插件的设备上，发送'#面板更新'提示需要绑定Uid，并且数据也是重新加载的，并没有读取我转移进去的数据

**Comment by GOOD-AN** [comment]
有的数据是写在redis里面的，redis持久化保存的数据转移了吗？

**Comment by yoimiya-kokomi** [comment]
在确认绑定了同样uid的情况下，userData应该能正常迁移
如果无法读取确认下目录或文件是否正确

**Comment by Lycofuture** [comment]
> 

谢谢，已经解决了。
原来有些数据是在redis里面，我以为所有数据都在userData就没有迁移redis

**Comment by AshenAshes** [comment]
想问下提问者怎么迁移redis数据？

**Comment by Lycofuture** [comment]
> 想问下提问者怎么迁移redis数据？

找到数据库位置，进行备份就好了
