### ISSUE TITLE
绫人一命的计算随着队伍伤害计算一并关闭了

### ISSUE THREAD

**Issue by neko-fu** [yoimiya-kokomi/miao-plugin#415]
不关队伍伤害的二命尾刀
![QQ图片20230124145658](https://user-images.githubusercontent.com/118741239/214230512-be24bec0-3968-4a0e-b4dd-ddb3932ad070.jpg)
关队伍伤害的二命尾刀
![QQ图片20230124145757](https://user-images.githubusercontent.com/118741239/214230574-865a8ed9-2495-4d99-8b0b-79c049658d55.jpg)
关队伍伤害的零命尾刀
![QQ图片20230124145820](https://user-images.githubusercontent.com/118741239/214230624-37213913-e406-4f44-9373-8d7117674f68.jpg)

**Comment by panganqi** [comment]
pr了，之后喵喵应该会更新
