### ISSUE TITLE
面板更新失败，可能是面板服务升级维护或遇到故障

### ISSUE THREAD

**Issue by Msdyz123** [yoimiya-kokomi/miao-plugin#418]
如下图，使用过喵喵强制更新，还是不行，强制更新显示喵喵版本已经是最新的，后台看着不像是重装，有没有大佬救救孩子
![X9QJ)688_@4)MM`R@B{J JW](https://user-images.githubusercontent.com/107755459/214840993-d4f690a4-cb81-4fbb-874c-b95fc7d59005.png)

**Comment by likodesu** [comment]
enka那边服务器问题，跟你没关系

**Comment by JohnScotttt** [comment]
我也遇到了，有解决方法吗
