### ISSUE TITLE
武器图鉴指令无反应

### ISSUE THREAD

**Issue by 1Nian-zsx** [yoimiya-kokomi/miao-plugin#420]
别的指令都可以正常工作，只有武器图鉴没反应
![image](https://user-images.githubusercontent.com/98264976/215008207-544592c3-697f-4148-abaa-99b404a41dfa.png)

**Comment by 1Nian-zsx** [comment]
yunzai是3.0.0版本，插件是2.1.9版本

**Comment by Algar233** [comment]
喵喵没有武器图鉴

**Comment by 1Nian-zsx** [comment]
那为什么把武器图鉴写在帮助里？
![image](https://user-images.githubusercontent.com/98264976/215239656-4bdc934a-837a-45a2-a9cf-53200f42eee9.png)

**Comment by Algar233** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/208

**Comment by 1Nian-zsx** [comment]
那请问能在插件帮助里去掉该项吗，或者在插件github页面标注一下，谁会知道插件功能的问题要去机器人那里找答案啊

**Comment by 1Nian-zsx** [comment]
那请问能在插件帮助里去掉该项吗，或者在插件github页面标注一下，谁会知道插件功能的问题要去机器人那里找答案啊
