### ISSUE TITLE
练度统计有部分人不显示技能等级情况

### ISSUE THREAD

**Issue by TiffanyChou21** [yoimiya-kokomi/miao-plugin#421]
不是全都不显示，只有部分人不显示，而且不显示的人也绑定了ck，查看日志也没有发现相关报错信息

**Comment by 720z** [comment]
我是所有角色都不显示技能等级，最下面有提示“未绑定cookie”；重新绑定后依然查不到技能等级；刚刚更新插件之后，#面板练度统计 也不显示，是不是米游社把技能等级关了。。。
![image](https://user-images.githubusercontent.com/78007344/216246207-938b6157-20f4-48e5-bda2-6dd5235f931f.png)
![image](https://user-images.githubusercontent.com/78007344/216246744-eca01bfd-0690-449b-b79d-878dc0e15cd4.png)
![image](https://user-images.githubusercontent.com/78007344/216246947-d0d1d4cb-9f8e-43c2-8b57-ac0d9be1275b.png)

**Comment by TiffanyChou21** [comment]
> 我是所有角色都不显示技能等级，最下面有提示“未绑定cookie”；重新绑定后依然查不到技能等级；刚刚更新插件之后，#面板练度统计 也不显示，是不是米游社把技能等级关了。。。
> ![image](https://user-images.githubusercontent.com/78007344/216246207-938b6157-20f4-48e5-bda2-6dd5235f931f.png)
> ![image](https://user-images.githubusercontent.com/78007344/216246744-eca01bfd-0690-449b-b79d-878dc0e15cd4.png)
> ![image](https://user-images.githubusercontent.com/78007344/216246947-d0d1d4cb-9f8e-43c2-8b57-ac0d9be1275b.png)

好像通过观测枢获取ck的人就有，通过抓包获取ck的就没有，ck重组一下重绑就有了，虽然我也不知道什么原理

**Comment by yiming-zh** [comment]
同样不显示天赋等级。
另外，绑完cookie后输入“#体力”能正常反馈
输入“#原石”会显示没有绑定
再输入“体力”显示没有cookie
![image](https://user-images.githubusercontent.com/32429601/216958566-1d015d24-45d7-4229-9ded-ba3942a36673.png)

**Comment by yoimiya-kokomi** [comment]
登录米游社之后，访问一下观测枢，以及访问一下 旅行工具-养成计算器 再获取ck，发送给bot试下

**Comment by yiming-zh** [comment]
目前似乎无法通过chorme访问养成计算器
https://www.miyoushe.com/ys/search?keyword=%E5%85%BB%E6%88%90%E8%AE%A1%E7%AE%97%E5%99%A8

**Comment by yiming-zh** [comment]
我的问题已解决，重新登陆网页端米游社刷新cookie即可。
