### ISSUE TITLE
小清新图和增量包图如何触发

### ISSUE THREAD

**Issue by DarknessMaria** [yoimiya-kokomi/miao-plugin#423]
安装了增量包也开启了小清新图，在目录下也能看到图片
但是用 #角色图鉴 #角色面板 都无法触发 难道是有什么隐藏方式么 
还是我有什么开关没打开

**Comment by likodesu** [comment]
那个是#xxx图片，或者#xxx触发

**Comment by fisherman34** [comment]
> 安装了增量包也开启了小清新图，在目录下也能看到图片 但是用 #角色图鉴 #角色面板 都无法触发 难道是有什么隐藏方式么 还是我有什么开关没打开

我想问一下增量包的图片是下载在哪个目录下面的？

**Comment by yoimiya-kokomi** [comment]
miao-plugin/resources/miao-res-plus
