### ISSUE TITLE
求问如何解决？“no such file.....”

### ISSUE THREAD

**Issue by Misaka23333333** [yoimiya-kokomi/miao-plugin#429]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/124157417/216064771-1ce6a70a-909d-4278-9219-801ebe35c2df.png">

**Comment by SmallK111407** [comment]
好好看readme啊喂，都说了手工下载要把-master后缀去除

**Comment by Misaka23333333** [comment]
谢谢谢谢这位大佬Orzorzorzorzorzorzorzorz%%%%%%%%%
真的非常感谢！！！！
