### ISSUE TITLE
角色持有率和深渊使用率无法查看

### ISSUE THREAD

**Issue by VeritasAlex** [yoimiya-kokomi/miao-plugin#432]
![QQ图片20230203101732](https://user-images.githubusercontent.com/57402050/216496634-2b0a3139-3443-42de-9c6c-ba3dc484d74a.jpg)
![QQ图片20230203101738](https://user-images.githubusercontent.com/57402050/216496638-ba793d1b-c4fd-47d6-b8ba-d11c4b17d48e.jpg)

**Comment by yoimiya-kokomi** [comment]
胡桃服务有点问题，等待处理就好～

**Comment by Oishiimono** [comment]
已经恢复啦
