### ISSUE TITLE
面板更新请求失败

### ISSUE THREAD

**Issue by 2497162852** [yoimiya-kokomi/miao-plugin#436]
![L)B IY~EH~D~05GYF 0P`U](https://user-images.githubusercontent.com/33111780/216648310-1c794bff-40aa-47e7-8789-a094ccfe3560.png)
![HZ068XX42K~3N57E7RA PIL](https://user-images.githubusercontent.com/33111780/216648366-3673b8b4-3842-4858-905e-81f7398349cd.png)
官网和两个中转都换过，三天了还是这样

**Comment by 2497162852** [comment]
已解决 角色别名

**Comment by MAakber** [comment]
我也遇到了同样的问题
群里面返回

`请求失败，可能是面板服务升级维护或遇到故障，请稍后重试...`
