### ISSUE TITLE
#组队伤害 后台有识别 但无输出

### ISSUE THREAD

**Issue by thz-hub** [yoimiya-kokomi/miao-plugin#440]
#组队伤害 后台有识别 但无输出 这是怎么回事，是我命令弄错了吗？

**Comment by SmallK111407** [comment]
这是喵喵的？

**Comment by yoimiya-kokomi** [comment]
非喵喵相关的命令

**Comment by thz-hub** [comment]
![3df294808b3813f7](https://user-images.githubusercontent.com/62689630/217132218-97ad8a24-f3fe-479c-a75b-14bc5fe01989.jpg)
这个不是有组队伤害吗
