### ISSUE TITLE
建议凯亚排行榜改为以单段Q伤为排行依据

### ISSUE THREAD

**Issue by duur** [yoimiya-kokomi/miao-plugin#445]
他是主Q角色，排e带绝缘套的很吃亏

**Comment by yoimiya-kokomi** [comment]
收～

**Comment by duur** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by TeRiRi1018** [comment]
> 

你在miao-plugin/resources/meta/character/凯亚/calc.js
里面加一句
export const defDmgIdx = 1
按照0123的顺序，1为第二项，就是q伤害，同理如果有别的你想微调的群排行依据也能这样。

**Comment by duur** [comment]
> > 
> 
> 你在miao-plugin/resources/meta/character/凯亚/calc.js 里面加一句 export const defDmgIdx = 1 按照0123的顺序，1为第二项，就是q伤害，同理如果有别的你想微调的群排行依据也能这样。

感谢！回去试试
