### ISSUE TITLE
建议将 #面板帮助 命令写在 #喵喵帮助 当中

### ISSUE THREAD

**Issue by classmatezhu** [yoimiya-kokomi/miao-plugin#446]
类似的 #体力帮助 #记录帮助 命令都已经写在了 #喵喵帮助 面板当中。建议将 #面板帮助 也写在 #喵喵帮助 当中。方便普通用户了解喵喵的命令。

**Comment by yoimiya-kokomi** [comment]
多谢，已经补充~
不过已经自定义过config/help.js的需要手工补充
