### ISSUE TITLE
香菱的伤害计算里面没有算精通这一栏，希望补上

### ISSUE THREAD

**Issue by hunghunsongge** [yoimiya-kokomi/miao-plugin#449]
![%)MVW6}GEC%V4OQM PV((4M](https://user-images.githubusercontent.com/60694424/217528869-0d254933-0ecd-4887-b2ed-c08b32e8eb44.gif)

**Comment by yoimiya-kokomi** [comment]
ok，下个版本补充

**Comment by yoimiya-kokomi** [comment]
2.3.0版本已经更新
