### ISSUE TITLE
我使用了sudo yum install -y chromium解决了此问题

### ISSUE THREAD

**Issue by hanyangwendao** [yoimiya-kokomi/miao-plugin#450]
> recv from: [Private: 3362710936(friend)] 喵喵帮助 [YzBot][02:25:06.450][MARK] puppeteer Chromium 启动中。。 [YzBot][02:25:06.471][ERRO] Error: Failed to launch the browser process! /home/jijiang/Yunzai-Bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
> [YzBot][02:25:06.471][ERRO] puppeteer Chromium 启动失败
> 
> 这东西怎么安装

试一试下面的代码：

安装_Chrome_Binary-可选
注意：若是 Aarch64 架构不可跳过，若是其他架构云崽运行时报错 puppeteer 启动失败 可再来安装。

提示：可使用 uname -a 查看系统架构。

sudo apt install chromium-browser -y
安装其他依赖
sudo apt install libgbm-dev libasound2-dev -y

_Originally posted by @cola2050 in https://github.com/yoimiya-kokomi/miao-plugin/issues/74#issuecomment-1225996279_

**Comment by GBTBS** [comment]
![Image](https://github.com/user-attachments/assets/926af076-b36f-43f3-a4db-81e6bac52fea)

大佬救救我这个，我用你的后还是有这个图片报错
