### ISSUE TITLE
查询面板失败

### ISSUE THREAD

**Issue by xiaoACE6716** [yoimiya-kokomi/miao-plugin#451]
机器人返回：请求失败，可能是面板服务升级维护或遇到故障，请稍后重试...
2月10号，看别人的Issues说更新到最新版可以解决问题。然而将喵喵更新到最新版也仍然失败，官网与两个中转都尝试过

**Comment by yoimiya-kokomi** [comment]
删除miao-plugin/config/profile.js（若有），重启bot
如果还失败确认下bot版本，是否是2.2.2或以上。以及发一下#面板 命令看下右下角的更新服务

**Comment by xiaoACE6716** [comment]
已尝试，官网可以正常使用，中转还是不行(用中转是因为有时候有网络问题)，那我先使用官网吧

**Comment by QingXi-z** [comment]
请问官网是什么

**Comment by xiaoACE6716** [comment]
> 请问官网是什么

**Comment by lin-junliang** [comment]
> 请问官网是什么

https://enka.network/
