### ISSUE TITLE
面板更新冷却时长

### ISSUE THREAD

**Issue by Lycofuture** [yoimiya-kokomi/miao-plugin#459]
为什么修改冷却时长为1分钟，重启后还是提示5分钟的冷却

**Comment by yoimiya-kokomi** [comment]
config/profile.js 配置文件，确认下是否修改了正确的文件，改完重启

以及如果面板服务返回了服务侧缓存时间，且缓存时间比配置的等待时间长的话，会以服务侧的更新时间为准。因为即使发起请求服务也不会返回新的数据
