### ISSUE TITLE
希望添加赛诺渡荒之雷伤害 修复天赋5计算错误

### ISSUE THREAD

**Issue by neko-fu** [yoimiya-kokomi/miao-plugin#463]
①天赋5错误
![IMG_20230212_011906](https://user-images.githubusercontent.com/118741239/218272433-c038b06e-5bbb-4fff-bf7e-0e02f7500508.jpg)
②能否像微信小程序一样给赛诺添加渡荒之雷的伤害计算?
并且计算qte下强化e和三道渡荒之雷的激化总伤害?
如下图，不计算qte下总伤害只算强化e激化伤害导致专武饰金攻击沙和精通沙差距寥寥无几。
![553df3a9f26c72de](https://user-images.githubusercontent.com/118741239/218272444-06eae19e-e911-4da8-8676-56141b5f3ef8.jpg)
![-5bd26003fb73ed2](https://user-images.githubusercontent.com/118741239/218272451-3e5b9aa4-3c44-47cc-af39-e916ee05d7fd.jpg)

**Comment by panganqi** [comment]
这个要喵喵更新伤害计算框架，现在的伤害计算不能很好的支持这个计算
