### ISSUE TITLE
夜兰伤害排名居然是看重击的嘛

### ISSUE THREAD

**Issue by ayakasuki** [yoimiya-kokomi/miao-plugin#465]
如题，我发现群里有个分很低，但是带了强化重击的弓，E和Q都伤害不够，但是居然是按第一项排名嘛

**Comment by yoimiya-kokomi** [comment]
夜兰默认看q协同蒸发
如果排名有问题更新最新版，以及群内执行下 #刷新排名
如果还有问题确认下文件是否有其他改动

**Comment by ayakasuki** [comment]
ok了，谢谢~



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月14日 11:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yoimiya-kokomi/miao-plugin] 夜兰伤害排名居然是看重击的嘛 (Issue #465) |

夜兰默认看q协同蒸发
如果排名有问题更新最新版，以及群内执行下 #刷新排名
如果还有问题确认下文件是否有其他改动
