### ISSUE TITLE
夜兰圣遗物评分问题

### ISSUE THREAD

**Issue by GOOD-AN** [yoimiya-kokomi/miao-plugin#467]
夜兰圣遗物评分有精通选项，且计算蒸发伤害，但实际上大部分人的夜兰都是补水为其他角色反应使用，很少有直接让夜兰打蒸发的。
所以更多都是为了开出Q，那么充能的要求也相对会有一些，算精通且比充能比重高感觉不太符合实际。

**Comment by Fwindy** [comment]
个人反对，精通夜兰肯定需要保留，我就是玩蒸夜的，需要刻意压充能抬精生双爆，精通权重肯定比充能高很多。
只是精通夜兰规则的精通阈值现在调成80了，对于一些不玩蒸夜但歪了不少精通词条的人来说，也会改成精通算法可能确实不太友好。

**Comment by neko-fu** [comment]
为了保充能精通会堆的少所以评分占比高正常，最好还是评分规则可以自主调而不是现在的被动。

**Comment by GOOD-AN** [comment]
我与楼上[neko-fu](https://github.com/neko-fu)大佬意见一致，希望可以自行调整或者有多套可以选择。

**Comment by Fwindy** [comment]
> 为了保充能精通会堆的少所以评分占比高正常，最好还是评分规则可以自主调而不是现在的被动。
> 我与楼上[neko-fu](https://github.com/neko-fu)大佬意见一致，希望可以自行调整或者有多套可以选择。

可是挺早就可以自行调整了
看这个pr #179

**Comment by GOOD-AN** [comment]
> > 为了保充能精通会堆的少所以评分占比高正常，最好还是评分规则可以自主调而不是现在的被动。
> > 我与楼上[neko-fu](https://github.com/neko-fu)大佬意见一致，希望可以自行调整或者有多套可以选择。
> 
> 可是挺早就可以自行调整了 看这个pr #179

但是没有办法设置多个然后自行选择吧？

**Comment by Fwindy** [comment]
> 但是没有办法设置多个然后自行选择吧？

我看你们描述，需要的应该还是自定义一套切换规则，比如精通超过多少才会把精通计入权重，或者特定的配装才把精通计入权重，其它情况则用另一套无精通的权重，这个需求直接看那个pr就行。
真的想在一堆切换规则里再做切换的话，简单点就自己写个yunzai插件处理下文件替换+重启。

**Comment by GOOD-AN** [comment]
> 我看你们描述，需要的应该还是自定义一套切换规则，比如精通超过多少才会把精通计入权重，或者特定的配装才把精通计入权重，其它情况则用另一套无精通的权重，这个需求直接看那个pr就行。 真的想在一堆切换规则里再做切换的话，简单点就自己写个yunzai插件处理下文件替换+重启。

我这边的想法会复杂一些，就是用户输入哪一套就用哪一套来计算，或者想自定义权重可以输入数值来调整，就和现在计算面板更换圣遗物差不多。

**Comment by neko-fu** [comment]
> > 我看你们描述，需要的应该还是自定义一套切换规则，比如精通超过多少才会把精通计入权重，或者特定的配装才把精通计入权重，其它情况则用另一套无精通的权重，这个需求直接看那个pr就行。 真的想在一堆切换规则里再做切换的话，简单点就自己写个yunzai插件处理下文件替换+重启。
> 
> 我这边的想法会复杂一些，就是用户输入哪一套就用哪一套来计算，或者想自定义权重可以输入数值来调整，就和现在计算面板更换圣遗物差不多。

这个太难太复杂了，而且其实实用性不高。

**Comment by GOOD-AN** [comment]
> 这个太难太复杂了，而且其实实用性不高。

嗯。。。确实，后面我再慢慢看吧，看我这边需要的人多不多，主要是对Node.js不熟，这个issue我先关了吧，至少初步的问题解决了，感谢以上各位大佬。
