### ISSUE TITLE
关于#喵喵设定 对锅巴Plugin的适配

### ISSUE THREAD

**Issue by ldcivan** [yoimiya-kokomi/miao-plugin#472]
不知道作者有没有将来进行锅巴适配的计划？因为现在喵喵的开关越来越多了，在QQ上通过消息进行配置已经有点麻烦了T T

或者说，我也可以自己试着写个适配（bushi

**Comment by yoimiya-kokomi** [comment]
计划适配，但是一直咕中
理论上读写配置都比较完备了，差个scheme翻译

**Comment by ldcivan** [comment]
> 计划适配，但是一直咕中 理论上读写配置都比较完备了，差个scheme翻译

好滴，那咱就等等吧w

thx~
