### ISSUE TITLE
询问 喵喵外置圣遗物计算工具

### ISSUE THREAD

**Issue by QingXi-z** [yoimiya-kokomi/miao-plugin#473]
就是由于每次更换圣遗物计算评分需要更新面板，而游戏面板加上喵喵面板更新都需要一定时间
我这边是想问一下可不可以建立一个小工具，用户自己填写角色，圣遗物位置及属性，然后就会生成喵喵的评分，或者说是喵喵插件发出的圣遗物面板图片
就是觉得这样等更新面板时间太久了想自己手动评分，比较喜欢喵喵的评分规则，但是自己不知道怎么计算

**Comment by yoimiya-kokomi** [comment]
走手工填写或ocr感觉对于bot场景也不是特别适合

如果有比较多的圣遗物评分场景，可以考虑将需要查看的不同圣遗物装备在多个角色上，然后更新面板后，通过面板替换功能，替换圣遗物进行查看

具体命令可以参见 #面板帮助

**Comment by QingXi-z** [comment]
好的学到了！
