### ISSUE TITLE
更新最新版本后 部分‘原图’对应不上面板图

### ISSUE THREAD

**Issue by 127Wzc** [yoimiya-kokomi/miao-plugin#483]
异常截图：
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/52766844/220654937-99e45d69-3708-48cd-a327-58310af20992.png">
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/52766844/220655892-e899c181-696d-4f52-b2d7-433b47921c43.png">

原图路径: miao-plugin/resources/profile/normal-character

**Comment by yoimiya-kokomi** [comment]
下个版本fix

**Comment by yoimiya-kokomi** [comment]
此问题已经fix，更新至最新版即可

**Comment by 127Wzc** [comment]
> 此问题已经fix，更新至最新版即可

收到
