### ISSUE TITLE
云崽显示QQ版本更新

### ISSUE THREAD

**Issue by 18576004957** [yoimiya-kokomi/miao-plugin#490]
![屏幕截图 2023-02-25 180026](https://user-images.githubusercontent.com/54264740/221343616-a092493f-bba7-4e41-a022-0faf33d239c6.jpg)
请问这个要怎么解决呀..重新下载也不行诶

**Comment by Kochisa** [comment]
QQ号风控

**Comment by 18576004957** [comment]
是需要我换个QQ号登录嘛？我换了个号还是显示QQ版本过低..要怎么解决QQ号风控呀

**Comment by 18576004957** [comment]
> QQ号风控

是需要我换个QQ号登录嘛？我换了个号还是显示QQ版本过低..要怎么解决QQ号风控呀

**Comment by xiaopebaka** [comment]
我也遇到同样的问题  怎么解决啊

**Comment by Kochisa** [comment]
> > QQ号风控
> 
> 是需要我换个QQ号登录嘛？我换了个号还是显示QQ版本过低..要怎么解决QQ号风控呀

QQ拿手机登一次把风控解除 然后把账户配置文件删掉重新登

**Comment by NEORUAA** [comment]
设备类型改成手表试试

**Comment by 18576004957** [comment]
> > > QQ号风控
> > 
> > 
> > 是需要我换个QQ号登录嘛？我换了个号还是显示QQ版本过低..要怎么解决QQ号风控呀
> 
> QQ拿手机登一次把风控解除 然后把账户配置文件删掉重新登

这个号我手机一直登陆着的，没显示有风控啥的呀，然后账户配置文件删除是指把Yunzai里的config文件整个删除嘛？

**Comment by 127Wzc** [comment]
![image](https://user-images.githubusercontent.com/52766844/221483833-9aadf3ac-9867-48e9-a488-dc68924fd3aa.png)

**Comment by 18576004957** [comment]
> ![image](https://user-images.githubusercontent.com/52766844/221483833-9aadf3ac-9867-48e9-a488-dc68924fd3aa.png)

谢谢！！按照上面的方法可以啦！！QAQ
