### ISSUE TITLE
希望申请一份Api的token

### ISSUE THREAD

**Issue by A7424** [yoimiya-kokomi/miao-plugin#5]

**Comment by yoimiya-kokomi** [comment]
目前功能与API非公开，请到YunzaiBot群找喵喵或九章私聊申请
群聊现在应该是满的，等开放后可申请

**Comment by A7424** [comment]
> 目前功能与API非公开，请到YunzaiBot群找喵喵或九章私聊申请 群聊现在应该是满的，等开放后可申请

好的
