### ISSUE TITLE
double check一下。 喵喵自己有带 十连抽卡模拟的功能吗

### ISSUE THREAD

**Issue by jerryx-first** [yoimiya-kokomi/miao-plugin#506]
喵喵的帮助里有个十连，十连2 啥的，
但是看了下代码，我没找到 喵喵插件里面卡池十连的实现.
没写过JS 不敢断定,简单梳理了下逻辑没看到相关代码。。。
 
老鸟仓库被锁了之后，原来库里面自带的genshin插件 十连功能 连卡池都没人维护了，得自己去手动改卡池配置文件。。。
我又不敢把那个原神插件给删了，怕引起什么依赖故障。。。

喵喵如果有的话直接用喵喵的

**Comment by yoimiya-kokomi** [comment]
没有
帮助里有这个命令是因为 #喵喵帮助 是设计可以覆盖yunzai原有帮助的，所以带了yunzai的功能说明
