### ISSUE TITLE
『#更新面板』有时候不返回图片

### ISSUE THREAD

**Issue by RemCandy** [yoimiya-kokomi/miao-plugin#509]
![IMG_20230308_115255](https://user-images.githubusercontent.com/72900249/223615860-c1ae8f57-8427-46d3-8bc8-8936e52b7adb.jpg)
![IMG_20230308_115213](https://user-images.githubusercontent.com/72900249/223615869-f4786d5c-b057-4f5b-a2f0-306ca50c1eef.jpg)

正常情况下会多一步『图片生成』，不知道是不是bug，谢谢喵佬🥰🥰
![IMG_20230308_115444](https://user-images.githubusercontent.com/72900249/223615992-10a2006c-2a88-4f87-8658-abc56c940f06.jpg)

**Comment by PrussianBlueCN** [comment]
遇到了同样的问题，而且似乎问题集中在一个特定的群上，同样的uid在其他群就正常返回图片。

**Comment by Gimhoy** [comment]
私聊也有这个问题

**Comment by wayne3602** [comment]
+1,换网址也不行

**Comment by MiniGrayGay** [comment]
面板更新报错50x错误码的这个问题大概已经定位到了，大概率和我在CDN启用了GZip+Brotli压缩返回数据，并且为了响应速度加上了range协议头，但是服务器不兼容有关。晚点会处理一下
