### ISSUE TITLE
特定用户#更新面板 无返回，后台报错Enka ReqErT: 504 Gateway Time-out

### ISSUE THREAD

**Issue by PrussianBlueCN** [yoimiya-kokomi/miao-plugin#511]
联动 #509 ，经过近两天观察这一问题目前有这样的特征：
1. 只在特定用户身上发生。虽然之前其他人也偶尔出现这样问题，但近2天左右时间这一问题只能在固定的一位群友身上稳定复现。出现问题的uid：152212847；
2. 该uid在其他机器人上，无论是miao-api还是miniGG均可正常更新面板，该用户在出现问题的机器人这里使用其他生成图片的功能（包括来自喵喵的）均正常；
3. 将后台日志输出等级改为Debug后发现报错如下图，已确认#喵喵设置 中面板服务固定miniGG：
![f61cac30776f522b9932f9f09b29bf92](https://user-images.githubusercontent.com/110645427/224333367-1f4c41fa-e3a2-4b21-bb0c-f3bd406b8fde.png)
4. 已尝试过的解决办法：重启、问题用户退群后重启、问题用户删好友并退群后重启、更新喵喵插件、切换到ENKA（怎么想也不会有用吧！），均未起到作用。
机器人系统环境：腾讯云centos8，nodejs 19.2

**Comment by PrussianBlueCN** [comment]
更新，rm miao-plugin并重装，仍不能解决该用户请求不到面板的问题（悲

**Comment by PrussianBlueCN** [comment]
更新，今早开始所有群的所有用户在这个机器人更新任何uid的面板都会报错Enka ReqErT: 504 Gateway Time-out了。

**Comment by wayne3602** [comment]
@PrussianBlueCN 兄弟，怎么切换到ENKA的？

**Comment by ProblemFactory** [comment]
> @PrussianBlueCN 兄弟，怎么切换到ENKA的？

#喵喵设置面板服务2

**Comment by wayne3602** [comment]
@ProblemFactory 谢谢，已解决
