### ISSUE TITLE
抽卡分析的命令报错

### ISSUE THREAD

**Issue by Yuuuuu0** [yoimiya-kokomi/miao-plugin#523]
![image](https://user-images.githubusercontent.com/44354554/226605577-0e80a5e8-bf35-4d5d-bee2-ab565313a346.png)
at file:///root/Miao-Yunzai/plugins/miao-plugin/apps/gacha/GachaData.js:155:55

**Comment by 1055169799** [comment]
更新喵喵插件即可解决
