### ISSUE TITLE
#抽卡帮助 发送抽卡帮助后再发送米哈游登录或米哈游登录 邮箱机器人均无响应

### ISSUE THREAD

**Issue by karl2829** [yoimiya-kokomi/miao-plugin#529]
![github1](https://user-images.githubusercontent.com/81348420/227094086-b32ffde8-7f2c-46fe-90e2-bf678fb80fa0.png)
![github2](https://user-images.githubusercontent.com/81348420/227094143-9407ec66-34ec-43fd-8a17-3d781ce74e2c.png)

使用的是Miao-Yunzai，均为最新版本

**Comment by zysbksn** [comment]
我是更新抽卡记录没有响应

**Comment by karl2829** [comment]
其它插件导致的，删除其它插件恢复到初始抽卡帮助了，但是没看懂怎么添加抽卡记录
