### ISSUE TITLE
查询角色伤害，图片数据全部不显示了

### ISSUE THREAD

**Issue by lgyseven** [yoimiya-kokomi/miao-plugin#53]

**Comment by AkiraShe** [comment]
![MSEW31NU )X2D`QALOIH913](https://user-images.githubusercontent.com/44690109/176805149-c89ff693-bdf9-402a-a2b7-b00a901f531e.gif)
我也遇到同样问题。同一个角色，多执行几次 #角色伤害 命令，偶尔能正常显示。miaomiao插件版本1.8.3（刚更新的，依然存在问题）

**Comment by zzctonyh** [comment]
先npm run log看看啊

**Comment by AkiraShe** [comment]
> 先npm run log看看啊
![2795D1BB683688FC3E6EAE3B46C733C9](https://user-images.githubusercontent.com/44690109/176872348-00ff57d9-9486-4334-967e-25530d27333e.jpg)
你好，log如附图。第一次 #夜兰伤害查询正常，第二、第三次异常。

**Comment by yoimiya-kokomi** [comment]
渲染逻辑在Yunzai中，可尝试在渲染时增加一定延时看是否有改善
Yunzai现在暂时无法合入变更了，可以切换到这里更新下试试
https://github.com/yoimiya-kokomi/Yunzai-Bot

或者参考lib/render.js自行修改下试试

**Comment by AkiraShe** [comment]
切换到https://github.com/yoimiya-kokomi/Yunzai-Bot更新后，#角色伤害 命令连续执行10次都正常了，感谢！

**Comment by lgyseven** [comment]
谢谢回答！重新配置后可以用了
