### ISSUE TITLE
#面板 显示的群排名错误

### ISSUE THREAD

**Issue by NotIvny** [yoimiya-kokomi/miao-plugin#535]
更新喵喵插件后后#面板 显示的群排名错误，圣遗物排名显示为综合练度排名，回滚到前几天的版本没问题。
例如：某人雷神综合练度排名第4，圣遗物排名第1，实际却显示综合练度排名第1。
before
![F434615B-6066-4C56-84CE-5008698CDEC0](https://user-images.githubusercontent.com/125482125/228271218-365acb2e-5303-4fae-bad0-45f97ae4a459.jpeg)
after
![0F0BC875-416E-4F84-8571-8F260F1DBAEA](https://user-images.githubusercontent.com/125482125/228271273-5e9c54a4-4d11-409a-8d14-4c839f9d0d9a.jpeg)
雷神，神子，刻晴，迪卢克的圣遗物排名均显示成了综合练度排名，而#XX排名的数据与这个对不上。

**Comment by 13766816608** [comment]
+1
