### ISSUE TITLE
功能请求：套装切换

### ISSUE THREAD

**Issue by CUZNIL** [yoimiya-kokomi/miao-plugin#540]
目前是支持换指定圣遗物、换角色换武器等。
希望能再支持在保持圣遗物所有主词条副词条不变的前提下换套装。
比如：
发送“#可莉面板换追忆角斗”，会更改为追忆角斗2+2；
发送“#神里面板换冰套4”，会更改为冰套4；
发送“#七七面板换散件”，会更改为五件不同套装；
发送“#七七面板换海染2”，会更改为海染2+散件；

正准备提的时候看到https://github.com/yoimiya-kokomi/miao-plugin/issues/329 已经提过了，但是似乎还没有做。我本来想自己改好了提pr的，应该是要改[ProfileChange.js](https://github.com/yoimiya-kokomi/miao-plugin/blob/master/apps/profile/ProfileChange.js)，但是我看半天还是没搞懂是怎么处理的，不知道该怎么写
![TKA7KH4E%)@LZ8 0$D~T$)B](https://user-images.githubusercontent.com/76582404/229761731-491f52cd-ce82-4dc4-aeb3-8fec11f8eed7.gif)

**Comment by lin-junliang** [comment]
想换套装可以找排名上的群友的圣遗物拿过来换一下就好了，如果换的话到底是哪个位置随机换成套装？
感觉不到这个功能的实用性，你可以详细说说

**Comment by CUZNIL** [comment]
> 想换套装可以找排名上的群友的圣遗物拿过来换一下就好了，

换群友的圣遗物会有圣遗物本身主副词条差距较大、双爆难以配平等问题，无法回答“如果我这堆散件变成冰套4，我可以提升多少伤害？”的这个问题。

>如果换的话到底是哪个位置随机换成套装？ 

直接全改就行。举个例子：

检测到“换冰套4”，就把圣遗物artis对应的名称name全部改成冰套的对应昵称，换花毛沙杯。

检测到“换追忆决斗”，就把花毛改成追忆套，沙杯头改成决斗套。

检测到“换海染2”，就把花毛改成海染套，沙杯头依次改成乐团决斗追忆（随意规定三个不同的圣遗物套装即可，之后每次检测到换2件套就换沙杯头为这三件不同的，乐团决斗追忆是举例子。）

而且有一说一，想做随机倒是也不影响，只有换2件套需要稍微多考虑一层有没有变4件套。

>感觉不到这个功能的实用性，你可以详细说说

回答“如果我这堆散件变成冰套4，我可以提升多少伤害？”的问题，让群友明确自己去刷某个本预期收益是多少，从而决定刷不刷或者是吹水"如果我也有冰套4"。总之是有用的，我这里经常看到有人尝试只换套装不换词条，我自己也需要这个功能。
