### ISSUE TITLE
为啥妮露排名比的是水月伤害？

### ISSUE THREAD

**Issue by BaiMaollk** [yoimiya-kokomi/miao-plugin#546]

**Comment by BaiMaollk** [comment]
组队伤害关了的，能不能自己设置排名的方式，或者把妮露的默认排名方式设置成丰穰之核伤害而不是水月伤害，大部分人玩妮露还是玩种子的吧

**Comment by Warkeeper** [comment]
@BaiMaollk 可以自己设置的

自己去修改这个文件

https://github.com/yoimiya-kokomi/miao-plugin/blob/a009b9678d1b86599c87ba4ffaaf877497f881c0/resources/meta/character/%E5%A6%AE%E9%9C%B2/calc.js#L36

在上面这一行👆前面加一行这个👇
```
export const defDmgIdx = 5
```
