### ISSUE TITLE
更新面板获取不到妮露

### ISSUE THREAD

**Issue by Dr-WeiAL** [yoimiya-kokomi/miao-plugin#548]
尝试过删除面板重新更新，角色展柜里面八个角色只获取到七个，唯独妮露获取不到
使用浏览器进入enka.network获取角色可以正常获取到妮露
![image](https://user-images.githubusercontent.com/47446553/231569558-24b99693-205f-48c1-9c49-404a1e767e00.png)
![image](https://user-images.githubusercontent.com/47446553/231569579-ab017171-bf83-486c-bd0c-4b9d83220043.png)

**Comment by pw317** [comment]
我这边的现象是花海套圣遗物有bug，其他的圣遗物都能成功更新。花海套的名字和图片显示不出来。词条是对的。套装效果没有。

**Comment by pw317** [comment]
修好啦👍
