### ISSUE TITLE
#签到-能不能改一下签到逻辑，签到QQ绑定下的全部Cookie（毕竟群友没有权限执行#全部签到）

### ISSUE THREAD

**Issue by RockRadix** [yoimiya-kokomi/miao-plugin#55]

**Comment by 1055169799** [comment]
试试 
绑定一个帐号之后发送#开启自动签到，然后再去绑定下一个，再发#开启自动签到
在你已经绑定了账号的这种情况下，可以切换账号发送#开启自动签到，然后再切换下一个发送#开启自动签到

**Comment by yoimiya-kokomi** [comment]
切换至喵喵分支Yunzai，已经支持此能力
https://github.com/yoimiya-kokomi/Yunzai-Bot
