### ISSUE TITLE
enka可以正常查询，bot查询面板提示维护

### ISSUE THREAD

**Issue by lin-junliang** [yoimiya-kokomi/miao-plugin#555]
![image](https://user-images.githubusercontent.com/59049320/233757475-80ee10db-d890-433c-b9fd-700105e9746a.png)

**Comment by hutao571** [comment]
面板服务改4试试，2请求国内uid默认会重定向到3，3现在寄了

**Comment by lin-junliang** [comment]
> 面板服务改4试，2请国内uid默认会重定到3，3现在寄了

谢谢能用了！！

**Comment by karakoo** [comment]
> 面板服务改4试试，2请求国内uid默认会重定向到3，3现在寄了

@yoimiya-kokomi 希望可以弄个配置，是否自动重定向

**Comment by lin-junliang** [comment]
> > 面板服务改4试试，2请求国内uid默认会重定向到3，3现在寄了
> 
> @yoimiya-kokomi 希望可以弄个配置，是否自动重定向

我补一句，我出现的问题应该不是重新定向了。是可以设置的，把这个文件复制一份删掉后缀_default就可以取消定向了（\plugins\miao-plugin\config\profile_default.js）
刚刚试了一下0和2，已经可以正常使用了
