### ISSUE TITLE
自动切换更新面板服务

### ISSUE THREAD

**Issue by GOOD-AN** [yoimiya-kokomi/miao-plugin#556]
十分抱歉，之前提过一次在请求面板失败时自动切换的问题，今天不得不再次提出这个建议，有时候请求面板并不是enka的问题，而是代理服务的不稳定造成的报错，比如我这边今天中午Minigg的服务出现了异常，而Hutao的服务正常，夜间又出现了Hutao的服务异常，而Minigg的服务正常。

就是当设置面板服务为 0 的时候，如果Minigg服务出现了异常，则请求Hutao服务，还异常则请求enka本身的服务。

当前手动切换服务还是造成了一定的维护困难，不能及时判断哪个服务还在正常提供，切换后还需尝试才能得知，而且因个人生活、工作等诸多原因，很多时候很难去及时的操作切换到正常的服务上。

还有一点就是超时等待时间是否可以自定义一下，很多时候还是感觉超时等待时间长了些。

望大佬考虑。

**Comment by lin-junliang** [comment]
+1，其实0是自动就应该是自动才对的，不知道什么自动了，不过等待时间是可以改的
\plugins\miao-plugin\config\profile_default.js
这个文件复制一份删掉后面的_default，打开看最下面，那个5就是5分钟，改成1就是1分钟，enka是1分钟

**Comment by GOOD-AN** [comment]
> +1，其实0是自动就应该是自动才对的，不知道什么自动了，不过等待时间是可以改的
> \plugins\miao-plugin\config\profile_default.js
> 这个文件复制一份删掉后面的_default，打开看最下面，那个5就是5分钟，改成1就是1分钟，enka是1分钟

不好意思，是我没表达清楚，我说的等待不是单账号上一次请求与下一次请求之间的等待CD，而是单次请求中网络链接的超时时间。
