### ISSUE TITLE
星铁更新面板uid错误

### ISSUE THREAD

**Issue by xuyueeeer** [yoimiya-kokomi/miao-plugin#581]
扫码登陆并获取ck后，星铁更新面板更新的是原神的uid,不会跳转到星铁uid上，导致更新的面板信息是别人的。

**Comment by Tsuk1ko** [comment]
同样的问题

**Comment by yoimiya-kokomi** [comment]
如果使用的是Miao-Yunzai，更新至最新版本即可，已经支持多游戏uid共存

如果使用其他Yunzai版本，同一个角色的uid只有一个，需手工切换或附带uid进行查询
