### ISSUE TITLE
#角色伤害请求失败

### ISSUE THREAD

**Issue by hchen1134** [yoimiya-kokomi/miao-plugin#59]
![image](https://user-images.githubusercontent.com/28447051/177575207-e712625d-5461-4b0c-afdd-19c99a665f15.png)
查询#烟绯伤害、#云堇伤害 时看到以上报错，#面板、#养成等功能不受影响
目前只发现了烟绯和云堇有这个问题，没有排查所有的角色

**Comment by yoimiya-kokomi** [comment]
更新至最新版喵喵看下，应该是旧数据格式的兼容问题

**Comment by hchen1134** [comment]
烟绯正常了，可是云堇还是报错……
