### ISSUE TITLE
[BUG]无法读取星铁角色遗器

### ISSUE THREAD

**Issue by mbnull** [yoimiya-kokomi/miao-plugin#598]
![ed1c9b550c419b362b1814eb72210fd3](https://github.com/yoimiya-kokomi/miao-plugin/assets/107937053/9f89b174-bb04-4dc2-b6fc-8ce8688788ae)

不靠谱的猜测，是因为mihomo更换了api的值，我自己直接访问是包含了遗器信息的。
#597

**Comment by yukiice** [comment]
我也遇到了，无法获得遗物

**Comment by jiegengyun** [comment]
一样的问题，之前是一直更新失败，现在能更新  出来全都是1级  不刷新遗器

**Comment by HL5570** [comment]
yes，我也

**Comment by mbnull** [comment]
今天上午的commit之后能正常用了。
