### ISSUE TITLE
token怎么查看啊

### ISSUE THREAD

**Issue by shengxionggandi** [yoimiya-kokomi/miao-plugin#6]
您好，我在bot本体中找到了一个名称为token，但是没有后缀的文档，不知道是不是这个（而且我打开之后也都是乱码）如果是的话怎么查看啊，或者怎么申请一个token（

**Comment by yoimiya-kokomi** [comment]
目前功能与API非公开，请到YunzaiBot群找喵喵或九章私聊申请
群聊现在应该是满的，等开放后可申请
--
找到的token不是，估计你看的是oicq的登录token

**Comment by shengxionggandi** [comment]
啊啊啊好的好的，谢谢啦
