### ISSUE TITLE
能更新下伤害计算吗QAQ

### ISSUE THREAD

**Issue by neko-fu** [yoimiya-kokomi/miao-plugin#605]
赛诺渡荒之雷

 白术q激化伤害，因为独立附着

 八重e和q的激化伤害
八重好像只有配队时的激化伤害，

 珐露珊e伤害，因为高命是连续触发e的副c

**Comment by AshenAshes** [comment]
更新已合入#613

**Comment by neko-fu** [comment]
> 更新已合入#613

感谢采纳！
