### ISSUE TITLE
银狼e数据三个效果的数值错乱了

### ISSUE THREAD

**Issue by Tsuk1ko** [yoimiya-kokomi/miao-plugin#611]
单体伤害->基础概率  
基础概率->伤害抗性降低  
伤害抗性降低->单体伤害

https://github.com/yoimiya-kokomi/miao-plugin/blob/5e702985470e3b91235a436af40f66941567fe69/resources/meta-sr/character/%E9%93%B6%E7%8B%BC/data.json#L69-L140

![image](https://github.com/yoimiya-kokomi/miao-plugin/assets/24877906/9635631e-fb9c-4cf8-818a-d977dbf4c527)

**Comment by AshenAshes** [comment]
更新已合入#613
