### ISSUE TITLE
怎么关闭默认开启的喵喵版功能

### ISSUE THREAD

**Issue by JadeVane** [yoimiya-kokomi/miao-plugin#614]
装完喵喵插件，下面这些设置默认开启，且无法关闭

![2023-08-01_09-18](https://github.com/yoimiya-kokomi/miao-plugin/assets/34258753/bf6c7364-9db6-4827-add7-e496ce761d3f)

直接改配置文件也不行，有什么方法关闭吗

**Comment by TangZihao1997** [comment]
同问

**Comment by JadeVane** [comment]
解决了，直接装回原版yunzai就可以了

https://gitee.com/yoimiya-kokomi/Yunzai-Bot/

**Comment by TangZihao1997** [comment]
> 解决了，直接装回原版yunzai就可以了
> 
> https://gitee.com/yoimiya-kokomi/Yunzai-Bot/

昨天我才知道，在miao-zai，直接使用#原神抽卡记录、#原神武器抽卡记录、这两个就能使用之前的抽卡
