### ISSUE TITLE
提纳里计算问题

### ISSUE THREAD

**Issue by neko-fu** [yoimiya-kokomi/miao-plugin#616]
能否添加重击激化总伤害？
在关闭队伍伤害时，提纳里不计算激化伤害了
![QQ图片20230805223826](https://github.com/yoimiya-kokomi/miao-plugin/assets/118741239/ebcc0bcf-a0db-47ad-853c-0961431541b2)
![QQ图片20230805223846](https://github.com/yoimiya-kokomi/miao-plugin/assets/118741239/dccb6c79-cffa-43ab-b14a-84d74ffef22f)

**Comment by AshenAshes** [comment]
更新已合入#617
