### ISSUE TITLE
#老婆命令一直增加内存占用

### ISSUE THREAD

**Issue by 47479380** [yoimiya-kokomi/miao-plugin#62]
每次使用 `#老婆` 命令，就会增加20mb左右的内存占用

- 使用系统：Debian 
- 系统版本：10.5
- 插件版本：miao-plugin1.8.7

**Comment by yoimiya-kokomi** [comment]
内存占用持续增加不降低，而且稳定增加吗？
更新yunzai至最新版（2.1.9），将日志等级开到debug，重启之后关注下日志中是否有其他信息

内部逻辑上确实有一定的缓存机制但会定期回收，以及对于多次命令也不会累积缓存

**Comment by 47479380** [comment]
> 内存占用持续增加不降低，而且稳定增加吗？ 更新yunzai至最新版（2.1.9），将日志等级开到debug，重启之后关注下日志中是否有其他信息
> 
> 内部逻辑上确实有一定的缓存机制但会定期回收，以及对于多次命令也不会累积缓存

我使用了yunzai 2.1.9重新部署，确实没有内存只升不降的情况了

**Comment by 47479380** [comment]
> > 内存占用持续增加不降低，而且稳定增加吗？ 更新yunzai至最新版（2.1.9），将日志等级开到debug，重启之后关注下日志中是否有其他信息
> > 内部逻辑上确实有一定的缓存机制但会定期回收，以及对于多次命令也不会累积缓存
> 
> 我使用了yunzai 2.1.9重新部署，确实没有内存只升不降的情况了
好吧，还是有问题

日志：
```
yunzai-bot    | [2022-07-11T01:32:21.616] [INFO] recv from: [Private: xxxqq(friend)] 老婆
yunzai-bot    | [2022-07-11T01:32:21.617] [MARK] [私聊][xxx(xxxqq)] 老婆:wife
yunzai-bot    | [2022-07-11T01:32:21.620] [DEBU] 目标UID：220528919,【已存在查询记录】：使用上一次查询过的Cookie UID：220528919
yunzai-bot    | [2022-07-11T01:32:21.621] [DEBU] uid:220528919 添加请求记录uid：220528919 成功
yunzai-bot    | [2022-07-11T01:32:21.622] [DEBU] UID:220528919 记录刷新, 计数：2
yunzai-bot    | [2022-07-11T01:32:21.902] [DEBU] mys查询成功:220528919
yunzai-bot    | [2022-07-11T01:32:21.905] [DEBU] uid:220528919 添加请求记录uid：220528919 成功
yunzai-bot    | [2022-07-11T01:32:21.906] [DEBU] UID:220528919 记录刷新, 计数：2
yunzai-bot    | [2022-07-11T01:32:22.172] [DEBU] mys查询成功:220528919
yunzai-bot    | [2022-07-11T01:32:22.588] [MARK] 图片生成 card:409ms 次数:12
yunzai-bot    | [2022-07-11T01:32:22.607] [DEBU] 开始图片任务，共有1张图片
yunzai-bot    | [2022-07-11T01:32:22.771] [DEBU] 图片任务结束
yunzai-bot    | [2022-07-11T01:32:23.033] [INFO] succeed to send: [Private(xxxxqq)] [图片]

```
内存占用一开始只有130mb左右 发了几十次`#老婆`后
![QQ图片20220711022018](https://user-images.githubusercontent.com/35549419/178157227-0a2d2b98-6336-456f-a3fa-ac6ed3d8cd44.png)

**Comment by yoimiya-kokomi** [comment]
`#老婆` 除了角色信息外其余没有缓存

如果内存占用有增长估计是截图的问题？可以尝试下其他会返回图片的命令，例如`#雷神面板 `
持续一段时间之后看是否有增长

**Comment by 47479380** [comment]
我刚刚试了一下`喵喵帮助`也会涨，好像只要调用了`render`就会涨内存

我之前尝试将`Common.js`调用`render`的那一段注释了，后一直刷，是没有问题的

**Comment by 47479380** [comment]
我跑了一些测试，发现在windows上没问题，使用docker部署Yunzai就有问题。

这里[https://github.com/puppeteer/puppeteer/issues/5893](https://github.com/puppeteer/puppeteer/issues/5893)也有很多遇到一样问题的，都是用的docker部署的，估计是Chromium 的bug。

![QQ图片20220804235703](https://user-images.githubusercontent.com/35549419/182896766-bda1e7f9-0810-4c7a-8054-2c3f6759dd41.png)

然后我又跑了亿点点测试，发现只要将 `resources/common/common.less`文件的引入注释掉就没这个问题了。


![QQ图片20220805010735](https://user-images.githubusercontent.com/35549419/182915576-6f4572b9-7322-4f3e-8571-62f4b8c1d8cd.png)
