### ISSUE TITLE
提纳里组队伤害计算错误

### ISSUE THREAD

**Issue by AizawaHikaru233** [yoimiya-kokomi/miao-plugin#624]
提纳里作为草系本不应该吃到万叶40%增伤，在之前版本插件的情况下是没问题的，而最新版本的插件却计算提纳里伤害享受了万叶40%增伤，最重要的是，提纳里常规配队压根不会考虑携带万叶，在配队伤害里计算苍古万叶本身就很违背常理。我的建议是直接删除万叶的辅助效果，改为计算提八纳钟，增加钟离的20%减抗。

**Comment by AizawaHikaru233** [comment]
附图，旧版和新版伤害对比
![QQ图片20230818231346](https://github.com/yoimiya-kokomi/miao-plugin/assets/79595843/18899dba-4e54-40e2-b149-c7ef9b59375e)
![QQ图片20230818231352](https://github.com/yoimiya-kokomi/miao-plugin/assets/79595843/337533a6-f1e4-4b4f-92fb-bc45a606c5bd)

**Comment by ZM-J** [comment]
看了下，现在没算万叶的元素增伤，但是会算苍古的AZ增伤、大公鸡,，以及万叶的2命+200精通。

不知道会不会有人拿65万叶给提纳里耍猴戏，但是这种耍猴戏的感觉已经脱离了bot的实用性
