### ISSUE TITLE
峡湾长歌与赛诺的计算逻辑异常 显示异常

### ISSUE THREAD

**Issue by neko-fu** [yoimiya-kokomi/miao-plugin#635]
由下(最下边)图，

普攻第一段伤害相同
但赛诺固有天赋一给了精通转伤害
「猜想①」∶固有天赋二没吃到武器特效

强化qte激化总伤害变高
所以激化伤害提高了
「猜想②」∶激化伤害吃到了武器特效

(结论在本文尾段)

验证与计算∶(以下图精一峡湾长歌对照)
———————————————————
 ① 赛诺元素精通373.7+饰金150+开大100=623.7精通(不算峡湾长歌特效)
    623.7×固有天赋150%普攻伤害提升=935.55伤害提升
    与小程序提供的935.6相同，则该过程并未计算峡湾长歌提供的固定精通数值buff
———————————————————
 ② 第一段普攻伤害(暴击伤害)∶
(倍率154.75%×攻击力1152.1+固有天赋二普攻加成935.55)
×(1+爆伤2.08)
×(1+雷伤杯46.6%+二命50%)
×0.5
×0.9
=7407.37
    与小程序算出的7390相差千分之2.3，为等级压制 怪物等级相差1原因，视为验证成立
———————————————————
 ③ q状态·qte强化总伤害(暴击伤害)
    总精通(计算峡湾长歌特效提供)∶
373.7+q提升100+饰金150+峡湾长歌特效120=743.7
    超激化基础伤害加成
1447×1.15×[1+5×743.7/(1200+743.7)]=4847.55

    强化e(qte)激化伤害∶
(倍率282.24%×攻击力1152.1+激化伤害提升4847.55)
×(1+爆伤2.08)
×(1+二命50%+雷伤杯46.6%+固有天赋一35%)
×0.5
×0.9
=25998

    渡荒之雷伤害(不激化)
(固有天赋一100%×攻击力1152.1+固有天赋二250%×不计算峡湾长歌的精通623.7)
×(1+爆伤2.08)
×(1+二命50%+雷伤杯46.6%)
×0.5
×0.9
=7387.82

     渡荒之雷伤害(激化)
(固有天赋一100%×攻击力1152.1+固有天赋二250%×不计算峡湾长歌的精通623.7+激化伤害提升4847.55)
×(1+爆伤2.08)
×(1+二命50%+雷伤杯46.6%)
×0.5
×0.9
=20597

     q状态·qte强化总伤害(强化e激化伤害+渡荒之雷激化伤害+渡荒之雷×2)
=25998+20597+7387.82×2=61370.64
     与小程序差距61370/63671=3.7%
差距过大，假设不成立。
○○○○○○○○○○○○○○
「猜想③」
峡湾长歌精通特效
计入了 激化伤害提升
未计入 固有天赋二的q状态普攻伤害提升
计入了 固有天赋二的渡荒之雷伤害提升

验证与计算∶
计入固有二渡荒之雷伤害净提升∶
峡湾长歌技能120精通×固有天赋二250%
×(1+爆伤2.08)
×(1+46.6%+50%)
×0.5
×0.9
×3道渡荒之雷
=2452.39
上文计算强化qte激化总伤61370.64+2452.39=63823.03
63823.03/63671=1.002387743
差距仍为2.3‰，视为假设成立
(本计算使用为90级怪物，程序使用91级，因而普攻伤害和激化qte都出现了相同的2.3‰的差距)

则，问题有如下
一∶在＃赛诺伤害时，固有天赋二的提升显示错误，
①固有天赋二普攻加成显示与武器不匹配但与程序计算出的伤害匹配(普攻计算实际上是错误的)
②固有天赋二渡荒之雷加成显示与武器特效不匹配且与程序计算出的伤害不匹配(强化qte激化伤害实际上是正确的)

二∶伤害计算错误
普攻伤害未计入固有天赋二对武器峡湾长歌技能提升精通的转化
![Collage_20230903_224857](https://github.com/yoimiya-kokomi/miao-plugin/assets/118741239/752385b7-2c9d-4322-96af-ebdf6fafff7a)
![Cache_-20a24be7d72432](https://github.com/yoimiya-kokomi/miao-plugin/assets/118741239/ab918c37-b76b-47c0-a623-0ca62fba3f29)
![Cache_-4e69918c8c83dda5](https://github.com/yoimiya-kokomi/miao-plugin/assets/118741239/0e17e7ce-f23f-4f39-bda2-d49eb6a88b44)

**Comment by AshenAshes** [comment]
感谢反馈，已在今天的更新中修了，可以看一下还有没有问题

**Comment by neko-fu** [comment]
> 

OK！没有问题非常完美，感谢回复和改动

**Comment by neko-fu** [comment]
> 感谢反馈，已在今天的更新中修了，可以看一下还有没有问题

OK！没有问题非常完美，感谢回复和改动
