### ISSUE TITLE
伤害计算相关

### ISSUE THREAD

**Issue by NRZ091** [yoimiya-kokomi/miao-plugin#67]
夜兰的天赋一当获取面板时夜兰在队伍中时会被计算两次（即获取面板时天赋一效果被读取后，伤害计算下的buff区还会在算一次）
而绿剑则获取时效果不计入面板，只在伤害计算buff区计算

**Comment by yoimiya-kokomi** [comment]
此问题短期内无解。夜兰出场时，从好友面板中查看的原始数据就是错误的，包含被动效果
短期内的建议就是请在夜兰不出场时获取面板数据

另一种方案时不使用游戏内的面板数据，直接根据圣遗物词条及武器效果计算最终面板
但整体工作量也不小，暂时不会使用这种方案

**Comment by NRZ091** [comment]
好的
