### ISSUE TITLE
群内排名改成有ck才能加入之后，星铁的榜就全没了

### ISSUE THREAD

**Issue by BaiMaollk** [yoimiya-kokomi/miao-plugin#675]
![8fc17f1e8d3def50f10539cc48b6a787](https://github.com/yoimiya-kokomi/miao-plugin/assets/75015352/bd47df2d-d9b9-4d8e-930c-fa7cab5ef4b5)

**Comment by BaiMaollk** [comment]
而且更新面板有问题，明明#扫码登录了的，但是更新面板时还是说没有ck参与不了
![997bad346b80847a5e7034d78eae327c](https://github.com/yoimiya-kokomi/miao-plugin/assets/75015352/a4645ceb-d386-4ad0-8369-6f946352aa86)

**Comment by BaiMaollk** [comment]
#刷新排名#重置排名都试过了，影响不了星铁的榜，而且好像没有*刷新排名*重置排名的指令、

**Comment by BaiMaollk** [comment]
已经扫码登陆过的，有ck的，
![dc558f148f31193a55b32253a750068e](https://github.com/yoimiya-kokomi/miao-plugin/assets/75015352/ed40649c-5abd-4375-b82e-a370de0a4270)

**Comment by BaiMaollk** [comment]
这是喵喵设置的界面
![b7a969a1f8d0f0b532c6ce13e5a6119a](https://github.com/yoimiya-kokomi/miao-plugin/assets/75015352/77807d92-0cdb-4eab-af31-06f3f394ebdc)

**Comment by yrain21** [comment]
更新到最新版本，*刷新排行 *更新面板 应该都可以了

**Comment by BaiMaollk** [comment]
> 更新到最新版本，*刷新排行 *更新面板 应该都可以了

谢谢
