### ISSUE TITLE
botqq群怎么进啊QWQ搜不到怎么办？

### ISSUE THREAD

**Issue by nine-an** [yoimiya-kokomi/miao-plugin#7]
大佬，bot群怎么进啊QWQ!我想申请api的！

**Comment by yeiang** [comment]
我也想进群，但是不知道，恳请大佬，引进

**Comment by lrf1999** [comment]
+1

**Comment by yoimiya-kokomi** [comment]
Yunzai-bot官方群开放之前可以先加miao-plugin群：607710456

**Comment by DreamLumine** [comment]
> Yunzai-bot官方群开放之前可以先加miao-plugin群：607710456

[https://s2.loli.net/2022/05/21/5WueFRJsmKrnHi9.png](url)
搜索不到

**Comment by zizxzy** [comment]
> Yunzai-bot官方群开放之前可以先加miao-plugin群：607710456

这个群也查不到了

**Comment by honfeng** [comment]
完全搜不到群

**Comment by AshJordanZhao** [comment]
> Yunzai-bot官方群开放之前可以先加miao-plugin群：607710456

这个群搜索不到啊

**Comment by honfeng** [comment]
用群号搜不到群 没开放群号搜索或者被屏蔽了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: AshJordanZhao ***@***.***>
发送时间: Thursday, May 26, 2022 9:00:57 PM
收件人: yoimiya-kokomi/miao-plugin ***@***.***>
抄送: honfeng ***@***.***>; Comment ***@***.***>
主题: Re: [yoimiya-kokomi/miao-plugin] botqq群怎么进啊QWQ搜不到怎么办？ (Issue #7)


Yunzai-bot官方群开放之前可以先加miao-plugin群：607710456

这个群搜索不到啊

―

**Comment by yoimiya-kokomi** [comment]
嗯，确实暂时停止新加入了

**Comment by liuzj288** [comment]
yunzai主群：213938015（暂停加入）
miaomiao分群：607710456（暂停加入）
我的交流群：416120135
