### ISSUE TITLE
星铁群排名功能无数据

### ISSUE THREAD

**Issue by TheTychoStar** [yoimiya-kokomi/miao-plugin#705]
更新喵喵后，原神的群排名功能正常，但星铁的排名均不显示数据。
已经尝试过重启bot/刷新群排名/重置角色排名/更新面板，均无效果。
症状如下：
![07b4054b8691c89bcaad31441992f39f](https://github.com/yoimiya-kokomi/miao-plugin/assets/75252778/8a36ddbe-d8c0-465a-bc6d-4de804f07ac3)
日志也看不出哪里有错误：

> 1|Miao-Yunzai  | [MiaoYz][00:18:32.594][MARK] [喵喵:角色面板][rankList][意式*******] #希儿排名
>1|Miao-Yunzai  | [MiaoYz][00:18:32.603][DEBU] [图片生成][使用模板] ./temp/html/miao-plugin/character/rank-profile-list/1102.html
>1|Miao-Yunzai  | [MiaoYz][00:18:34.804][MARK] [图片生成][miao-plugin/character/rank-profile-list][2次] 104.74KB 2200ms
>1|Miao-Yunzai  | [MiaoYz][00:18:34.806][DEBU] 开始图片任务，共有1张图片
>1|Miao-Yunzai  | [MiaoYz][00:18:34.807][DEBU] send:ImgStore.GroupPicUp seq:1791
>1|Miao-Yunzai  | [MiaoYz][00:18:34.888][DEBU] recv:ImgStore.GroupPicUp seq:1791
>1|Miao-Yunzai  | [MiaoYz][00:18:34.888][DEBU] 图片任务结束

**Comment by AshenAshes** [comment]
星铁功能用*开头

**Comment by TheTychoStar** [comment]
> 星铁功能用*开头

原来如此，以前星铁排名是可以用#的，现在分开了么。谢谢。
