### ISSUE TITLE
无法上传深渊数据

### ISSUE THREAD

**Issue by MLYSCEM** [yoimiya-kokomi/miao-plugin#72]
如题

**Comment by yoimiya-kokomi** [comment]
后台有无什么报错或提示信息？

**Comment by MLYSCEM** [comment]
![IMG_20220722_002556](https://user-images.githubusercontent.com/109544711/180265350-68cb3501-610b-4ce6-853c-a773c3efdfa2.jpg)
如图

**Comment by MLYSCEM** [comment]
这是怎么回事啊

**Comment by yoimiya-kokomi** [comment]
确认yunzai及miaomiao均更新至最新版
同用户通过#角色 #深渊12层 等命令查看下能否正常访问米游社信息

若能够正常展示，bot所在机器尝试访问下 http://49.232.91.210/miaoPlugin/hutaoApi 看能否访问得通
