### ISSUE TITLE
关于圣遗物评分

### ISSUE THREAD

**Issue by Yuugure-Yuu** [yoimiya-kokomi/miao-plugin#73]
个人感觉圣遗物评分一直比较乱，但充能效率对每个角色都有用，应该都算分吧

**Comment by yoimiya-kokomi** [comment]
目前评分的权重逻辑是与提瓦特小助手、原魔工具箱等方一同拉齐的
当然因为参与方较多，所以也很难有一套完全无争议的权重规则
具体角色的评分如果有意见可以反馈，规则以及流派判定也会持续更新
