### ISSUE TITLE
开启排行限制后，不符合条件的排到了最前面

### ISSUE THREAD

**Issue by lin-junliang** [yoimiya-kokomi/miao-plugin#730]
![image](https://github.com/yoimiya-kokomi/miao-plugin/assets/59049320/0e32706c-ef79-4471-9be3-a64b110497e4)
开启排行限制后，不符合条件的不会显示伤害了，但是排名却去到了最前面

**Comment by lin-junliang** [comment]
已解决
进 redis 目录输redis-cli flushall

**Comment by AshenAshes** [comment]
下次碰到这种情况试试先*重置排名，然后*刷新排名
