### ISSUE TITLE
安装了image-size运行依然报错

### ISSUE THREAD

**Issue by marvinli001** [yoimiya-kokomi/miao-plugin#75]
![image](https://user-images.githubusercontent.com/44795725/180754599-fcb4d4c9-863a-47ae-93c6-f11df315f45a.png)
安装了image-size之后运行bot依然有报错
![image](https://user-images.githubusercontent.com/44795725/180754686-817cc8b7-642d-4351-a0eb-5cb249882418.png)
大佬救救

**Comment by ShiinaRinne** [comment]
我没接触过nodejs和这个项目源码，仅说一下我解决的方式
试试**在yunzai的安装目录**执行你之前用的安装命令，或者用yarn安装(yarn需要额外下载)
`yarn add image-size`
如果还是不行可以试着改一下Character.js中的代码，没试过，不保证能用。
import换成这样的(来自官方文档)
`const sizeOf = require('image-size')`

我使用npm安装之后没有缺失包的问题了，但出现了另一个错误，重新装一下依赖就可以
`pnpm install -P`

如果仍没有解决，就等作者回复吧~

![image](https://user-images.githubusercontent.com/45081750/180760943-45e35c10-e782-4f0f-aac5-6eacf613a9c1.png)

**Comment by yoimiya-kokomi** [comment]
> ![image](https://user-images.githubusercontent.com/44795725/180754599-fcb4d4c9-863a-47ae-93c6-f11df315f45a.png) 安装了image-size之后运行bot依然有报错 ![image](https://user-images.githubusercontent.com/44795725/180754686-817cc8b7-642d-4351-a0eb-5cb249882418.png) 大佬救救

依赖缺失，在yunzai根目录下执行npm install image-size 安装即可
看你的截图是在~目录下执行的而不是yunzai
