### ISSUE TITLE
新的1.9.0插件兼容2.1.8云崽吗？

### ISSUE THREAD

**Issue by kikasyou** [yoimiya-kokomi/miao-plugin#76]
如果不兼容的话我就继续用1.8.9吧。

**Comment by Yamakoer** [comment]
兼容，可以使用

**Comment by yoimiya-kokomi** [comment]
支持，并且miao-plugin目前v3yunzai是初步兼容，还有一些功能未适配
如果为了稳定使用短期内仍然推荐用v2yunzai

v2yunzai可以切换到这个分支
https://github.com/yoimiya-kokomi/Yunzai-Bot
