### ISSUE TITLE
3.0 还是放在plugins里吗

### ISSUE THREAD

**Issue by wooodswu** [yoimiya-kokomi/miao-plugin#77]
miao-plugin 好像没有反应

**Comment by yoimiya-kokomi** [comment]
位置不变，放进去后重启
如果没有反应确认下版本以及路径是否有误，以及启动的是否是对应目录的yunzai

**Comment by wooodswu** [comment]
> 位置不变，放进去后重启
> 如果没有反应确认下版本以及路径是否有误，以及启动的是否是对应目录的yunzai
我看启动的就是Yunzai_Bot

<img width="563" alt="image" src="https://user-images.githubusercontent.com/87766834/180967463-ce45e311-0def-4c4e-9ef9-0df6719059d1.png">

**Comment by wooodswu** [comment]
> > 位置不变，放进去后重启
> > 如果没有反应确认下版本以及路径是否有误，以及启动的是否是对应目录的yunzai
> > 我看启动的就是Yunzai_Bot
> 
> <img alt="image" width="563" src="https://user-images.githubusercontent.com/87766834/180967463-ce45e311-0def-4c4e-9ef9-0df6719059d1.png">

我先试了3.0 发现没有反应 就试了一下2.2.0, 是要改哪个路径的yunzai？

**Comment by wooodswu** [comment]
> 位置不变，放进去后重启
> 如果没有反应确认下版本以及路径是否有误，以及启动的是否是对应目录的yunzai

<img width="565" alt="image" src="https://user-images.githubusercontent.com/87766834/180972777-8a6deddb-c642-4365-b3c3-1fe2999e67b3.png">
现在是这个错了

**Comment by wooodswu** [comment]
> 位置不变，放进去后重启
> 如果没有反应确认下版本以及路径是否有误，以及启动的是否是对应目录的yunzai

显示我自己不是主人，但是我删过Yunzai-Bot/config/config.js 重新设置过了
