### ISSUE TITLE
喵喵设置，喵喵更新为什么显示我不是主人

### ISSUE THREAD

**Issue by wooodswu** [yoimiya-kokomi/miao-plugin#78]
我明明已经重启过，甚至还把config.js 文件删了重新node app, 没填错主人qq号，还是不行，其他功能能用，就是“只有主人才能命令喵喵哦~”

**Comment by yoimiya-kokomi** [comment]
请提供更多信息，比如yunzai的版本号以及miao-plugin的版本号，运行环境等

**Comment by wooodswu** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/87766834/182011086-0f63e4bf-9d0a-4b88-833d-73a906b262df.png">
yunzai 2.2.0 & miao-plugins 1.9.0

**Comment by yoimiya-kokomi** [comment]
看下yunzai自身主人可用的命令是否有效，例如`#重置用户缓存`

**Comment by wooodswu** [comment]
> 看下yunzai自身主人可用的命令是否有效，例如`#重置用户缓存`

<img width="656" alt="D14C5C45-09E3-4DEE-9EBA-002B1036C080" src="https://user-images.githubusercontent.com/87766834/182081078-468ed8b8-c6cb-4f2a-8146-2f9206099037.png">
我试过了，没有反应（没有做任何更新）

**Comment by yoimiya-kokomi** [comment]
我感觉你的设置有问题，bot的master就没生效
检查下 config/config.js 的 masterQQ 字段

例如： masterQQ: [ 123456 ],
