### ISSUE TITLE
[功能请求]直接从米游社而非第三方平台获取面板数据

### ISSUE THREAD

**Issue by ZM-J** [yoimiya-kokomi/miao-plugin#782]
众所周知，米游社近期有一个史诗级更新，可以允许用户直接通过米游社查看角色的面板。

这样一来，除了展示的8个角色，理论上有了ck，不需要访问第三方面板查询平台 api（如 enka.network），直接走米游社接口，就能拿到**所有**角色的面板。

总之，先评估一下这样做的必要性？

**Comment by devil233-ui** [comment]
相当容易触发马（）

**Comment by qingnning** [comment]
确实相当容易触发验证码

**Comment by ZM-J** [comment]
> 相当容易触发马（）

所以说只是个功能集成，yaml 配置文件里面自行选择面板更新来源

换言之，功能有没有是一回事，用不用是另外一回事

**Comment by devil233-ui** [comment]
> > 相当容易触发马（）
> 
> 所以说只是个功能集成，yaml 配置文件里面自行选择面板更新来源
> 
> 换言之，功能有没有是一回事，用不用是另外一回事

然后就会有一堆人触发马跑来说

**Comment by ZM-J** [comment]
> > > 相当容易触发马（）
> > 
> > 
> > 所以说只是个功能集成，yaml 配置文件里面自行选择面板更新来源
> > 换言之，功能有没有是一回事，用不用是另外一回事
> 
> 然后就会有一堆人触发马跑来说

那可以做绝一点，譬如新开个命令 `#米游社更新面板`，包括引入对应的 yaml 字段

**该字段默认设置为 false，仅管理员可将其设置为 true（也就是说后果自负）**

**Comment by kissnavel** [comment]
好的，你快写一个，避免账号异常隔壁有现成的

**Comment by ZM-J** [comment]
> 好的，你快写一个，避免账号异常隔壁有现成的

别说了，一堆屁事在等着我，原 5.0 的主线都没过完（
