### ISSUE TITLE
[功能请求]针对`#角色列表`加入筛选功能，以查看幻想真境剧诗要求

### ISSUE THREAD

**Issue by ZM-J** [yoimiya-kokomi/miao-plugin#788]
e.g., `#水火雷角色列表`，仅展示拥有的所有属性为水、火、雷的角色列表

结合左侧编号，就能较直观地查看当前角色是否满足当期幻想真境剧诗的角色数量要求

**Comment by TheTychoStar** [comment]
好主意，但是否还要把每期的开幕角色和特邀角色也考虑进去，会增加更新时的工作量。

**Comment by ZM-J** [comment]
> 好主意，但是否还要把每期的开幕角色和特邀角色也考虑进去，会增加更新时的工作量。

这个就先不管了，提供一个大概的查看就行了

开幕角色和特邀角色不知道有什么接口可以查到捏

**Comment by ZM-J** [comment]
> 好主意，但是否还要把每期的开幕角色和特邀角色也考虑进去，会增加更新时的工作量。

这个不知道可以不可以直接用玉衡杯数据库的资源，但是他那个数据里面的 `Time` 字段跟实际的挑战月份对不上，不知道该怎么对了

**Comment by ZM-J** [comment]
> > 好主意，但是否还要把每期的开幕角色和特邀角色也考虑进去，会增加更新时的工作量。
> 
> 这个不知道可以不可以直接用玉衡杯数据库的资源，但是他那个数据里面的 `Time` 字段跟实际的挑战月份对不上，不知道该怎么对了

想到了，可以用月份进行硬编码（

**Comment by TheTychoStar** [comment]
> > > 好主意，但是否还要把每期的开幕角色和特邀角色也考虑进去，会增加更新时的工作量。
> > 
> > 
> > 这个不知道可以不可以直接用玉衡杯数据库的资源，但是他那个数据里面的 `Time` 字段跟实际的挑战月份对不上，不知道该怎么对了
> 
> 想到了，可以用月份进行硬编码（

太厉害了佬，点赞。

**Comment by ZM-J** [comment]
> > > > 好主意，但是否还要把每期的开幕角色和特邀角色也考虑进去，会增加更新时的工作量。
> > > 
> > > 
> > > 这个不知道可以不可以直接用玉衡杯数据库的资源，但是他那个数据里面的 `Time` 字段跟实际的挑战月份对不上，不知道该怎么对了
> > 
> > 
> > 想到了，可以用月份进行硬编码（
> 
> 太厉害了佬，点赞。
> 
> 试了一下，很好用。有个小提议，是否可以在输出结果里加上显示当期的可出战属性、开幕角色和特邀角色的内容。不用很花哨的，就用文字在图片最上或最下显示一下就好，也节省空间。另外现在的展示顺序是所有可出战角色按照练度混在一起排的，我个人的感觉，未来如果能够按角色属性、开幕角色和特邀角色进行分组展示就更好了。

这个现在是复用了之前的练度模板，我审美有问题，不太会调前端这玩意儿

倒是可以通过输出消息的方式来做

**Comment by ZM-J** [comment]
现在暂时就这样吧

**Comment by TheTychoStar** [comment]
> 现在暂时就这样吧

感恩大佬，太棒了
