### ISSUE TITLE
更新面板请求失败

### ISSUE THREAD

**Issue by wuweidmw** [yoimiya-kokomi/miao-plugin#79]
![P@~)`_XPNX_KV({ 310@O`J](https://user-images.githubusercontent.com/104341076/181068190-bc31a8db-6393-4c68-ad75-f471371b34fa.png)
官服uid全部请求失败，之前有可以查看，但不能更新，b服的可以正常使用。

**Comment by yoimiya-kokomi** [comment]
参见 https://github.com/yoimiya-kokomi/miao-plugin/issues/63#issue-1299812134
