### ISSUE TITLE
获取原图一直输出空调师傅

### ISSUE THREAD

**Issue by xingyu42** [yoimiya-kokomi/miao-plugin#824]
![image](https://github.com/user-attachments/assets/b59ad4e9-86ad-499e-8d14-b11218c0260b)
关闭获取原图还是输出师傅，怀疑 imgPath 这个没有获取到

**Comment by ye3011** [comment]
icqq1.3.2？

**Comment by xingyu42** [comment]
是



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月9日(周六) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoimiya-kokomi/miao-plugin] 获取原图一直输出空调师傅 (Issue #824)




 
icqq1.3.2？

**Comment by ye3011** [comment]
降级就好了

**Comment by xingyu42** [comment]
请问降到哪个版本好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月9日(周六) 下午4:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoimiya-kokomi/miao-plugin] 获取原图一直输出空调师傅 (Issue #824)




 
降级就好了

**Comment by ye3011** [comment]
只要不是1.3.2就行

**Comment by xingyu42** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月9日(周六) 晚上10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoimiya-kokomi/miao-plugin] 获取原图一直输出空调师傅 (Issue #824)




 
只要不是1.3.2就行
