### ISSUE TITLE
装不上，怎么弄啊

### ISSUE THREAD

**Issue by muguodiao** [yoimiya-kokomi/miao-plugin#83]
![image](https://user-images.githubusercontent.com/105115300/181785738-2a664a74-4e99-4215-8909-6cf6c965ca72.png)
![image](https://user-images.githubusercontent.com/105115300/181785813-65c2d5dc-95d8-472d-aef2-fddf8f005e8e.png)

**Comment by ShiinaRinne** [comment]
试试清除缓存，使用yarn或cnpm

**Comment by muguodiao** [comment]
![image](https://user-images.githubusercontent.com/105115300/181800397-58ea0a00-35c4-4673-b78c-08cb5104fb50.png)

**Comment by ShiinaRinne** [comment]
> ![image](https://user-images.githubusercontent.com/105115300/181800397-58ea0a00-35c4-4673-b78c-08cb5104fb50.png)

https://github.com/yoimiya-kokomi/miao-plugin/issues/74#issuecomment-1199638759
这东西应该不需要再发个issue...

**Comment by yoimiya-kokomi** [comment]
上面的回复的issue是对的
以及这个就是正常安装一个依赖，问题比较基础，可自行百度解决
