### ISSUE TITLE
发送【#喵喵更新】后一直重复这个，正常吗

### ISSUE THREAD

**Issue by muguodiao** [yoimiya-kokomi/miao-plugin#87]
![image](https://user-images.githubusercontent.com/105115300/182020655-a0990e4a-3dd7-4f2c-b012-d41b2455a2f2.png)

**Comment by muguodiao** [comment]
重启后再发，提示1.9.2了，

**Comment by yoimiya-kokomi** [comment]
npm run stop后重开
