### ISSUE TITLE
3.0 喵喵插件 运行报错

### ISSUE THREAD

**Issue by HuIn2479** [yoimiya-kokomi/miao-plugin#88]
![Screenshot_2022-08-01-05-45-34-319_com.server.auditor.ssh.client.png](https://user-images.githubusercontent.com/66163050/182046899-65e87865-ac52-42c1-b603-dbdc989276d4.png)

**Comment by liuly0322** [comment]
看起来是 docker 部署的问题，应该是 Yunzai 在更新了 pnpm workspace 后 docker 脚本没有相对应的更新，建议在 Yunzai 下反馈
