### ISSUE TITLE
yunzai3.0.0和miao-plugin1.9.3下部分命令无效

### ISSUE THREAD

**Issue by SamizuHM** [yoimiya-kokomi/miao-plugin#89]
![QQ截图20220801153051](https://user-images.githubusercontent.com/51712552/182096535-fff1aae6-6157-498c-89a4-d0e4aea1d99b.jpg)
#用户统计 和 #重置用户缓存 命令无效，管理员命令 #喵喵设置 有效

**Comment by RockRadix** [comment]
因为这个功能云崽都还没有写

**Comment by liuly0322** [comment]
此外还有
https://github.com/yoimiya-kokomi/miao-plugin/blob/4333ef81efb00968135f5724ca169578fb9b32b3/resources/help/help-cfg_default.js#L91-L93
这个似乎是明确被 Yunzai 移除了（[commit](https://github.com/Le-niao/Yunzai-Bot/commit/489d123ee4799f8691a1cc40a22479a829d3436a)），大概也可以删去了

**Comment by SamizuHM** [comment]
> 因为这个功能云崽都还没有写

谢谢，之前以为这是插件的功能呢
