### ISSUE TITLE
关于 dispatch log 的优化

### ISSUE THREAD

**Issue by liuly0322** [yoimiya-kokomi/miao-plugin#90]
关闭 dispatch 进入时的 log 而保留插件正常执行结束时的 log，因为比较 tricy 所以提个 issue 讨论一下：

Yunzai 中的 log 显示有两处：

- ```js
  if (res !== false) {
    if (v.log !== false) {
      logger.mark(`${e.logFnc} ${lodash.truncate(e.msg, { length: 80 })} 处理完成 ${Date.now() - start}ms`)
    }
    break a
  }
  ```

- ```js
  if (v.log !== false) {
    logger.mark(`${e.logFnc}${e.logText} ${lodash.truncate(e.msg, { length: 80 })}`)
  }
  ```

为了在第一处返回 false，第二处返回 true，可以使用 getter 来产生计算属性：

https://github.com/yoimiya-kokomi/miao-plugin/blob/4333ef81efb00968135f5724ca169578fb9b32b3/adapter/index.js#L13-L16

将这里的 rule 改为：

```js
get rule() {
  return [
    {
      reg: '.+',
      fnc: 'dispatch',
      before_dispatch: true,
      get log() {
        if (this.before_dispatch) {
          this.before_dispatch = false
          return false
        }
        return true
      },
    },
  ]
},
```

这样每次对插件 rule 的访问都会产生一个新的对象，新的对象维护了 `before_dispatch` 记录当前执行阶段，对该对象的 log 属性的访问当且仅当第一次会返回 false

效果：

```
[YzBot][18:27:48.116][INFO] recv from: [Private: *********(friend)] #胡桃
# 这里没有复读
[YzBot][18:27:48.160][MARK] [米游社查询][uid：*********][使用已绑定ck：********]
[YzBot][18:27:48.427][MARK] [图片生成][miao-plugin/character/card][3次] 232.30kb 262ms
[YzBot][18:27:49.418][INFO] succeed to send: [Private(*********)] [图片]
# 这里正常发送了结束信息
[YzBot][18:27:49.419][MARK] [miao-plugin][dispatch] #角色详情 处理完成 1261ms
```

**Comment by yoimiya-kokomi** [comment]
嗯，现在v3的适配还比较简单，日志相关的优化还没进行，后面会优化一下~

你的方案整体是ok的，不过log的值依赖于调用顺序，万一yunzai 访问log的顺序或次数变化就会有影响
会稍微调整下，仍然使用计算属性返回log，默认返回false，在dispatch() ret===true时修改自身属性值，后续返回true
