### ISSUE TITLE
V3bot#喵喵更新命令报错，#原石统计命令无效

### ISSUE THREAD

**Issue by ChthollyWn** [yoimiya-kokomi/miao-plugin#92]
![image](https://user-images.githubusercontent.com/85938618/182165170-320cd883-16da-4603-8409-324b4b220d33.png)
![image](https://user-images.githubusercontent.com/85938618/182165259-fb9fc8a6-83e7-402c-80f6-8104090c78ca.png)
使用喵喵更新命令时后台报错
![image](https://user-images.githubusercontent.com/85938618/182165472-13b9a21d-f2dd-4ff2-a3f2-e85f6dac8189.png)
![image](https://user-images.githubusercontent.com/85938618/182165526-0b6a4230-15a3-4ebf-b100-179c114ea489.png)
使用原石统计命令没有反应

**Comment by liuly0322** [comment]
#原石统计 是 Yunzai 自带的功能，请检查 Yunzai 版本

更新失败是因为更改了配置文件，注意：

```js
/*
* 如需配置【复制】此文件，改名为profile.js
* 暂未做热更新，修改完毕请重启yunzai
* */
```

先保存你的 `conponents/profile_data/enka.js` 和 `config/profile_default.js`，从图上看这些是你更改过的文件

然后暂时关闭 bot，终端输入

```bash
git restore
```

以撤销更改，然后再次开启 bot 即可使用更新功能

**Comment by yoimiya-kokomi** [comment]
liuly0322的回复是对的~

conponents/profile_data/enka.js：
尽量不要直接修改bot文件，如果修改也请在更新后重新修改而不要盖回去旧版本文件，否则可能会有异常问题

config/profile_default.js：
如需配置复制为 config/profile.js 进行配置，修改_default.js无效
