### ISSUE TITLE
达达利亚的普攻等级皇冠显示问题

### ISSUE THREAD

**Issue by Aleafysuki** [yoimiya-kokomi/miao-plugin#98]
达达利亚的被动天赋可以提升普攻等级1级（即使不在队伍中也会对自己生效）。
因此当他的普攻等级被点满（游戏中赋予皇冠）之后，显示的普通攻击等级是11，逻辑层面上，这里应该也要显示一个智识之冕才对。可能需要在普攻赋冠的区域再套一层逻辑判断。
![image](https://user-images.githubusercontent.com/82559156/182531583-3bc728b5-aacc-4c2f-b31f-3b2fda50691c.png)

**Comment by liuly0322** [comment]
可能的修改：

https://github.com/yoimiya-kokomi/miao-plugin/blob/5dbdc5f7405b0c7e53784e8128f4bf0bbfac15c0/resources/character/detail.html#L24

talent[key].original >= 10

**Comment by Aleafysuki** [comment]
> 可能的修改：
> 
> https://github.com/yoimiya-kokomi/miao-plugin/blob/5dbdc5f7405b0c7e53784e8128f4bf0bbfac15c0/resources/character/detail.html#L24
> 
> talent[key].original >= 10

感谢，实测可行！我稍后看看是否要提一个pull request

**Comment by yoimiya-kokomi** [comment]
多谢，已经在新版本中fix~
