### ISSUE TITLE
绫华的面板建议

### ISSUE THREAD

**Issue by Yuugure-Yuu** [yoimiya-kokomi/miao-plugin#99]
1. 充能算分。
2. 伤害期望计入双冰+冰附着的35暴击和双冰冻结的55暴击两种暴击率或者只根据双冰冻结下的暴击计算，方便比较圣遗物。

**Comment by yoimiya-kokomi** [comment]
部分角色的充能权重在新版本中已经补充，包括绫华

伤害期望增加双冰共鸣在规划中，后期会支持
